- include/functions.h
- include/types.h
- src/cugraph.cu
- src/graph_utils.cuh
- src/tests/gdf_graph/gdf_graph.cu
- src/tests/test_utils.h
This addresses the C++/CUDA part for #17. 
I also added a feature allowing conversion from adjacency list to edge list.
> [REVIEW] Retrieve vertex/edge indices from adjacency list 

- include/rmm_utils.h
- src/COOtoCSR.cuh
- src/cugraph.cu
- src/graph_utils.cuh
- src/grmat.cu
- src/nvgraph_gdf.cu
- src/pagerank.cu
- src/tests/gdf_graph/gdf_graph.cu
- src/tests/grmat/grmat_test.cu
- src/tests/nvgraph_plugin/nvgraph_gdf_jaccard.cpp
- src/tests/nvgraph_plugin/nvgraph_gdf_louvain.cpp
- src/tests/test_utils.h
Merge and resolve conflicts in Andrei's PR #39 with master
> [WIP] Andrei rmm changelist

- conda/environments/cugraph_dev.yml
updated the conda environment to include nvgraph
> [REVIEW] added nvgraph and set minimal cuDF version

- ci/checks/changelog.sh
- ci/checks/style.sh
- ci/cpu/build.sh
- ci/cpu/cugraph/build_cugraph.sh
- ci/cpu/cugraph/upload-anaconda.sh
- ci/cpu/libcugraph/build_libcugraph.sh
- ci/cpu/libcugraph/upload-anaconda.sh
- ci/gpu/build.sh
- ci/release/update-version.sh
- conda/recipes/cugraph/build.sh
- conda/recipes/libcugraph/build.sh
- conda/recipes/libcugraph/meta.yaml
- requirements.txt
- setup_pip.py
My initial pass at the gpuCI scripts.
> [WIP] Initial gpuCI scripts

- CHANGELOG.md
- cpp/src/cugraph.cu
- python/cugraph/graph/c_graph.pyx
- python/cugraph/graph/test_graph.py
Close Issue #59 
Fixed segfault issue by adding checks into graph methods for computing edge list and transpose. Added some additional helper methods on python graph object. Added tests verifying bug fix and fixed some issue in existing tests.
> Issue 59 Bug fix

- CHANGELOG.md
- python/cugraph/bfs/test_bfs.py
- python/cugraph/jaccard/test_jaccard.py
- python/cugraph/louvain/test_louvain.py
- python/cugraph/pagerank/test_pagerank.py
- python/cugraph/spectral_clustering/test_balanced_cut.py
> [REVIEW] test vertex and edge identifiers

- cpp/src/cugraph.cu
- python/cugraph/bfs/bfs_wrapper.pyx
> [REVIEW] Fixed BFS to generate the adjacency list if it's not present when called

- CHANGELOG.md
- python/cugraph/louvain/louvain_wrapper.pyx
> [REVIEW] Fixed Louvain to generate adjacency list if only edge list present

- ci/cpu/cugraph/upload-anaconda.sh
- ci/cpu/libcugraph/upload-anaconda.sh
- ci/cpu/prebuild.sh
- conda/recipes/cugraph/build.sh
Adds the `prebuild.sh`. This sets various flags used in the main build scripts.
> Bld ci script updates

- CHANGELOG.md
- ci/cpu/cugraph/build_cugraph.sh
- ci/cpu/libcugraph/build_libcugraph.sh
- conda/recipes/cugraph/meta.yaml
- conda/recipes/libcugraph/meta.yaml
- conda_build.sh
Updates to cugraph/libcugraph dependencies to grab cuDF 0.6.0
> BLD Update conda recipes

- CHANGELOG.md
- cpp/include/functions.h
> WIP documentation

- CHANGELOG.md
- cpp/src/nvgraph_gdf.cu
> Disable terminal output in sssp

- CHANGELOG.md
- README.md
Fixes a few typos in the README introduction.
> Fix typos in readme intro

- CHANGELOG.md
- cpp/include/functions.h
- cpp/src/cugraph.cu
- cpp/src/nvgraph_gdf.cu
- cpp/src/tests/gdf_graph/gdf_graph.cu
- cpp/src/tests/grmat/grmat_test.cu
- cpp/src/tests/nvgraph_plugin/nvgraph_gdf_sssp.cpp
- cpp/src/tests/pagerank/pagerank_test.cu
- python/cugraph/cugraph.pyx
- python/cugraph/graph/c_graph.pxd
- python/cugraph/graph/c_graph.pyx
- python/cugraph/graph/test_graph.py
- python/cugraph/pagerank/pagerank_wrapper.pyx
- python/cugraph/sssp/sssp_wrapper.pyx
> [REVIEW] Bug cudf & cugraph interoperability issue

- CHANGELOG.md
- cpp/src/cugraph.cu
- cpp/src/nvgraph_gdf.cu
- python/cugraph/graph/c_graph.pyx
- python/cugraph/louvain/louvain_wrapper.pyx
- python/cugraph/louvain/test_louvain.py
- python/cugraph/spectral_clustering/test_balanced_cut.py
> [REVIEW] fix segfault when edgevals not provided

- CHANGELOG.md
- README.md
- conda/environments/cugraph_nightly.yml
- conda/environments/cugraph_nightly_cuda10.yml
- Removed pip from README and fixed section links
- fixed nightly conda environment
> [REVIEW] MInor update to README and nightly 

- CHANGELOG.md
- conda/environments/cugraph_dev.yml
- conda/environments/cugraph_dev_cuda10.yml
- conda/environments/cugraph_nightly.yml
- conda/environments/cugraph_nightly_cuda10.yml
Add rmm to the conda configuration.  Addresses issue #242
> [REVIEW] Add rmm to the conda configuration

- CHANGELOG.md
- conda/environments/builddocs.yml
- conda/environments/cugraph_dev.yml
- conda/environments/cugraph_dev_cuda10.yml
Updated dependencies on cudf, rmm and nvstrings.
> [REVIEW] Update conda environment

- CHANGELOG.md
- cpp/include/cugraph.h
- cpp/src/converters/renumber.cuh
- cpp/src/tests/components/con_comp_test.cu
- cpp/src/utilities/grmat.cu
- python/cugraph/graph/c_graph.pxd
Updates to accommodate new cudf include file locations
NOTE: my editor is configured to automatically remove trailing whitespace on file save, so those changes are in the commit too.
> Updates to accommodate new cudf include file locations

- CHANGELOG.md
- cpp/include/algorithms.h
- cpp/include/functions.h
- cpp/src/snmg/link_analysis/pagerank.cu
- cpp/src/structure/cugraph.cu
- python/cugraph/cugraph.pyx
- python/cugraph/graph/c_graph.pyx
- python/cugraph/mg_pagerank/c_mg_pagerank.pxd
- python/cugraph/mg_pagerank/mg_pagerank_wrapper.pyx
- python/cugraph/utils/pointer_utils.pyx
Added python wrapper for multi gpu pagerank algorithm.
Added mg_pagerank test function to verify end to end working
> [WIP] snmg python wrapper

- CHANGELOG.md
- cpp/CMakeLists.txt
- cpp/include/algorithms.h
- cpp/src/snmg/COO2CSR/COO2CSR.cu
- cpp/src/snmg/utils.cuh
- cpp/src/tests/CMakeLists.txt
- cpp/src/tests/snmg_coo2csr/snmg_coo2csr_test.cu
- cpp/src/tests/snmg_test_utils.h
- cpp/src/tests/test_utils.h
> Snmg coo2csr

- CHANGELOG.md
- README.md
Updated the README with release information
closes #282
> [REVIEW] Added release 0.8 material

- CHANGELOG.md
- cpp/src/sort/sort.cuh
This PR defines sample SNMG sort functions.  Once approved I will fill in the details from the cusort repository.
> [REVIEW] Define the prototype of what the SNMG sort would look like

- CHANGELOG.md
- conda/recipes/cugraph/meta.yaml
- conda/recipes/libcugraph/meta.yaml
> [REVIEW] Bumping cudf version to 0.9

- CHANGELOG.md
- python/cugraph/graph/c_graph.pyx
- python/cugraph/graph/test_graph.py
> In out degree

- CHANGELOG.md
- python/cugraph/__init__.py
- python/cugraph/utilities/__init__.py
cugraph was unable to import device_of_gpu_pointer close #377
> cugraph was unable to import device_of_gpu_pointer close #377

- CHANGELOG.md
- python/cugraph/snmg/link_analysis/mg_pagerank.py
- python/cugraph/snmg/link_analysis/mg_pagerank_wrapper.pyx
This is the cugraph part of https://github.com/rapidsai/dask-cugraph/pull/32
Also close #379
> Exposed MG pagerank solver parameters

- CHANGELOG.md
- cpp/src/sort/sort_impl.cuh
> [REVIEW] run omp_get_num_threads in a parallel context

- CHANGELOG.md
- CONTRIBUTING.md
> [REVIEW] update python build instructions

- CHANGELOG.md
- python/cugraph/dask/pagerank/__init__.py
- python/cugraph/dask/pagerank/pagerank.py
- python/cugraph/tests/dask/test_hibench_small.py
- python/cugraph/tests/dask/test_karate_csv.py
- python/cugraph/utilities/column_utils.pyx
> [REVIEW] snmg drop duplicates, add conditional read_csv wait in pagerank.py

- CHANGELOG.md
- conda/environments/cugraph_dev_cuda10.yml
- conda/environments/cugraph_dev_cuda92.yml
- python/cugraph/community/c_louvain.pxd
- python/cugraph/community/c_spectral_clustering.pxd
- python/cugraph/community/c_subgraph_extraction.pxd
- python/cugraph/community/c_triangle_count.pxd
- python/cugraph/components/c_connectivity.pxd
- python/cugraph/link_analysis/c_pagerank.pxd
- python/cugraph/link_prediction/c_jaccard.pxd
- python/cugraph/link_prediction/c_overlap.pxd
- python/cugraph/snmg/link_analysis/c_mg_pagerank.pxd
- python/cugraph/structure/c_graph.pxd
- python/cugraph/traversal/c_bfs.pxd
- python/cugraph/traversal/c_sssp.pxd
- python/cugraph/utilities/c_grmat.pxd
> [Review] Add except + to cython C bindings and update Conda environment.

- CHANGELOG.md
- cpp/src/snmg/blas/spmv.cu
- cpp/src/snmg/link_analysis/pagerank.cu
- datasets/README.md
> [WIP] add device sync

- CHANGELOG.md
- python/cugraph/link_prediction/jaccard_wrapper.pyx
- python/cugraph/link_prediction/overlap_wrapper.pyx
- python/cugraph/link_prediction/wjaccard_wrapper.pyx
- python/cugraph/link_prediction/woverlap_wrapper.pyx
- python/cugraph/structure/c_graph.pxd
- python/cugraph/structure/graph_wrapper.pyx
- python/cugraph/tests/test_balanced_cut.py
- python/cugraph/tests/test_bfs.py
- python/cugraph/tests/test_connectivity.py
- python/cugraph/tests/test_graph.py
- python/cugraph/tests/test_jaccard.py
- python/cugraph/tests/test_louvain.py
- python/cugraph/tests/test_modularity.py
- python/cugraph/tests/test_overlap.py
- python/cugraph/tests/test_pagerank.py
- python/cugraph/tests/test_sssp.py
- python/cugraph/tests/test_subgraph_extraction.py
- python/cugraph/tests/test_triangle_count.py
- python/cugraph/tests/test_wjaccard.py
- python/cugraph/tests/utils.py
- python/cugraph/traversal/sssp_wrapper.pyx
- python/cugraph/utilities/column_utils.pyx
> [REVIEW] Import cudf_cpp.pxd and remove redundant definitions

- CHANGELOG.md
- python/cugraph/structure/graph.py
- python/cugraph/structure/graph_wrapper.pyx
- python/cugraph/tests/test_graph.py
- python/cugraph/tests/test_subgraph_extraction.py
> [Review] Updates python graph view methods to return edge weights in addition

- cpp/src/nvgraph/triangles_counting.cpp
> Fixed FatalError typo in trianges_counting.cpp

- CHANGELOG.md
- conda/environments/cugraph_dev_cuda10.yml
- conda/environments/cugraph_dev_cuda92.yml
- python/cugraph/community/louvain_wrapper.pyx
- python/cugraph/community/spectral_clustering_wrapper.pyx
- python/cugraph/community/subgraph_extraction_wrapper.pyx
- python/cugraph/community/triangle_count_wrapper.pyx
- python/cugraph/components/c_connectivity.pxd
- python/cugraph/components/connectivity_wrapper.pyx
- python/cugraph/link_analysis/pagerank_wrapper.pyx
- python/cugraph/link_prediction/jaccard.py
- python/cugraph/link_prediction/jaccard_wrapper.pyx
- python/cugraph/link_prediction/overlap.py
- python/cugraph/link_prediction/overlap_wrapper.pyx
- python/cugraph/link_prediction/wjaccard.py
- python/cugraph/link_prediction/wjaccard_wrapper.pyx
- python/cugraph/link_prediction/woverlap.py
- python/cugraph/link_prediction/woverlap_wrapper.pyx
- python/cugraph/structure/c_graph.pxd
- python/cugraph/structure/graph_wrapper.pyx
- python/cugraph/tests/test_graph.py
- python/cugraph/traversal/bfs_wrapper.pyx
- python/cugraph/traversal/sssp_wrapper.pyx
- python/cugraph/utilities/column_utils.pyx
- python/cugraph/utilities/grmat_wrapper.pyx
https://github.com/rapidsai/cudf/pull/2648 puts cugraph out-of-sync with cudf. This PR fixes this.
Close #472
> [REVIEW][BUG] re-sync with cudf

- .gitmodules
- CHANGELOG.md
- python/cugraph/tests/dask/test_hibench_small.py
- python/cugraph/tests/dask/test_karate_csv.py
> [REVIEW] Add cuHornet as a submodule

- CHANGELOG.md
- python/cugraph/components/connectivity_wrapper.pyx
- python/cugraph/tests/test_sssp.py
- python/cugraph/traversal/sssp_wrapper.pyx
> [WIP] call bfs on weighted graphs when sssp is called

- CHANGELOG.md
- cpp/src/snmg/COO2CSR/COO2CSR.cu
- python/cugraph/tests/test_woverlap.py
> [WIP] add weighted overlap test

- CHANGELOG.md
- python/utils/asv_report.py
- python/utils/benchmark.py
- python/utils/run_benchmarks.py
- python/utils/utils.py
Adding initial benchamark updates needed for nightly ASV E2E runs. This is still somewhat of a WIP and may get updated soon and frequently as our benchmarking tools evolve.
> Added updated benchmark files that use new func wrapper pattern and asvdb

- CHANGELOG.md
- cpp/src/tests/db/find_matches_test.cu
> [REVIEW] Temporarily disabling 2 DB tests

- CHANGELOG.md
- conda/environments/cugraph_dev_cuda10.yml
- conda/environments/cugraph_dev_cuda101.yml
- conda/environments/cugraph_dev_cuda92.yml
> [REVIEW] dev env update

- ci/gpu/build.sh
Simply adds downloading the test datasets and looping over the gtests and running each one.
I've adapted this from @rlratzel's container test script.
> [REVIEW] Run all tests in gpu test script

- CHANGELOG.md
- datasets/get_test_data.sh
- python/cugraph/tests/test_balanced_cut.py
- python/cugraph/tests/test_bfs.py
- python/cugraph/tests/test_connectivity.py
- python/cugraph/tests/test_core_number.py
- python/cugraph/tests/test_filter_unreachable.py
- python/cugraph/tests/test_graph.py
- python/cugraph/tests/test_grmat.py
- python/cugraph/tests/test_jaccard.py
- python/cugraph/tests/test_k_core.py
- python/cugraph/tests/test_katz_centrality.py
- python/cugraph/tests/test_louvain.py
- python/cugraph/tests/test_modularity.py
- python/cugraph/tests/test_overlap.py
- python/cugraph/tests/test_pagerank.py
- python/cugraph/tests/test_sssp.py
- python/cugraph/tests/test_subgraph_extraction.py
- python/cugraph/tests/test_symmetrize.py
- python/cugraph/tests/test_triangle_count.py
- python/cugraph/tests/test_wjaccard.py
- python/cugraph/tests/test_woverlap.py
Updates to use the new RMM Python reinitialize() API.
> Updates to use the new RMM Python reinitialize() API.

- .gitignore
- CHANGELOG.md
- python/cugraph/__init__.py
- python/cugraph/pregel/__init__.py
- python/cugraph/pregel/traversal/__init__.py
- python/cugraph/pregel/traversal/bfs_bsp.py
- python/cugraph/tests/test_bfs_pregel.py
> [REVIEW] Pregel-based BFS

- CHANGELOG.md
- cpp/src/converters/nvgraph.cu
- python/cugraph/tests/test_sssp.py
> [REVIEW] sssp test for type conversion, remove adj list from createGraph_nvgraph

- CHANGELOG.md
- TRANSITIONGUIDE.md
- python/cugraph/__init__.py
- python/cugraph/structure/__init__.py
- python/cugraph/structure/graph.py
- python/cugraph/tests/test_graph.py
This PR enables user to create (Di)Graph from Multi(Di)Graph with an option of providing any one column of the multigraph as the edge_attr.
Closes #589
> [REVIEW] multigraph_changes

- CHANGELOG.md
- cpp/src/structure/cugraph.cu
- python/cugraph/centrality/katz_centrality_wrapper.pyx
- python/cugraph/link_analysis/pagerank_wrapper.pyx
- python/cugraph/structure/graph.py
-> Fix cudf error for scattering function call in katz wrapper
-> Fix personalization bug due to premature garbage collection
-> Fix bug in transposed_adj_list_view
-> Edit pagerank to renumber nstart
> [REVIEW] fix cudf_error in Katz wrapper

- CHANGELOG.md
- cpp/include/algorithms.h
- cpp/src/traversal/bfs.cu
- python/cugraph/tests/test_sssp.py
- python/cugraph/traversal/bfs.pxd
- python/cugraph/traversal/bfs_wrapper.pyx
- python/cugraph/traversal/sssp_wrapper.pyx
Closes #643 
Using the same approach as #629 
Extra : 
- Re-enabled BFS forwarding when the graph is unweighted in SSSP
> [REVIEW] Remove gdf_column in BFS

- ci/release/update-version.sh
Adjust for capitalization change
> [REVIEW] update-version.sh [skip-ci]

- CHANGELOG.md
- conda/environments/cugraph_dev_cuda10.yml
- conda/environments/cugraph_dev_cuda101.yml
- conda/environments/cugraph_dev_cuda92.yml
cuDF recently upgraded to Pandas 0.25 in https://github.com/rapidsai/cudf/pull/3486
> [REVIEW] Use cudf pandas version

- CHANGELOG.md
- python/cugraph/tests/test_balanced_cut.py
> [REVIEW] Balanced cut fix 

- CHANGELOG.md
- python/cugraph/bsp/traversal/bfs_bsp.py
- python/cugraph/proto/components/scc.py
- python/cugraph/proto/structure/bicliques.py
- python/cugraph/structure/symmetrize.py
- python/cugraph/tests/test_bfs_bsp.py
> [REVIEW] Deprecated cudf calls

- CHANGELOG.md
- conda/environments/cugraph_dev_cuda10.yml
- conda/environments/cugraph_dev_cuda101.yml
- conda/environments/cugraph_dev_cuda92.yml
Update versions from 0.12 => 0.13
Close #696
> [REVIEW] Update Conda Environment files to fetch RAPIDS 0.13 packages

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
> [REVIEW] Updated doc to remove CUDA 9.2

- CHANGELOG.md
- cpp/src/centrality/katz_centrality.cu
- cpp/src/community/ECG.cu
- cpp/src/community/nvgraph_gdf.cu
- cpp/src/components/connectivity.cu
- cpp/src/converters/nvgraph.cu
- cpp/src/converters/renumber.cu
- cpp/src/cores/core_number.cu
- cpp/src/link_prediction/jaccard.cu
- cpp/src/link_prediction/overlap.cu
- cpp/src/nvgraph/include/modularity.cuh
- cpp/src/structure/cugraph.cu
- cpp/src/traversal/sssp.cu
- cpp/src/traversal/two_hop_neighbors.cu
- cpp/src/utilities/error_utils.h
- python/cugraph/tests/dask/test_hibench_small.py
- python/cugraph/tests/dask/test_karate_csv.py
> [REVIEW] Updating error messages

- CHANGELOG.md
- notebooks/traversal/SSSP.ipynb
> [REVIEW] Fixed SSSP notebook typo error

- CHANGELOG.md
- python/cugraph/__init__.py
- python/cugraph/community/louvain.py
- python/cugraph/community/triangle_count.py
- python/cugraph/components/connectivity.py
- python/cugraph/components/connectivity_wrapper.pyx
- python/cugraph/link_prediction/jaccard.py
- python/cugraph/link_prediction/wjaccard.py
- python/cugraph/structure/__init__.py
- python/cugraph/structure/convert_matrix.py
- python/cugraph/tests/test_balanced_cut.py
- python/cugraph/tests/test_ecg.py
- python/cugraph/tests/test_graph.py
- python/cugraph/tests/test_jaccard.py
- python/cugraph/tests/test_renumber.py
- python/cugraph/tests/test_wjaccard.py
Closes #642 
Closes #318 
Disable Multi Graph
Add cugraph.from_cudf_edgelist for nx compatibility
> [REVIEW] throw exception for incorrect graph input

- CHANGELOG.md
- python/cugraph/__init__.py
- python/cugraph/tests/test_utils.py
- python/cugraph/utilities/utils.py
created a utility function for BFS / SSSP to return paths to specified vertices
closes #355
> [REVIEW] adding utility function for BFS / SSSP

- CHANGELOG.md
- python/cugraph/community/ecg_wrapper.pyx
Closes #744 
Data type was not being detected properly.  Changed the way that the data type was being checked and this makes the python wrapper call the proper C++ templated function.
> [REVIEW] [BUG] ECG error

- CHANGELOG.md
- python/utils/README-benchmark.md
> [gpuCI] Auto-merge branch-0.13 to branch-0.14 [skip ci]

- CHANGELOG.md
- ci/test.sh
- python/.coveragerc
Added options and config file to enable codecov.
There's also a gpuCI config update to fully enable codecov, which @mike-wendt has done
> [REVIEW] [ENH] Added options and config file to enable codecov

- CHANGELOG.md
- python/setup.py
I missed this in https://github.com/rapidsai/cugraph/pull/782 :man_facepalming:. Now `-j` really cythonizes in parallel.
> [REVIEW] Cythonize in parallel

- CHANGELOG.md
- python/cugraph/structure/graph.py
- python/cugraph/tests/test_graph.py
--> Added the following functionality to python Graph class:
1) to_directed
2) to_undirected
3) is_directed
4) has_node
5) has_edge
6) edges (same as view_edge_list(), only difference is it doesn't return weights)
7) nodes
--> Added tests
> [REVIEW] add graph functionality

- CHANGELOG.md
- CONTRIBUTING.md
> [REVIEW] fix outdated CONTRIBUTING.md

- CHANGELOG.md
- notebooks/community/Spectral-Clustering.ipynb
- notebooks/components/ConnectedComponents.ipynb
- notebooks/link_analysis/Pagerank.ipynb
- notebooks/link_prediction/Jaccard-Similarity.ipynb
- notebooks/link_prediction/Overlap-Similarity.ipynb
- python/cugraph/tests/test_graph.py
- python/cugraph/tests/test_jaccard.py
- python/cugraph/tests/test_katz_centrality.py
- python/cugraph/utilities/utils.py
Fix CI fails due to indexing changes in cudf
> [REVIEW] loc to iloc

- .gitignore
- CHANGELOG.md
- CONTRIBUTING.md
- PRTAGS.md
- README.md
- SOURCEBUILD.md
Redid README and CONTRIBUTION.  Added two new files: SOURCEBUILD and PRTAGS
Closes #808
> [REVIEW] Updated Markdown docs [skip-ci]

- CONTRIBUTING.md
- PRTAGS.md
- README.md
- SOURCEBUILD.md
> [REVIEW][skip-ci] more doc updates

- CHANGELOG.md
- python/cugraph/structure/graph.py
- python/cugraph/structure/graph_new_wrapper.pyx
- python/cugraph/structure/utils_wrapper.pyx
- python/cugraph/tests/test_graph.py
- python/cugraph/utilities/utils.py
--> Remove dependency on graph_wrapper and migrate graph functions to use new Graph class to eliminate gdf_column.
--> Add neighbors(n) graph function and test
> [REVIEW] update graph functions to use new Graph class

- CHANGELOG.md
- ci/local/build.sh
> [REVIEW] Update local gpuci build

- CHANGELOG.md
- python/cugraph/tests/test_balanced_cut.py
- python/cugraph/tests/test_betweenness_centrality.py
- python/cugraph/tests/test_bfs.py
- python/cugraph/tests/test_bfs_bsp.py
- python/cugraph/tests/test_connectivity.py
- python/cugraph/tests/test_core_number.py
- python/cugraph/tests/test_ecg.py
- python/cugraph/tests/test_filter_unreachable.py
- python/cugraph/tests/test_graph.py
- python/cugraph/tests/test_grmat.py
- python/cugraph/tests/test_jaccard.py
- python/cugraph/tests/test_k_core.py
- python/cugraph/tests/test_k_truss_subgraph.py
- python/cugraph/tests/test_katz_centrality.py
- python/cugraph/tests/test_louvain.py
- python/cugraph/tests/test_modularity.py
- python/cugraph/tests/test_overlap.py
- python/cugraph/tests/test_pagerank.py
- python/cugraph/tests/test_renumber.py
- python/cugraph/tests/test_sssp.py
- python/cugraph/tests/test_subgraph_extraction.py
- python/cugraph/tests/test_symmetrize.py
- python/cugraph/tests/test_triangle_count.py
- python/cugraph/tests/test_unrenumber.py
- python/cugraph/tests/test_wjaccard.py
- python/cugraph/tests/test_woverlap.py
- python/cugraph/utilities/utils.py
removed RMM from the tests
closes #849
> [REVIEW] Removed RMM from tests

- CHANGELOG.md
- notebooks/traversal/BFS.ipynb
this is a quick fix to the BFS notebook.  The notebook should be redone
> [REVIEW] Fix BFS Notebook

- CHANGELOG.md
- python/cugraph/__init__.py
Delete snmg reference from main init.py file
> [REVIEW] Missed a file in the original SNMG PR

- CHANGELOG.md
- ci/checks/style.sh
- python/.flake8
- python/cugraph/proto/components/scc.py
- python/setup.cfg
- python/setup.py
Updates to support the latest flake8 version.
> [ENH] Updates to support the latest flake8 version

- CHANGELOG.md
- build.sh
updated build script to include docs
> [REVIEW] updated build for docs

- CHANGELOG.md
- ci/gpu/build.sh
- conda/environments/cugraph_dev_cuda10.0.yml
- conda/environments/cugraph_dev_cuda10.1.yml
- conda/environments/cugraph_dev_cuda10.2.yml
- conda/recipes/cugraph/meta.yaml
- conda/recipes/libcugraph/meta.yaml
- python/setuputils.py
Small fixes for when https://github.com/rapidsai/raft/pull/7 merged
> [REVIEW] dask infra updates

- CHANGELOG.md
- notebooks/community/Louvain.ipynb
Closes #296 
Add some documentation to the Louvain notebook to describe why Parallel Louvain might be different from Serial Louvain.
> [REVIEW] Update Louvain notebook

- CHANGELOG.md
- python/cugraph/link_prediction/jaccard_wrapper.pyx
- python/cugraph/link_prediction/overlap_wrapper.pyx
- python/cugraph/structure/graph.py
- python/cugraph/traversal/bfs_wrapper.pyx
- python/cugraph/traversal/sssp_wrapper.pyx
- python/cugraph/utilities/unrenumber.py
Fixed renumber_map accesses that were causing regression
> [REVIEW] regression fix

- CHANGELOG.md
- cpp/src/layout/barnes_hut.hpp
Fix cuGraph build error (debug mode).
> [REVIEW] Build error fix (debug mode)

- CHANGELOG.md
- cpp/src/converters/COOtoCSR.cuh
> [REVIEW] Fix offset calculation in COO to CSR

- CHANGELOG.md
- cpp/src/layout/barnes_hut.hpp
- python/cugraph/internals/internals.pyx
- python/cugraph/tests/test_force_atlas2.py
* Updates `force_atlas2` BH approximation to call `callback->on_train_end()` after iterating
* Updates the test to verify each of the callback's methods are invoked the expected number of times
> [REVIEW] Update force_atlas2 to call on_train_end after iterating

- CHANGELOG.md
- ci/test.sh
- codecov.yml
Removing codecov until we figure out how to interpret failures that block CI.
> [ENH][REVIEW] Adding a codecov yml config to prevent blocking CI until we figure out how to interpret failures

- CHANGELOG.md
- ci/local/README.md
Closes: https://github.com/rapidsai/cugraph/issues/994
> [REVIEW] Update local CI README [skip-ci]

- CHANGELOG.md
- notebooks/demo/mg_pagerank.ipynb
In this notebook, we show how to use multiple GPUs in cuGraph to compute the PageRank of each user in Twitter's dataset.
Similar to the UVM notebook but on multi GPU
Close #1004 
Rendered here :  https://github.com/afender/cugraph/blob/mg_notebook/notebooks/demo/mg_pagerank.ipynb
> [REVIEW] MG notebook

- CHANGELOG.md
- benchmarks/bench_algos.py
- benchmarks/params.py
- benchmarks/pytest.ini
- ci/gpu/build.sh
- ci/test.sh
- python/cugraph/layout/force_atlas2.py
- python/cugraph/structure/graph.py
- python/cugraph/structure/number_map.py
* Fixed benchmarks for new renumbering API
* Updated docstrings for clarity and added minor comments, also changed var names in one case to match docstring.
* Added quick test-only benchmark run to CI so breakages won't go unnoticed.
closes #1035
> [BUG] Fixed benchmarks for new renumbering API, updated comments, added quick test-only benchmark run to CI

- CHANGELOG.md
> [REVIEW] Branch 0.16 merge 0.15 conflict fix

- CHANGELOG.md
- cpp/include/algorithms.hpp
- cpp/include/functions.hpp
- cpp/include/graph.hpp
- cpp/src/converters/renumber.cu
- cpp/src/cores/core_number.cu
- cpp/tests/renumber/renumber_test.cu
> [REVIEW] replace deprecated rmm::mr::get_default_resource with rmm::mr::get_current_device_resource

- CHANGELOG.md
- cpp/CMakeLists.txt
- cpp/cmake/thrust-ret-if-fail.patch
Copied from https://github.com/rapidsai/cudf/pull/6098
> [REVIEW] Patch Thrust to workaround CUDA_CUB_RET_IF_FAIL macro clearing CUDA errors

- CHANGELOG.md
- ci/checks/style.sh
> [REVIEW] Fix style checker

- CHANGELOG.md
- cpp/include/algorithms.hpp
- cpp/include/utilities/cython.hpp
- cpp/src/community/louvain.cu
- cpp/src/experimental/louvain.cuh
- cpp/src/utilities/cython.cpp
- python/cugraph/community/louvain.pxd
- python/cugraph/community/louvain_wrapper.pyx
- python/cugraph/dask/community/louvain.pxd
- python/cugraph/dask/community/louvain_wrapper.pyx
- python/cugraph/structure/graph_primtypes.pxd
- python/cugraph/tests/test_graph.py
- python/cugraph/tests/test_louvain.py
Update the Louvain API to support calling with either old or new graphs.
> [REVIEW] Louvain API update to use graph_container_t

- CHANGELOG.md
- ci/gpu/test-notebooks.sh
- docs/source/api.rst
- notebooks/cugraph_benchmarks/nx_cugraph_bc_benchmarking.ipynb
- python/cugraph/__init__.py
- python/cugraph/centrality/katz_centrality.py
- python/cugraph/community/subgraph_extraction.py
- python/cugraph/tests/test_bfs.py
- python/cugraph/tests/test_sssp.py
- python/cugraph/tests/test_subgraph_extraction.py
- python/cugraph/traversal/__init__.py
- python/cugraph/traversal/bfs.py
- python/cugraph/traversal/sssp.py
Adding BSF, SSSP, and Subgraph Extraction
Fixing some test issues
> [REVIEW] ENH added more Nx compatibility

- CHANGELOG.md
- conda/environments/cugraph_dev_cuda10.1.yml
- conda/environments/cugraph_dev_cuda10.2.yml
- conda/environments/cugraph_dev_cuda11.0.yml
Should help with cudf/libcudf and rmm/librmm versions mismatches locally in `cugraph_env`
> [REVIEW] BLD Added RAPIDS cpp packages to cugraph dev env

- CHANGELOG.md
- notebooks/cugraph_benchmarks/bfs_benchmark.ipynb
- notebooks/cugraph_benchmarks/louvain_benchmark.ipynb
- notebooks/cugraph_benchmarks/pagerank_benchmark.ipynb
- notebooks/cugraph_benchmarks/release.ipynb
- python/cugraph/structure/graph.py
Auto-merge triggered by push to `branch-0.16` that creates a PR to keep `branch-0.17` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Auto-merge branch-0.16 to branch-0.17 [skip ci]

- CHANGELOG.md
- cpp/CMakeLists.txt
- cpp/tests/centrality/katz_centrality_test.cu
- python/cugraph/tests/utils.py
Modified CMakeLists.txt to check for CUDA version and build appropriate gencodes, including those of aarch64 architectures
> [Review] Adding CUDA architecture code for sm80 and aarch64

- CHANGELOG.md
- ci/cpu/upload.sh
Uploads currently aren't working due to incorrect syntax. This should fix the issue.
> [REVIEW] FIX Fix upload script syntax [skip-ci]

- CHANGELOG.md
- cpp/src/traversal/bfs.cu
- python/cugraph/comms/comms.py
--> Disable bottom up approachfor bfs #960 
--> Close #1244
> [REVIEW] fix_github_issues

- CHANGELOG.md
- PRTAGS.md
- README.md
- docs/source/cugraph_ref.rst
Auto-merge triggered by push to `branch-0.17` that creates a PR to keep `branch-0.18` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Auto-merge branch-0.17 to branch-0.18 [skip ci]

- CHANGELOG.md
> Fix Branch 0.18 merge 0.17

- python/cugraph/structure/number_map.py
> [REVIEW] Fix mnmg cleanup exceptions

- cpp/src/centrality/betweenness_centrality.cu
- cpp/src/community/ECG.cu
- cpp/src/community/extract_subgraph_by_vertex.cu
- cpp/src/components/connectivity.cu
- cpp/src/cores/core_number.cu
- cpp/src/experimental/graph.cu
- cpp/src/experimental/graph_view.cu
- cpp/src/layout/force_atlas2.cu
- cpp/src/linear_assignment/hungarian.cu
- cpp/src/link_analysis/gunrock_hits.cpp
- cpp/src/link_analysis/pagerank.cu
- cpp/src/link_analysis/pagerank_1D.cu
- cpp/src/link_analysis/pagerank_1D.cuh
- cpp/src/link_prediction/jaccard.cu
- cpp/src/link_prediction/overlap.cu
- cpp/src/structure/graph.cu
- cpp/src/traversal/sssp.cu
- docs/source/api.rst
- docs/source/cugraph_intro.md
- python/cugraph/centrality/__init__.py
- python/cugraph/centrality/betweenness_centrality.py
- python/cugraph/community/spectral_clustering.py
Updating API docs and improving error checking 
closes #1231 
closes #1232 
closes #1117 
closes #1256
> [REVIEW] improving error checking and docs

- cpp/CMakeLists.txt
- python/cugraph/comms/comms.py
Function signature changes required by RAFT PR #120
> [REVIEW] API update to match RAFT PR #120

- CHANGELOG.md
- SOURCEBUILD.md
- python/cugraph/__init__.py
- python/cugraph/structure/__init__.py
- python/cugraph/structure/graph.py
- python/cugraph/structure/symmetrize.py
- python/cugraph/tests/test_multigraph.py
- python/cugraph/traversal/sssp.py
- python/cugraph/utilities/utils.py
Updated SOURCEBUILD.md to include the latest build.sh options.
> Updated SOURCEBUILD.md to include the latest build.sh options

- README.md
- SOURCEBUILD.md
- conda/environments/cugraph_dev_cuda10.1.yml
- conda/environments/cugraph_dev_cuda10.2.yml
- conda/environments/cugraph_dev_cuda11.0.yml
- docs/source/cugraph_blogs.rst
updated the conda environments to have cmake 3.18 and update the README file
> Update the conda environments and README file

- benchmarks/bench_algos.py
- cpp/src/community/louvain.cu
- cpp/src/community/louvain.cuh
- cpp/src/experimental/coarsen_graph.cu
- cpp/src/experimental/louvain.cuh
- cpp/src/experimental/relabel.cu
- cpp/tests/CMakeLists.txt
- cpp/tests/community/ecg_test.cpp
- cpp/tests/community/leiden_test.cpp
- cpp/tests/community/louvain_test.cpp
Auto-merge triggered by push to `branch-0.18` that creates a PR to keep `branch-0.19` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Auto-merge branch-0.18 to branch-0.19 [skip ci]

- conda/environments/cugraph_dev_cuda10.1.yml
- conda/environments/cugraph_dev_cuda10.2.yml
- conda/environments/cugraph_dev_cuda11.0.yml
- conda/recipes/cugraph/meta.yaml
- conda/recipes/libcugraph/meta.yaml
update the environment to use NCCL 2.8.4
> Updated NCCL to version 2.8.4

- cpp/include/experimental/graph_generator.hpp
- cpp/src/experimental/generate_rmat_edgelist.cu
- cpp/tests/experimental/generate_rmat_test.cpp
Forward-merge triggered by push to `branch-0.19` that creates a PR to keep `branch-0.20` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-0.19 to branch-0.20 [skip ci]

- conda/recipes/cugraph/meta.yaml
> Revert "Update conda recipes pinning of repo dependencies" [skip-ci]

- cpp/CMakeLists.txt
There was a PR merged into RAFT today, updating to the most recent commit hash : f0cd81fb49638eaddc9bf18998cc894f292bc293.
> Updating RAFT tag

- cpp/CMakeLists.txt
- cpp/include/patterns/copy_v_transform_reduce_key_aggregated_out_nbr.cuh
- cpp/include/utilities/collect_comm.cuh
- cpp/src/experimental/relabel.cu
- cpp/src/experimental/renumber_edgelist.cu
- cpp/src/experimental/renumber_utils.cu
- python/cugraph/centrality/katz_centrality.py
- python/cugraph/components/connectivity.py
- python/cugraph/dask/centrality/katz_centrality.py
Undo workarounds due to cuco::static_map bugs (Issues 71, 72, 73, 74, 75 in https://github.com/NVIDIA/cuCollections/issues) as those get fixed and update the cuCollection git tag to pull the version after the bug fixes.
> [ENH] Undo cuco::static_map bug workarounds

- README.md
- ci/benchmark/build.sh
- conda/recipes/cugraph/meta.yaml
- conda/recipes/libcugraph/meta.yaml
- conda_build.sh
Remove `defaults` channel from conda build
> ENH Remove defaults channel from conda build

- CHANGELOG.md
- cpp/CMakeLists.txt
- cpp/include/cugraph/algorithms.hpp
- cpp/include/cugraph/experimental/graph.hpp
- cpp/include/cugraph/patterns/update_frontier_v_push_if_out_nbr.cuh
- cpp/src/components/weakly_connected_components.cu
- cpp/src/experimental/graph.cu
- cpp/src/traversal/sssp.cu
- cpp/tests/CMakeLists.txt
- cpp/tests/components/mg_weakly_connected_components_test.cpp
- cpp/tests/components/weakly_connected_components_test.cpp
- cpp/tests/utilities/matrix_market_file_utilities.cu
- cpp/tests/utilities/rmat_utilities.cu
This PR fixes the merge conflicts in #1611.
> Fix merge conflicts [skip ci]

- CHANGELOG.md
- cpp/CMakeLists.txt
- cpp/include/cugraph/algorithms.hpp
- cpp/include/cugraph/experimental/graph.hpp
- cpp/include/cugraph/patterns/update_frontier_v_push_if_out_nbr.cuh
- cpp/src/components/weakly_connected_components.cu
- cpp/src/experimental/graph.cu
- cpp/src/traversal/sssp.cu
- cpp/tests/CMakeLists.txt
- cpp/tests/components/mg_weakly_connected_components_test.cpp
- cpp/tests/components/weakly_connected_components_test.cpp
- cpp/tests/utilities/matrix_market_file_utilities.cu
- cpp/tests/utilities/rmat_utilities.cu
Forward-merge triggered by push to `branch-21.06` that creates a PR to keep `branch-21.08` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-21.06 to branch-21.08 [skip ci]

- conda/environments/cugraph_dev_cuda11.0.yml
- conda/environments/cugraph_dev_cuda11.1.yml
- conda/environments/cugraph_dev_cuda11.2.yml
Updated dependencies for CalVer
Note: I have not tested this yet.
> Updated dependencies for CalVer

- notebooks/cugraph_benchmarks/random_walk_benchmark.ipynb
Made call to cugraph.random_walks() ignore the unused return value.
Manually tested in browser with jupyterlab.
> [BUG] Made call to cugraph.random_walks() ignore the unused return value

- ci/release/update-version.sh
> [RELEASE] cugraph v21.06 [skip-ci]

- python/cugraph/dask/traversal/bfs.py
- python/cugraph/dask/traversal/sssp.py
this PRs removes legacy hardcoded int32 types
> remove hardcoded dtype

- cpp/include/cugraph/experimental/graph_view.hpp
- cpp/include/cugraph/matrix_partition_view.hpp
- cpp/include/cugraph/prims/copy_v_transform_reduce_key_aggregated_out_nbr.cuh
- cpp/include/cugraph/prims/transform_reduce_by_adj_matrix_row_col_key_e.cuh
- cpp/src/experimental/coarsen_graph.cu
- cpp/src/experimental/graph.cu
- cpp/src/experimental/graph_view.cu
Forward-merge triggered by push to `branch-21.08` that creates a PR to keep `branch-21.10` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-21.08 to branch-21.10 [skip ci]

- conda/environments/cugraph_dev_cuda11.0.yml
- conda/environments/cugraph_dev_cuda11.2.yml
- conda/recipes/cugraph/meta.yaml
Changes to be in-line with: https://github.com/rapidsai/cudf/pull/8859
> Pin max version for `dask` & `distributed` 

- docs/cugraph/source/api.rst
- python/cugraph/generators/rmat.py
Fixed indentations so that docs appear correctly
> Docs for RMAT

- docs/cugraph/source/api.rst
- python/cugraph/generators/rmat.py
Forward-merge triggered by push to `branch-21.08` that creates a PR to keep `branch-21.10` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-21.08 to branch-21.10 [skip gpuci]

- cpp/src/traversal/tsp.cu
- cpp/src/traversal/tsp.hpp
- cpp/src/traversal/tsp_solver.hpp
- cpp/src/traversal/tsp_utils.hpp
- thirdparty/LICENSES/LICENSE.texas_state_university
Texas State Copyright was missing from TSP source code
Documentation only change
> [HOTFIX] Update TSP branch 21.08 with Texas State Copyright

- python/cugraph/cugraph/structure/hypergraph.py
cudf moved the is_string_dtype method to a different package
> Accommodate cudf change to is_string_dtype method

- cpp/src/utilities/cython.cu
- python/cugraph/cugraph/__init__.py
- python/cugraph/cugraph/link_prediction/__init__.py
- python/cugraph/cugraph/link_prediction/overlap.py
- python/cugraph/cugraph/link_prediction/sorensen.py
- python/cugraph/cugraph/link_prediction/wjaccard.py
- python/cugraph/cugraph/link_prediction/wsorensen.py
- python/cugraph/cugraph/tests/test_overlap.py
- python/cugraph/cugraph/tests/test_sorensen.py
- python/cugraph/cugraph/tests/test_woverlap.py
- python/cugraph/cugraph/tests/test_wsorensen.py
Forward-merge triggered by push to `branch-21.10` that creates a PR to keep `branch-21.12` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-21.10 to branch-21.12 [skip gpuci]

- python/cugraph/cugraph/tests/test_louvain.py
added a catch for the test importing an uncommon module
> add try/catch for python-louvain

- conda/environments/cugraph_dev_cuda11.0.yml
- conda/environments/cugraph_dev_cuda11.2.yml
- conda/environments/cugraph_dev_cuda11.4.yml
- conda/recipes/cugraph/meta.yaml
This PR resolves conflicts that are blocking the automerger for `branch-21.12`: https://github.com/rapidsai/cugraph/pull/1846
> Fix automerger for `branch-21.12`

- cpp/src/traversal/tsp.cu
- cpp/src/traversal/tsp.hpp
- cpp/src/traversal/tsp_solver.hpp
- cpp/src/traversal/tsp_utils.hpp
- thirdparty/LICENSES/LICENSE.texas_state_university
Added Texas State Copyright information
Documentation only
> [HOTFIX] Update TSP branch 21.06 with Texas State Copyright

- cpp/src/traversal/tsp.cu
- cpp/src/traversal/tsp.hpp
- cpp/src/traversal/tsp_solver.hpp
- cpp/src/traversal/tsp_utils.hpp
- thirdparty/LICENSES/LICENSE.texas_state_university
Added Texas State Copyright information
Documentation only
> [HOTFIX] Update TSP branch 0.20 with Texas State Copyright

- cpp/src/traversal/tsp.cu
- cpp/src/traversal/tsp.hpp
- cpp/src/traversal/tsp_solver.hpp
- cpp/src/traversal/tsp_utils.hpp
- thirdparty/LICENSES/LICENSE.texas_state_university
Added Texas State Copyright information
Documentation only
> [HOTFIX] Update TSP branch 0.19 with Texas State Copyright

- cpp/src/traversal/tsp.cu
- cpp/src/traversal/tsp.hpp
- cpp/src/traversal/tsp_solver.hpp
- cpp/src/traversal/tsp_utils.hpp
- thirdparty/LICENSES/LICENSE.texas_state_university
Added Texas State Copyright information
Documentation only
> [HOTFIX] Update TSP branch 0.18 with Texas State Copyright

- python/cugraph/cugraph/utilities/nx_factory.py
- python/cugraph/cugraph/utilities/utils.py
refactored how to convert from Nx to cuGraph to improve performance
> improved Nx conversion performance

- cpp/CMakeLists.txt
Required to merge https://github.com/rapidsai/raft/pull/370
> Update rapids-cmake to 21.12

- conda/environments/cugraph_dev_cuda11.0.yml
- conda/environments/cugraph_dev_cuda11.2.yml
- conda/environments/cugraph_dev_cuda11.4.yml
- conda/environments/cugraph_dev_cuda11.5.yml
- conda/recipes/cugraph/meta.yaml
Changes to be in-line with: rapidsai/cudf#9734
> [REVIEW] Pin max `dask` & `distributed` to `2021.11.2`

- ci/benchmark/build.sh
- ci/cpu/build.sh
- ci/gpu/build.sh
- ci/release/update-version.sh
- conda/recipes/cugraph/meta.yaml
- conda/recipes/pylibcugraph/meta.yaml
Update `ucx-py` version on release using `rvc`
> Update ucx-py version on release using rvc

- conda/recipes/cugraph/meta.yaml
- conda/recipes/pylibcugraph/meta.yaml
> Add missing imports tests

- conda/environments/cugraph_dev_cuda11.5.yml
Looks like this file was missed when we updated clang-format
> update cuda 11.5 configuration to use clang format 11.1.0

- CHANGELOG.md
Resolving merge conflicts in https://github.com/rapidsai/cugraph/pull/1995
> Branch 22.02 merge 21.12

- conda/environments/cugraph_dev_cuda11.0.yml
- conda/environments/cugraph_dev_cuda11.2.yml
- conda/environments/cugraph_dev_cuda11.4.yml
- conda/environments/cugraph_dev_cuda11.5.yml
- conda/recipes/cugraph/meta.yaml
Changed to be in-line with: https://github.com/rapidsai/cudf/pull/10108
> [REVIEW] Pin `dask` & `distributed`

- ci/cpu/prebuild.sh
Always upload libcugraph package
> Always upload libcugraph [skip-ci]

- ci/cpu/build.sh
Forward-merge triggered by push to `branch-22.02` that creates a PR to keep `branch-22.04` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-22.02 to branch-22.04 [skip gpuci]

- conda/recipes/cugraph/meta.yaml
Changed to be in-line with:https://github.com/rapidsai/cudf/pull/10182
> [REVIEW] Unpin max `dask` and `distributed` versions

- CHANGELOG.md
Resolving forward-merge conflicts found in https://github.com/rapidsai/cugraph/pull/2055
> [skip-CI] Branch 22.04 merge 22.02

- cpp/tests/prims/mg_update_frontier_v_push_if_out_nbr.cu
The test code has bugs and this PR fixes those.
> update_frontier_v_push_if_out_nbr C++ test bug fix

- cpp/CMakeLists.txt
- cpp/include/cugraph_c/algorithms.h
- cpp/src/c_api/hits.cpp
- cpp/tests/CMakeLists.txt
- cpp/tests/c_api/hits_test.c
Forward-merge triggered by push to `branch-22.04` that creates a PR to keep `branch-22.06` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-22.04 to branch-22.06 [skip gpuci]

- conda/environments/cugraph_dev_cuda11.0.yml
- conda/environments/cugraph_dev_cuda11.2.yml
- conda/environments/cugraph_dev_cuda11.4.yml
- conda/environments/cugraph_dev_cuda11.5.yml
- conda/recipes/cugraph/meta.yaml
Pin changes to be in-line with: https://github.com/rapidsai/cudf/pull/10481/
> [REVIEW] Pin `dask` and `distributed` versions

- .github/ops-bot.yaml
- conda/environments/cugraph_dev_cuda11.0.yml
- conda/environments/cugraph_dev_cuda11.2.yml
- conda/environments/cugraph_dev_cuda11.4.yml
- conda/environments/cugraph_dev_cuda11.5.yml
- conda/recipes/cugraph/meta.yaml
This PR fixes the merge conflicts in #2149.
> Fix merge conflicts [skip gpuci]

- conda/environments/cugraph_dev_cuda11.2.yml
- conda/environments/cugraph_dev_cuda11.4.yml
- conda/environments/cugraph_dev_cuda11.5.yml
- conda/recipes/cugraph/meta.yaml
Changes to be inline with: https://github.com/rapidsai/cudf/pull/10623
> [REVIEW] Unpin `dask` & `distributed` for devlopment 

- cpp/include/cugraph/prims/copy_v_transform_reduce_in_out_nbr.cuh
- cpp/include/cugraph/prims/copy_v_transform_reduce_key_aggregated_out_nbr.cuh
- cpp/include/cugraph/prims/update_frontier_v_push_if_out_nbr.cuh
Fix few typos in documentation.
> Fix typos in documentation

- python/cugraph/cugraph/gnn/graph_store.py
- python/cugraph/cugraph/utilities/utils.py
Forward-merge triggered by push to `branch-22.06` that creates a PR to keep `branch-22.08` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-22.06 to branch-22.08 [skip gpuci]

- ci/benchmark/build.sh
- ci/cpu/build.sh
- ci/gpu/build.sh
Using mamba should speed up CI
> Use mamba to build packages

- cpp/include/cugraph/prims/per_v_transform_reduce_dst_nbr_intersection_of_e_endpoints.cuh
- cpp/src/c_api/triangle_count.cpp
- cpp/tests/c_api/mg_triangle_count_test.c
- cpp/tests/c_api/triangle_count_test.c
Connect C API to new C++ implementation for triangle counting.
> Triangle counting C API implementation

- conda/environments/cugraph_dev_cuda11.2.yml
- conda/environments/cugraph_dev_cuda11.4.yml
- conda/environments/cugraph_dev_cuda11.5.yml
- conda/recipes/cugraph/meta.yaml
Pinnings to be inline with: https://github.com/rapidsai/cudf/pull/10965
> [REVIEW] Pin `dask` & `distributed` for release

- conda/recipes/cugraph/meta.yaml
Changes to be in line with: https://github.com/rapidsai/cudf/pull/11058
> [REVIEW] Unpin `dask` & `distributed` for development

- conda/environments/cugraph_dev_cuda11.2.yml
- conda/environments/cugraph_dev_cuda11.4.yml
- conda/environments/cugraph_dev_cuda11.5.yml
- conda/recipes/cugraph/meta.yaml
Pin max version of `cuda-python` to `11.7.0`
> Pin max version of `cuda-python` to `11.7.0`

- conda/environments/cugraph_dev_cuda11.2.yml
- conda/environments/cugraph_dev_cuda11.4.yml
- conda/environments/cugraph_dev_cuda11.5.yml
- conda/recipes/cugraph/meta.yaml
Pin max version of `cuda-python` to 11.7.0
> pin cuda-python max version to 11.7.0

- conda/recipes/libcugraph/meta.yaml
- python/cugraph/cugraph/dask/common/input_utils.py
- python/cugraph/cugraph/dask/common/mg_utils.py
- python/cugraph/cugraph/dask/comms/comms.py
> Branch 22.08 merge 22.06

- python/cugraph/cugraph/structure/property_graph.py
- python/cugraph/cugraph/tests/test_property_graph.py
Forward-merge triggered by push to `branch-22.08` that creates a PR to keep `branch-22.10` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-22.08 to branch-22.10 [skip gpuci]

- python/cugraph/cugraph/tests/test_bfs.py
- python/cugraph/cugraph/tests/test_connectivity.py
- python/cugraph/cugraph/tests/test_sssp.py
Updated imports to be compatible with latest version of cupy and also changed corresponding scipy imports for consistency.
> Updated imports to be compatible with latest version of cupy

- python/cugraph/cugraph/tests/mg/test_mg_property_graph.py
Updating these tests was missed in #2449
Also, MG tests are finally working for me :tada:
> Fix PropertyGraph MG tests

- python/cugraph/cugraph/dask/traversal/bfs.py
- python/cugraph/cugraph/tests/mg/test_mg_bfs.py
- python/cugraph/cugraph/tests/mg/test_mg_graph.py
This PR coerces the seeds and vertices type, raise a warning and updates the tests accordingly. 
closes #2515.
> Branch 22.10 fix mg bfs type mismatch

- cpp/CMakeLists.txt
- cpp/src/community/leiden_impl.cuh
- cpp/src/community/leiden_sg.cu
#2485 
API definition for Leiden C++ Implementation
> Leiden C++ API

- python/cugraph/cugraph/dask/cores/core_number.py
- python/cugraph/cugraph/dask/link_analysis/pagerank.py
- python/cugraph/cugraph/dask/sampling/uniform_neighbor_sample.py
- python/cugraph/cugraph/dask/traversal/bfs.py
This is a follow up PR to wait for all the inactive futures to be released
closes #2657
> Release all inactive futures

- docs/cugraph/source/api_docs/dask-cugraph.rst
> [DOC] Removed reference to hard limit of 2 billion vertices for dask cugraph

- docs/cugraph/source/basics/cugraph_blogs.rst
> updated list of conferences

- python/cugraph/cugraph/structure/number_map.py
- python/cugraph/cugraph/testing/utils.py
- python/cugraph/cugraph/tests/mg/test_mg_doctests.py
- python/cugraph/cugraph/tests/mg/test_mg_renumber.py
Forward-merge triggered by push to `branch-22.10` that creates a PR to keep `branch-22.12` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-22.10 to branch-22.12 [skip gpuci]

- notebooks/demo/mg_pagerank.ipynb
> fix Comms import

- python/cugraph/cugraph/gnn/__init__.py
- python/cugraph/cugraph/gnn/dgl_extensions/cugraph_store.py
This PR resolves part of https://github.com/rapidsai/cugraph/issues/2838 . 
This helps with code cleanup and organization as we now support both PyG and DGL .
> [REVIEW] Move 'graph_store.py' under dgl_extensions

- build.sh
- docs/cugraph/Makefile
removed docs from default cugraph build behavior
added additional generated directory to docs clean target
closes #2789 
closes #2812
> removed docs from cugraph build defaults and updated docs clean

- python/cugraph/cugraph/dask/structure/mg_property_graph.py
- python/cugraph/cugraph/structure/property_graph.py
- python/cugraph/cugraph/tests/test_property_graph.py
Forward-merge triggered by push to `branch-22.12` that creates a PR to keep `branch-23.02` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-22.12 to branch-23.02 [skip gpuci]

- cpp/src/c_api/similarity.cpp
- cpp/src/link_prediction/jaccard_impl.cuh
- cpp/src/link_prediction/overlap_impl.cuh
- cpp/src/link_prediction/similarity_impl.cuh
- cpp/src/link_prediction/sorensen_impl.cuh
- cpp/tests/c_api/mg_similarity_test.c
- cpp/tests/c_api/similarity_test.c
- cpp/tests/link_prediction/mg_similarity_test.cpp
- cpp/tests/link_prediction/similarity_test.cpp
Joseph discovered that the C API hadn't been implemented for the similarity algorithms (it was partially implemented and disabled).  This PR addresses that.
> Implement C API Similarity

- ci/cpu/build.sh
- ci/gpu/build.sh
Fix build script to install dask main
> Fix build script to install dask main

- conda/recipes/cugraph-dgl/meta.yaml
- python/cugraph-dgl/setup.py
This PR fixes https://github.com/rapidsai/cugraph/issues/2928
> [REVIEW] Update dgl dependency to dglcuda=11.6

- python/cugraph-dgl/README.MD
Update dgl-cuda conda installation instructions 
Closes: https://github.com/rapidsai/cugraph/issues/2969
> [skip gpuci] Update dgl-cuda conda installation instructions

- README.md
Resolves merge conflicts blocking https://github.com/rapidsai/cugraph/pull/2917
> Branch 22.12 merge 22.10

- .github/workflows/pr.yaml
- ci/test_notebooks.sh
- conda/environments/all_cuda-115_arch-x86_64.yaml
- dependencies.yaml
This PR is a continuation of #3076. It adds notebook testing to the PR workflow for GitHub Actions.
We'll continue to iterate as needed on this PR so that we can merge #3076 since that is holding up some other efforts.
> Add notebooks testing to GH Actions PR Workflow

- cpp/src/c_api/uniform_neighbor_sampling.cpp
- cpp/src/sampling/uniform_neighbor_sampling_impl.hpp
- python/cugraph-pyg/cugraph_pyg/tests/test_cugraph_sampler.py
- python/cugraph/cugraph/dask/common/mg_utils.py
- python/cugraph/cugraph/dask/sampling/uniform_neighbor_sample.py
- python/cugraph/cugraph/dask/structure/mg_property_graph.py
- python/cugraph/cugraph/sampling/uniform_neighbor_sample.py
- python/cugraph/cugraph/structure/graph_implementation/simpleDistributedGraph.py
- python/cugraph/cugraph/structure/graph_implementation/simpleGraph.py
- python/cugraph/cugraph/structure/number_map.py
- python/cugraph/cugraph/tests/conftest.py
- python/cugraph/cugraph/tests/mg/test_mg_doctests.py
- python/cugraph/cugraph/tests/mg/test_mg_uniform_neighbor_sample.py
- python/cugraph/cugraph/tests/test_doctests.py
- python/cugraph/cugraph/tests/test_graph.py
- python/cugraph/cugraph/tests/test_uniform_neighbor_sample.py
- python/pylibcugraph/pylibcugraph/CMakeLists.txt
- python/pylibcugraph/pylibcugraph/__init__.py
- python/pylibcugraph/pylibcugraph/_cugraph_c/algorithms.pxd
- python/pylibcugraph/pylibcugraph/_cugraph_c/random.pxd
- python/pylibcugraph/pylibcugraph/_cugraph_c/sampling_algorithms.pxd
- python/pylibcugraph/pylibcugraph/graphs.pyx
- python/pylibcugraph/pylibcugraph/internal_types/sampling_result.pyx
- python/pylibcugraph/pylibcugraph/random.pxd
- python/pylibcugraph/pylibcugraph/random.pyx
- python/pylibcugraph/pylibcugraph/testing/type_utils.pyx
- python/pylibcugraph/pylibcugraph/testing/utils.py
- python/pylibcugraph/pylibcugraph/tests/test_uniform_neighbor_sample.py
- python/pylibcugraph/pylibcugraph/uniform_neighbor_sample.pyx
Forward-merge triggered by push to `branch-23.02` that creates a PR to keep `branch-23.04` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> Forward-merge branch-23.02 to branch-23.04

- conda/recipes/cugraph-dgl/meta.yaml
Updates runtime dependency to latest DGL
> Updates dependency to latest DGL

- .github/workflows/pr.yaml
- .github/workflows/test.yaml
- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/recipes/cugraph-pyg/meta.yaml
- conda/recipes/cugraph-service/meta.yaml
- conda/recipes/cugraph/meta.yaml
- dependencies.yaml
- python/cugraph-service/server/setup.py
This PR resolves conflicts in auto-merger: https://github.com/rapidsai/cugraph/pull/3239
> [REVIEW] Resolve auto merger

- cpp/CMakeLists.txt
- cpp/include/cugraph/graph_generators.hpp
- cpp/include/cugraph_c/graph_generators.h
- cpp/src/c_api/graph_generators.cpp
- cpp/src/generators/generate_rmat_edgelist.cu
- cpp/tests/CMakeLists.txt
- cpp/tests/c_api/generate_rmat_test.c
- cpp/tests/c_api/mg_generate_rmat_test.c
- cpp/tests/cores/core_number_test.cpp
- cpp/tests/utilities/base_fixture.hpp
- cpp/tests/utilities/test_graphs.hpp
- python/pylibcugraph/pylibcugraph/_cugraph_c/graph_generators.pxd
Forward-merge triggered by push to `branch-23.04` that creates a PR to keep `branch-23.06` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> Forward-merge branch-23.04 to branch-23.06

- .github/workflows/build.yaml
> Fix one more path to cugraphops in build workflow

- cpp/src/sampling/detail/sampling_utils_impl.cuh
- cpp/tests/c_api/mg_test_utils.cpp
- cpp/tests/c_api/mg_uniform_neighbor_sample_test.c
Closes #3552 
If hop is specified, we'll organize the output by label and hop.
> include hop as part of the sort criteria for sampling results

- python/cugraph/cugraph/gnn/data_loading/bulk_sampler_io.py
Forward-merge triggered by push to `branch-23.06` that creates a PR to keep `branch-23.08` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> Forward-merge branch-23.06 to branch-23.08

- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/recipes/cugraph-pyg/conda_build_config.yaml
- conda/recipes/cugraph/conda_build_config.yaml
- conda/recipes/libcugraph/conda_build_config.yaml
- conda/recipes/pylibcugraph/conda_build_config.yaml
- cpp/CMakeLists.txt
- cpp/libcugraph_etl/CMakeLists.txt
- dependencies.yaml
- python/cugraph/CMakeLists.txt
- python/cugraph/pyproject.toml
- python/pylibcugraph/CMakeLists.txt
- python/pylibcugraph/pyproject.toml
Updates minimum required CMake version to 3.26.4
> Update to CMake 3.26.4

- docs/cugraph/source/conf.py
- docs/cugraph/source/sphinxext/github_link.py
resolves #3635 
AJ Schmidt came up with this fix. It does correct all the links in the cugraph projects.
> this fixes github links in cugraph, cugraph-dgl and cugraph-pyg

- build.sh
Forward-merge triggered by push to `branch-23.08` that creates a PR to keep `branch-23.10` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> Forward-merge branch-23.08 to branch-23.10

- ci/release/update-version.sh
Add a new file to `update-version.sh`. Tested locally
> Add file to update-version.sh

- notebooks/algorithms/link_prediction/similarity_combined.ipynb
Forward-merge triggered by push to `branch-23.10` that creates a PR to keep `branch-23.12` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> Forward-merge branch-23.10 to branch-23.12

- README.md
Closes #3915 
This PR fixes two broken links in our README.md file.
> Update Broken Links in README.md

- python/nx-cugraph/README.md
* Adds missing `connected_components` algo to table.
> `nx-cugraph` README update: adds missing `connected_components` algo to table

- python/nx-cugraph/_nx_cugraph/__init__.py
- python/nx-cugraph/nx_cugraph/algorithms/__init__.py
- python/nx-cugraph/nx_cugraph/algorithms/bipartite/__init__.py
- python/nx-cugraph/nx_cugraph/algorithms/bipartite/basic.py
- python/nx-cugraph/nx_cugraph/algorithms/cluster.py
- python/nx-cugraph/nx_cugraph/classes/digraph.py
- python/nx-cugraph/nx_cugraph/classes/graph.py
- python/nx-cugraph/nx_cugraph/tests/test_cluster.py
Forward-merge triggered by push to `branch-24.02` that creates a PR to keep `branch-24.04` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> Forward-merge branch-24.02 to branch-24.04

- cpp/src/community/detail/refine_impl.cuh
Use input rng_state rather than creating a one local to function
> Use input rng_state rather than creating a local one

- notebooks/README.md
Added instructions on how to run notebook locally or in a remote machine with minimal effort
> Update README for cugraph notebooks

- python/nx-cugraph/_nx_cugraph/__init__.py
- python/nx-cugraph/_nx_cugraph/core.py
Updating to match changes from https://github.com/networkx/networkx/pull/7219
> nx-cugraph: update `get_info` function keys to NetworkX 3.3

- docs/cugraph/source/installation/getting_cugraph.md
xref: https://github.com/rapidsai/cugraph/pull/4207#discussion_r1511881073
> Add Python 3.11 to Conda docs

- python/cugraph/cugraph/structure/graph_classes.py
- python/cugraph/cugraph/structure/hypergraph.py
- python/cugraph/cugraph/tests/utils/test_dataset.py
Avoiding `core` imports here as they tend to be "private"
> Use public pandas and cudf APIs where possible

- cpp/src/prims/transform_e.cuh
> transform_e bug fix in edge masking

- cpp/examples/README.md
- cpp/examples/build.sh
update example build script with targets and options/help
> update example build script with targets and options/help

- python/cugraph-equivariant/cugraph_equivariant/nn/tensor_product_conv.py
Forward-merge triggered by push to `branch-24.04` that creates a PR to keep `branch-24.06` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> Forward-merge branch-24.04 to branch-24.06

- python/nx-cugraph/_nx_cugraph/__init__.py
- python/nx-cugraph/nx_cugraph/algorithms/core.py
This case is tested by the networkx tests.
> Update `k_truss` to work with many connected components

- python/cugraph/cugraph/tests/centrality/test_betweenness_centrality.py
Fixes bug seen in MG tests due to incorrect call to `enable_batch`
> Fix MG Betweenness Centrality Test Bug

- cpp/src/prims/kv_store.cuh
Fix a bug in kv_store_t implementation
> Fix a bug in kv_store_t implementation

- cpp/src/prims/detail/sample_and_compute_local_nbr_indices.cuh
Closes #4554, user bug found building cugraph 24.10
> Fix build error with NO_CUGRAPH_OPS

- benchmarks/nx-cugraph/pytest-based/run-main-benchmarks.sh
> Fix `cit-patents` Dataset for `nx-cugraph` Benchmark

- build.sh
- ci/build_docs.sh
- cpp/CMakeLists.txt
- docs/cugraph/source/api_docs/index.rst
- docs/cugraph/source/conf.py
This PR adapts to breaking changes in rmm in https://github.com/rapidsai/rmm/pull/1722.
> Adapt to rmm logger changes

- CHANGELOG.md
- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/environments/all_cuda-125_arch-x86_64.yaml
- dependencies.yaml
- python/cugraph-service/server/pyproject.toml
- python/cugraph/cugraph/datasets/dataset.py
- python/cugraph/cugraph/testing/resultset.py
- python/cugraph/cugraph/tests/conftest.py
- python/cugraph/cugraph/tests/data_store/test_gnn_feat_storage_wholegraph.py
- python/cugraph/pyproject.toml
> Forward-merge branch-24.12 into branch-25.02

- .devcontainer/cuda11.8-pip/devcontainer.json
- .devcontainer/cuda12.8-conda/devcontainer.json
- .devcontainer/cuda12.8-pip/devcontainer.json
This corrects an error in the devcontainer names that might have been missed in #4907 or had some other conflict.
> Fix devcontainer names

- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/environments/all_cuda-128_arch-x86_64.yaml
- conda/recipes/cugraph/conda_build_config.yaml
- conda/recipes/libcugraph/conda_build_config.yaml
- conda/recipes/pylibcugraph/conda_build_config.yaml
- cpp/CMakeLists.txt
- cpp/examples/developers/graph_operations/CMakeLists.txt
- cpp/examples/developers/vertex_and_edge_partition/CMakeLists.txt
- cpp/examples/users/multi_gpu_application/CMakeLists.txt
- cpp/examples/users/single_gpu_application/CMakeLists.txt
- cpp/libcugraph_etl/CMakeLists.txt
- dependencies.yaml
- python/cugraph/CMakeLists.txt
- python/cugraph/pyproject.toml
- python/libcugraph/CMakeLists.txt
- python/libcugraph/pyproject.toml
- python/pylibcugraph/CMakeLists.txt
- python/pylibcugraph/pyproject.toml
Update CMake minimum required to 3.30.4 across all of RAPIDS
> Require CMake 3.30.4

- cpp/src/cores/core_number_impl.cuh
Reduce memory footprint of edge destination vertex property cache from sizeof(edge_t) per vertex to 1 bit per vertex.
> Reduce memory footprint of core number computation.

- python/cugraph/cugraph/gnn/data_loading/bulk_sampler.py
- python/cugraph/cugraph/gnn/dgl_extensions/__init__.py
> [HOTFIX] `v25.04.01`

- ci/test_python.sh
> Remove get_test_data before tests run.

- dependencies.yaml
- python/cugraph-service/client/pyproject.toml
- python/cugraph-service/server/pyproject.toml
- python/cugraph-service/tests/test_remote_graph.py
Removes unnecessary dependencies from cugraph-service.
This addresses the comment [here](https://github.com/rapidsai/cugraph/pull/5085#issuecomment-2895870022).
> Removes unnecessary dependencies from cugraph-service

- cpp/src/structure/graph_view_impl.cuh
Fix erroneous assertion (closes https://github.com/rapidsai/cugraph/issues/5138).
> Bug fix in assert()

- cpp/tests/c_api/legacy_mst_test.c
- python/cugraph/cugraph/dask/link_prediction/cosine.py
- python/cugraph/cugraph/dask/link_prediction/jaccard.py
- python/cugraph/cugraph/dask/link_prediction/overlap.py
- python/cugraph/cugraph/dask/link_prediction/sorensen.py
- python/cugraph/cugraph/link_prediction/cosine.py
- python/cugraph/cugraph/link_prediction/jaccard.py
- python/cugraph/cugraph/link_prediction/overlap.py
- python/cugraph/cugraph/link_prediction/sorensen.py
- python/cugraph/cugraph/tests/link_prediction/test_cosine.py
This PR adds tests for Cosine Similarity algorithm and update docstrings
> Add test for Cosine Similarity algorithm

- cpp/libcugraph_etl/include/hash/managed.cuh
Drops some old logic that special cases for pre-CUDA 10
> Drop old CUDA pre-10 logic

- python/cugraph/cugraph/datasets/dataset.py
Allows for the default behavior of the Dataset method `get_edgelist` to use cudf for a system with a CUDA-capable GPU and pandas for systems without for the CSV reader in order to support some use-cases (benchmarks) on CPU-only systems.
> Allows Dataset method `get_edgelist()` to be called on a CPU-only system

- conda/recipes/libcugraph/recipe.yaml
This PR updates rapids-logger to version 0.2.
> Update to rapids-logger 0.2
