src/cugraph.cu
src/tests/gdf_graph/gdf_graph.cu

These functions were using the size of the graph as the size of the offset array. 
Improved the tests for gdf_add_adj_list and gdf_add_transpose to catch this.

[REVIEW] Fixed addAdjList and addTransposed

---

CMakeLists.txt
include/cugraph.h
src/COOtoCSR.cuh
src/cugraph.cu
src/grmat.cu

Issue #22
Fixed `Cmakelist.txt` to find `error_utils.h`.
Removed `error_utils.h` from `cugraph.h` so that `error_utils.h` does not need to be installed

Fixed error_utils.h dependency

---

cmake/Modules/ConfigureGoogleTest.cmake
cmake/Templates/GoogleTest.CMakeLists.txt.cmake
src/tests/CMakeLists.txt
src/tests/grmat/grmat_test.cu

Couldn't build master due to ABI issues.  This PR adds back some cmake entries that had previously been removed to allow for the user to turn the CXX11 ABI changes on or off universally for everything built with cugraph.
Had to make a change to one of the unit tests which failed when built using the old ABI.

[REVIEW] [BUG] ABI fixes

---

cpp/CMakeLists.txt
cpp/cmake/Modules/ConfigureArrow.cmake
cpp/cmake/Modules/ConfigureGoogleTest.cmake

This PR removes code in the CMake files for supporting backward compatibility of the C++ ABI change.
At this point, all of the conda dependencies are built with the new ABI, there is no reason to maintain backward compatibility with version 0.6.
This PR will eliminate the need to explicitly compile with the new ABI, the default build will use the new ABI.

Make everything build with the new abi - remove backward compatibility

---

cpp/CMakeLists.txt
cpp/cmake/Modules/ConfigureGoogleTest.cmake

As we discussed in slack... I added back support for building with old ABI - but default is still new ABI.

Bug fix cmake abi - support old ABI

---

CHANGELOG.md
cpp/include/nvgraph_gdf.h
cpp/src/nvgraph_gdf.cu
cpp/src/utilities/error_utils.h
python/cugraph/cugraph.pyx
python/cugraph/graph/c_graph.pyx
python/cugraph/louvain/test_louvain.py
python/cugraph/nvgraph/c_nvgraph.pxd
python/cugraph/nvgraph/c_nvgraph.pyx
python/cugraph/spectral_clustering/spectral_clustering.pyx
python/cugraph/spectral_clustering/test_balanced_cut.py
python/cugraph/spectral_clustering/test_modularity.py

Added bindings for spectral clustering and clustering analyzing metrics. Added Graph.num_vertices() method to python Graph object to facilitate tests. Added tests for spectral clustering similar to those in Nvgraph (check modularity or edge cut scores versus a random assignment). Close #62

Spectral clustering

---

README.md

Addresses #87 
Added a section to the README about the C++ ABI.  Hopefully this will clarify how to build with the different ABI issues.

add instructions on building with the old ABI

---

ci/cpu/libcugraph/upload-anaconda.sh

Auto-merge triggered by push to `branch-0.6` that creates a PR to keep `branch-0.7` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Auto-merge branch-0.6 to branch-0.7 [skip ci]

---

CHANGELOG.md
cpp/cmake/Modules/ConfigureGoogleTest.cmake

This is possibly a symptom of a bigger issue which should be addressed in a later change.
closes #159

[BUG] Added additional link directory to support building on CentOS-7

---

CHANGELOG.md
cpp/src/tests/nvgraph_plugin/nvgraph_gdf_sssp.cpp
cpp/src/tests/pagerank/pagerank_test.cu
cpp/src/tests/test_utils.h

Simplified get_rapids_dataset_root_dir() to not accept a default root dir arg and instead use a default set on RAPIDS_DATASET_ROOT_DIR. This makes behavior more predictable when a user has not set the env var or the build var and the code has not passed a fallback default. This also eliminates confusion if get_rapids_dataset_root_dir() is called multiple times with different args, since only the arg from the first call will be honored (due to the static string).

[ENH] Simplified get_rapids_dataset_root_dir(), set a default value for the root dir

---

CHANGELOG.md
cpp/include/algorithms.h
cpp/src/cugraph.cu
python/cugraph/bfs/bfs_wrapper.pyx
python/cugraph/graph/c_graph.pyx
python/cugraph/jaccard/jaccard_wrapper.pyx
python/cugraph/jaccard/wjaccard_wrapper.pyx
python/cugraph/louvain/louvain_wrapper.pyx
python/cugraph/overlap/overlap_wrapper.pyx
python/cugraph/overlap/woverlap_wrapper.pyx
python/cugraph/pagerank/pagerank_wrapper.pyx
python/cugraph/spectral_clustering/spectral_clustering.pyx
python/cugraph/sssp/sssp_wrapper.pyx
python/cugraph/triangle_count/triangle_count_wrapper.pyx

[REVIEW] Bug ext create column

---

CHANGELOG.md
cpp/include/algorithms.h
cpp/include/functions.h
cpp/src/cugraph.cu
cpp/src/two_hop_neighbors.cu
python/cugraph/bfs/bfs_wrapper.pyx
python/cugraph/bfs/c_bfs.pxd
python/cugraph/graph/c_graph.pyx
python/cugraph/graph/test_graph.py
python/cugraph/jaccard/jaccard_wrapper.pyx
python/cugraph/jaccard/wjaccard_wrapper.pyx
python/cugraph/louvain/louvain_wrapper.pyx
python/cugraph/overlap/overlap_wrapper.pyx
python/cugraph/overlap/test_overlap.py
python/cugraph/overlap/woverlap_wrapper.pyx
python/cugraph/pagerank/pagerank_wrapper.pyx
python/cugraph/spectral_clustering/spectral_clustering.pyx
python/cugraph/spectral_clustering/test_balanced_cut.py
python/cugraph/spectral_clustering/test_modularity.py
python/cugraph/sssp/sssp_wrapper.pyx

[REVIEW] Bug ext two graphs

---

CHANGELOG.md
cpp/nvgraph/cpp/include/graph_concrete_visitors.hxx
cpp/nvgraph/cpp/tests/nvgraph_capi_tests_subgraph.cpp

Created a unit test that demonstrates the problem that @jwyles discovered in subgraph extraction.
Subgraph extraction takes a list of vertices, identifies the subset of edges that connect these vertices, renumbers the vertices and then generates a new CSR graph that only uses the provided vertices.  The problem James discovered occurs when vertex 0 (the first element in the extraction list) is not incident on any edges.
Fixed the implementation to address this.

[REVIEW] Fix nvgraph bug in subgraph extraction

---

CHANGELOG.md
cpp/include/functions.h
python/cugraph/graph/c_graph.pyx

Add python documentation for the renumber function.

[Review] Add some python documentation

---

CHANGELOG.md
conda/recipes/libcugraph/meta.yaml

Removed networkx conda dependency for both build and runtime since it is only needed for tests validating correctness against NetworkX, and not an actual build or runtime dependency.

Removed networkx conda dependency for both build and runtime

---

CHANGELOG.md
README.md
ci/cpu/libcugraph/upload-anaconda.sh
conda/environments/cugraph_dev.yml
conda/environments/cugraph_dev_cuda10.yml
conda/recipes/libcugraph/meta.yaml

Refs conda-forge/conda-forge.github.io#687
This is to bring our conda packages in line with the community effort above and remove our current use of labels.

[REVIEW] Add cudatoolkit dependency

---

CHANGELOG.md
ci/gpu/build.sh
conda/recipes/libcugraph/meta.yaml

Remove the conda dependency on nvgraph since it is already included in `libcugraph`.
Ref: https://github.com/rapidsai/cugraph/issues/266#issuecomment-488843365
Closes #266

[REVIEW] Remove nvgraph conda dependency

---

CHANGELOG.md
cpp/CMakeLists.txt

When running C++ tests (make test) within the build directory we see
`error while loading shared libraries: libNVCategory.so: cannot open shared object file: No such file or directory`
This may be related to OS/compiler changes (https://stackoverflow.com/questions/52018092/how-to-set-rpath-and-runpath-with-gcc-ld?rq=1)
Added set(CMAKE_SHARED_LINKER_FLAGS "-Wl,--disable-new-dtags") to enforce the old behavior to avoid this error.

[REVIEW] updated CMakeLists to apply RUNPATH to transitive dependencies

---

CHANGELOG.md
conda/recipes/libcugraph/meta.yaml
cpp/CMakeLists.txt

Updates to remove libboost_system as a runtime dependency on libcugraph.so, since only boost headers are needed at build-time.

Updates to remove libboost_system as a runtime dependency on libcugraph.so

---

CHANGELOG.md
python/setup.py

Adds a missing variable definition that causes setup.py to fail if conda isn't installed.

Add default definition for conda_lib_dir in setup.py

---

CHANGELOG.md
cpp/CMakeLists.txt
cpp/src/snmg/COO2CSR/COO2CSR.cu
cpp/src/snmg/link_analysis/pagerank.cu
cpp/src/utilities/graph_utils.cu
cpp/src/utilities/graph_utils.cuh

This fixes 
```ERROR: RMM runtime call  RMM_FREE( (col->valid), (stream) )invalid device pointer```
Initiated by dask-cugraph https://github.com/rapidsai/dask-cugraph/issues/23 after the first fix https://github.com/rapidsai/dask-cugraph/pull/24

[REVIEW] Added a function to initialize gdf columns in cugraph

---

CHANGELOG.md
ci/release/update-version.sh
conda/recipes/libcugraph/meta.yaml
cpp/CMakeLists.txt

Replaces #351 
Pulls in hotfix 0.8.1 changes and branch-0.8 changes
Missing changes to Python docs as they were already merged in a74c478ce2b599ae2171e49b94ed75bd7b5b47f5

[REVIEW] Fix PR 351

---

CHANGELOG.md
ci/gpu/build.sh

Removing `exit 0` in favor of an else statement which is more friendly when calling the script via the `source` command.

[REVIEW] Fix Skip Test Functionality

---

CHANGELOG.md
cpp/src/components/connectivity.cu
cpp/src/tests/components/scc_test.cu

Fixed the warnings for unused variables and updated the tester file's dealing of null ptr to file name.

Issue #352 Fixing warnings

---

CHANGELOG.md
conda/environments/cugraph_dev_cuda10.yml
conda/environments/cugraph_dev_cuda92.yml

cudf [bumped](https://github.com/rapidsai/cudf/pull/2573) its numba dependency to 0.45.1, which will cause problems with cugraph's numba dependency. @kkraus14 said it's probably best to remove this entirely and rely on cudf's numba install.

[REVIEW] Remove numba dependency so we use the one from cudf

---

CHANGELOG.md
python/cugraph/tests/test_balanced_cut.py
python/cugraph/tests/test_bfs.py
python/cugraph/tests/test_connectivity.py
python/cugraph/tests/test_filter_unreachable.py
python/cugraph/tests/test_graph.py
python/cugraph/tests/test_grmat.py
python/cugraph/tests/test_jaccard.py
python/cugraph/tests/test_louvain.py
python/cugraph/tests/test_modularity.py
python/cugraph/tests/test_overlap.py
python/cugraph/tests/test_pagerank.py
python/cugraph/tests/test_sssp.py
python/cugraph/tests/test_subgraph_extraction.py
python/cugraph/tests/test_triangle_count.py
python/cugraph/tests/test_wjaccard.py

Since RMM allocates half the available GPU memory by default, the pytests are forced to run sequentially. I'm opening this PR to discuss capping RMM's initial pool size in each test, so they can be run in parallel with `pytest-xdist`.
Here's the execution time pytest reports with and without `pytest-xdist`:
```shell
$ pytest .
== 460 passed, 1 warnings in 426.15 seconds ==
$ pytest -n auto .
== 460 passed, 2 warnings in 82.64 seconds ==
```
I'm not familiar enough with the tests to know whether the 2GB cap in this PR is too high or low. The tests also passed when I set it to 8, 128, and 512mb.

[REVIEW] Consider limiting tests' initial pool size

---

CHANGELOG.md
cpp/src/converters/renumber.cuh
cpp/src/tests/renumber/renumber_test.cu
python/cugraph/tests/test_graph.py

Hash function assumed unsigned integers in the computation.  Modulus of a
negative integer is negative - which caused an out of bounds index.
Added a unit test to include a negative index example.
To keep from overflowing, compute modulus, then add modulus and mod again
to force number to be in range of [0, mod).
closes #488

[REVIEW] [BUG] Handle negative vertex ids

---

datasets/get_test_data.sh

Auto-merge triggered by push to `branch-0.10` that creates a PR to keep `branch-0.11` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Auto-merge branch-0.10 to branch-0.11 [skip ci]

---

CHANGELOG.md
cpp/include/rmm_utils.h

Only call RMM free if the RMM session has been initialized.
This resolves almost all the cugraph notebook test failures (still an issue with `Renumbering-test`, may have to handle separately).
I'm not sure if this is the right approach as a client of RMM, hoping @kkraus14 has some thoughts.  Also unsure if this is the best place to add this check, hoping @afender and @seunghwak have feedback.

[BUG] Added RMM init check so RMM free APIs are not called if not initialized

---

CHANGELOG.md
python/cugraph/utilities/column_utils.pyx

Updates the type aliases from cudf following the merger of https://github.com/rapidsai/cudf/pull/3029

[REVIEW] Update cudf  type aliases to the new names

---

CHANGELOG.md
ci/gpu/build.sh
python/cugraph/tests/dask/test_hibench_small.py

Changed hardcoded `~/pagerank.csv` test output file to a generated tempfile to avoid permission problems for certain test environments that cannot write to ~ (such as the nightly unit test runs).
I'm not sure if users expect the resulting output file to remain (since the previous version never deleted it after the test ended), but that can be something done here as well if necessary.

[BUG] Changed hardcoded test output file to a generated tempfile file name

---

CHANGELOG.md
ci/cpu/prebuild.sh
conda/recipes/cugraph/meta.yaml
conda/recipes/libcugraph/meta.yaml

Removing BUILD_ABI references in CI as we will ALWAYS build with it on. Not removing the option from CMake in case users want to build from source with it OFF.

[REVIEW] Remove BUILD_ABI references in CI

---

CHANGELOG.md
python/cugraph/tests/test_bfs_bsp.py

Skipping all tests in `test_bfs_bsp.py` since SG BFS is not formally supported and they currently crash.
Also updated 0.11 release date in CHANGELOG.

[REVIEW] Skipping all tests in test_bfs_bsp.py since SG BFS is not formally supported

---

CHANGELOG.md
python/cugraph/link_prediction/wjaccard_wrapper.pyx
python/cugraph/link_prediction/woverlap_wrapper.pyx

Changes variable names of graph weights and weight_arr in the wrapper to avoid exception when graph has no edge weights i.e. is None

[REVIEW] change variable names in wjaccard and woverlap

---

CHANGELOG.md
python/cugraph/centrality/katz_centrality_wrapper.pyx
python/cugraph/community/subgraph_extraction_wrapper.pyx
python/cugraph/cores/k_core_wrapper.pyx
python/cugraph/link_analysis/pagerank_wrapper.pyx
python/cugraph/link_prediction/jaccard.py
python/cugraph/link_prediction/jaccard_wrapper.pyx
python/cugraph/link_prediction/overlap.py
python/cugraph/link_prediction/overlap_wrapper.pyx
python/cugraph/link_prediction/wjaccard.py
python/cugraph/link_prediction/wjaccard_wrapper.pyx
python/cugraph/link_prediction/woverlap.py
python/cugraph/link_prediction/woverlap_wrapper.pyx
python/cugraph/structure/graph.py
python/cugraph/tests/test_jaccard.py
python/cugraph/tests/test_overlap.py
python/cugraph/tests/test_woverlap.py
python/cugraph/traversal/bfs_wrapper.pyx
python/cugraph/traversal/sssp_wrapper.pyx

This PR takes user notations into consideration when vertices are passed as arguments for analytics. If the graph is renumbered, passed vertices are also auto-renumbered according to the renumbering map used for the graph.
Changed first and second cudf.Series (to provide vertex pairs for computation of coefficient) in jaccard, wjaccard, overlap and woverlap to  a cudf.DataFrame input since it is more intuitive.
closes #592

[REVIEW] renumber vertex ids

---

CHANGELOG.md
conda/recipes/cugraph/meta.yaml
conda/recipes/libcugraph/meta.yaml

As `cython` is only needed to build the Python bindings and does not contain any needed runtime libraries, drop it from the run requirements.

[REVIEW] Drop `cython` from run requirements

---

CHANGELOG.md
python/cugraph/centrality/katz_centrality_wrapper.pyx
python/cugraph/community/ecg_wrapper.pyx
python/cugraph/community/louvain_wrapper.pyx
python/cugraph/community/spectral_clustering_wrapper.pyx
python/cugraph/cores/core_number_wrapper.pyx
python/cugraph/link_analysis/pagerank_wrapper.pyx
python/cugraph/link_prediction/jaccard_wrapper.pyx
python/cugraph/link_prediction/overlap_wrapper.pyx
python/cugraph/link_prediction/wjaccard_wrapper.pyx
python/cugraph/link_prediction/woverlap_wrapper.pyx
python/cugraph/structure/graph.py
python/cugraph/tests/test_pagerank.py
python/cugraph/traversal/bfs_wrapper.pyx
python/cugraph/traversal/sssp_wrapper.pyx
python/cugraph/utilities/unrenumber.py

With Multi-column renumbering #636 , python bindings need to be updated for a renumber_map with multiple columns as a dataframe. The PR addresses the following:
--> Updates in python API (Graph and MultiGraph) to accept multiple source and destination columns and call auto renumbering
--> Updates all algorithms returning vertices to un-renumber to multiple columns as per users notation.
Closes #604 
Further followup is needed as described in #678

[REVIEW] multi column renumbering changes for python graph structure

---

CHANGELOG.md
ci/gpu/build.sh

gpuCI nodes are running out of space due to the datasets download for cuGraph. The files are not cleaned up after the testing and remain on disk. This creates a trap for Jenkins that will remove these files on exit.

[REVIEW] Cleanup datasets download after run

---

CHANGELOG.md
cpp/src/tests/centrality/katz_centrality_test.cu

Close #691 
A simple fix to check file open result after creating a ifstream and before using it.

[REVIEW] check for file open result after opening result files in katz_test

---

CHANGELOG.md
cpp/src/nvgraph/include/triangles_counting.hxx
cpp/src/nvgraph/triangles_counting.cpp

Partially address #476 
Based on
https://devblogs.nvidia.com/cuda-pro-tip-the-fast-way-to-query-device-properties/
cudaGetDeviceProperties can be much slower than cudaDeviceGetAttribute.
This PR replaces cudaGetDeviceProperties with cudaDeviceGetAttribute in triangle counting that results in over 100x speed up in device property query time in triangle counting (the overall speed up in triangle counting should be much smaller as device query time takes only a small percentage of triangle counting execution time).

[REVIEW] Call cudaDeviceGetAttribute instead of cudaGetDeviceProperties in triangle counting

---

CHANGELOG.md
cpp/CMakeLists.txt

Not sure why this started failing for me now, maybe I only recently deleted my cmake cache.
As a follow-up to https://github.com/rapidsai/cugraph/commit/854b0f8bcd2b563962e4cbc72f05253d1abde7f9#diff-6725b893dfc969abac4f4ee39a3a317fR138, this PR adds the `LIBCYPHERPARSER_INCLUDE` path to the list of `target_include_paths`.
For some reason this isn't being picked up from my conda env, and this change seems necessary if supplying this path as a cmake arg via `-DLIBCYPHERPARSER_INCLUDE=`.

[REVIEW] Add libcypher include path to target_include_directories

---

CHANGELOG.md
python/cugraph/structure/renumber.py

Fixed an issue that iroy30 found where the index of the returned series causes the order to changed.  Added a reset_index call to the function

[REVIEW] fix multi-colum renumbering 

---

CHANGELOG.md
python/utils/README-benchmark.md
python/utils/run_benchmarks.py
python/utils/run_benchmarks.sh

Added README for running benchmarks, added docstring to help describe how to add new benchmarks, moved ASV-specific code so non-ASV use cases do not require ASV deps.
Also added `run_benchmarks.sh` to automate a run using the standard set of benchmarks and datasets.

[ENH] [REVIEW] Added documentation for running and adding new benchmarks and shell script to automate

---

CHANGELOG.md
cpp/CMakeLists.txt

Added flag to not treat deprecation warnings as errors, for now.  This will likely be removed when the RMM API calls have been updated for 0.14.

[BUG] Added flag to not treat deprecation warnings as errors, for now

---

CHANGELOG.md
python/cugraph/components/connectivity_wrapper.pyx
python/cugraph/tests/test_connectivity.py

--> Added un-renumbering block to wcc and scc
--> Updated tests to compare vertices for the largest component. This is to ensure correct labeling and un-renumbering. (Previously the test was just comparing number and lengths of components)
closes #767

[REVIEW] Add un-renumbering to connected components and update tests

---

CHANGELOG.md
cpp/src/nvgraph/kmeans.cu
python/cugraph/community/spectral_clustering_wrapper.pyx
python/cugraph/tests/test_balanced_cut.py
python/cugraph/tests/test_modularity.py

Updated tests, added tests, and changed Cython code to ensure a `DiGraph` cannot be passed to `cugraph.spectralModularityMaximizationClustering()` or `cugraph.spectralBalancedCutClustering()`
The new code will result in the following traceback if a `DiGraph` is used for the above algos:
```
File "cugraph/community/spectral_clustering_wrapper.pyx", line 50, in cugraph.community.spectral_clustering_wrapper.spectralBalancedCutClustering
TypeError: DiGraph objects are not supported
```
I also added a FIXME to note a possible infinite loop situation encountered during benchmark development. The above type check for a `DiGraph` would have prevented this, but would have also masked it as well.
_sorry for the noise in the diff - my editor automatically removes trailing whitespace and there …

[REVIEW] [BUG] Raise TypeError if a DiGraph is used with spectral*Clustering()

---

CHANGELOG.md
python/cugraph/centrality/betweenness_centrality_wrapper.pyx
python/cugraph/centrality/katz_centrality_wrapper.pyx
python/cugraph/community/ecg_wrapper.pyx
python/cugraph/community/louvain_wrapper.pyx
python/cugraph/community/spectral_clustering_wrapper.pyx
python/cugraph/community/subgraph_extraction_wrapper.pyx
python/cugraph/community/triangle_count_wrapper.pyx
python/cugraph/components/connectivity_wrapper.pyx
python/cugraph/cores/core_number_wrapper.pyx
python/cugraph/cores/k_core_wrapper.pyx
python/cugraph/cores/ktruss_subgraph_wrapper.pyx
python/cugraph/link_analysis/pagerank_wrapper.pyx
python/cugraph/structure/graph.pxd
python/cugraph/structure/graph_wrapper.pyx
python/cugraph/structure/utils.pxd
python/cugraph/traversal/bfs_wrapper.pyx
python/cugraph/traversal/sssp_wrapper.pyx
python/cugraph/utilities/column_utils.pyx
python/cugraph/utilities/grmat_wrapper.pyx

This PR fixes `cudf` Cython imports/cimports following https://github.com/rapidsai/cudf/pull/4627. This PR should only be merged after https://github.com/rapidsai/cudf/pull/4627 has been merged.

[REVIEW] Fix legacy cudf imports/cimports

---

CHANGELOG.md
cpp/CMakeLists.txt

Fix compiler argument syntax in `CMakeLists.txt` that cause ccache to throw preprocessor errors.
Here's the difference in compile times using ccache (more in [this gist](https://gist.github.com/trxcllnt/498c215de31d99ca277322961f3887bd)):
libcugraph C++ | Cold cache  | Warm cache
---------------|-------------|-----------
real           | 4m40.711s   | 1m16.574s
user           | 31m5.862s   | 2m31.904s
sys            | 2m53.182s   | 0m34.434s
cugraph Cython | Cold cache | Warm cache
---------------|------------|-----------
real           | 0m37.699s  | 0m24.048s
user           | 3m28.400s  | 0m29.646s
sys            | 0m11.022s  | 0m2.382s

[REVIEW] Fix compiler argument syntax for ccache

---

CHANGELOG.md
python/setup.py

Copies over the changes made in this PR: https://github.com/rapidsai/ucx-py/pull/462
Using `new_build_ext` allows parallelizing the `cythonize()` call from the command line via `-j` like so:
```
python setup.py -j<num_cores>
```

[REVIEW] Use Cython's `new_build_ext` (if available)

---

CHANGELOG.md
docs/source/api.rst
python/cugraph/structure/convert_matrix.py
python/cugraph/structure/graph.py
python/cugraph/structure/renumber.py

Betweenness centrality was not added to the api.rst file.
Also cleaned up some warnings in the construction of python documentation.
There are still some warnings, related to the additional indentation we do for documenting when particular columns in a data frame have specific meaning.

[REVIEW] update some documentation

---

CHANGELOG.md
cpp/src/traversal/bfs.cu
python/cugraph/traversal/bfs.py

--> Remove "directed" param in bfs API
Bfs can be optimized when the graph is symmetric by setting directed=False. Since we now have Graph and DiGraph classes, "directed" can be removed from the API and internally set. For a Graph type, which stores symmetric edges, directed is set to False. For DiGraph, which doesn't go through symmetrization, directed is set to True.
Closes #316 
--> Fix bfs optimization path error
When directed is False, a bottomup approach is employed. We need to check nu (undiscovered nodes) as well to avoid the configuration error. Closes #801

[REVIEW] update bfs optimization path

---

CHANGELOG.md
cpp/CMakeLists.txt

Add `BUILD_BYPRODUCTS` entry to cugunrock project to fix `cmake -GNinja`, similar to the fix in https://github.com/rapidsai/cuml/pull/1984.

[REVIEW] Enable Ninja build

---

CHANGELOG.md
cpp/include/graph.hpp
cpp/src/centrality/katz_centrality.cu
python/cugraph/centrality/katz_centrality.py
python/cugraph/centrality/katz_centrality_wrapper.pyx
python/cugraph/structure/graph_new.pxd
python/cugraph/structure/graph_new.pyx
python/cugraph/tests/test_katz_centrality.py

Fixes #730 
- Katz will automatically calculate alpha parameter if it is not provided by the user
- The code will no longer inform the user if the value of alpha is greater than the minimum alpha for convergence
- The code will no longer inform the user if the centrality calculation does not converge

[REVIEW] Katz Centrality : Auto calculation of alpha parameter if set to none

---

CHANGELOG.md
python/setup.py

Closes #615 
Added a custom clean which recursively removes the following files/directories if present:
dist/
cugraph.egg-info
build/
dask-worker-space/
__pycache__/
cython generated cpp files

[REVIEW] Update setup.py for custom clean command

---

CHANGELOG.md
cpp/src/traversal/bfs.cu
cpp/src/traversal/bfs_kernels.cuh

The current version of BFS may skip vertices in the last iteration when running on directed graphs.
This fixes the behavior, and avoid a potential Kernel Configuration issue by ensuring that the kernel is started with a positive value.

[REVIEW] Fix BFS for directed graphs

---

CHANGELOG.md
cpp/tests/layout/force_atlas2_test.cu
python/cugraph/tests/test_force_atlas2.py

Test happen to break on trustworthiness assertion in pytest.
since the algorithm is not deterministic it is possible that the trustworthiness computed is not the same everytime. I adjusted the threshold values so that we are more flexible against randomness.

[REVIEW] Fix CI error on Force Atlas 2 test

---

CHANGELOG.md
cpp/src/link_analysis/pagerank.cu

Original PR here: https://github.com/rapidsai/cugraph/pull/919  but this is targeting `branch-0.14`

[BUG] Updated pagerank with @afender 's temp fix for double-free crash

---

CHANGELOG.md
python/cugraph/layout/force_atlas2_wrapper.pyx

Since Numba has added support for external memory managers (EMM) and cuDF configures Numba to use RMM on import, we can just use Numba directly here. This should eliminate the last usage of `device_array` in cuGraph :)
xref: https://github.com/rapidsai/rmm/issues/180

[REVIEW] Use Numba to allocate the array directly

---

CHANGELOG.md
python/cugraph/centrality/betweenness_centrality_wrapper.pyx
python/cugraph/community/ecg_wrapper.pyx
python/cugraph/community/louvain_wrapper.pyx
python/cugraph/community/spectral_clustering_wrapper.pyx
python/cugraph/community/triangle_count_wrapper.pyx
python/cugraph/components/connectivity_wrapper.pyx
python/cugraph/cores/core_number_wrapper.pyx
python/cugraph/link_analysis/pagerank_wrapper.pyx
python/cugraph/link_prediction/jaccard_wrapper.pyx
python/cugraph/link_prediction/overlap_wrapper.pyx
python/cugraph/structure/graph.py
python/cugraph/structure/graph_new.pyx
python/cugraph/structure/graph_new_wrapper.pyx
python/cugraph/tests/test_bfs.py
python/cugraph/traversal/bfs_wrapper.pyx
python/cugraph/traversal/sssp_wrapper.pyx

This PR updates the following:
--> Bfs test to test on unsymmetric directed input. 
--> Add a directed_edges flag to number_of_edges() so as to get directed edges in algorithm wrappers
--> avoid recalculation/storage of adjlist(transposedadjlist) if transposedadjlist(adjlist) is already present in case of Graph() input. When the user initializes a Graph(), the adj list is same as transposed adj list.

[REVIEW] Graph edges, test and storage updates

---

CHANGELOG.md
ci/gpu/build.sh

This just helps prevent bash from interpreting `>` and `*`.

[REVIEW] Quote conda installs to avoid bash interpretation [skip-ci]

---

CHANGELOG.md
ci/gpu/build.sh
conda/environments/cugraph_dev_cuda10.0.yml
conda/environments/cugraph_dev_cuda10.1.yml
conda/environments/cugraph_dev_cuda10.2.yml

[REVIEW] Branch 0.15 merge 0.14

---

CHANGELOG.md
cpp/CMakeLists.txt
cpp/include/algorithms.hpp
cpp/src/link_analysis/gunrock_hits.cpp
cpp/src/link_analysis/gunrock_hits.cu
python/cugraph/__init__.py
python/cugraph/link_analysis/hits.pxd
python/cugraph/link_analysis/hits.py
python/cugraph/link_analysis/hits_wrapper.pyx
python/cugraph/tests/test_hits.py

Integration of the gunrock HITS algorithm.
Note, gunrock currently assumes that input and output comes from host memory.  https://github.com/gunrock/gunrock/issues/759 is a request for gunrock to modify this.  In the meantime, this wrapper will pull the CSR from device memory to the host to call gunrock, and will take the host results and copy them into the device memory.

[REVIEW] add wrapper for gunrock HITS algorithm

---

CHANGELOG.md
ci/docs/build.sh

This section is being moved to the Jenkins job as its not important to developers and allows easier editing to these scripts for OPS.

[REVIEW] Move customization scripts to Jenkins [skip-ci]

---

CHANGELOG.md
cpp/CMakeLists.txt
python/setuputils.py

Fixes setting the RAFT_PATH env var for source builds.
Without this fix the path `-I../../../../ENV{RAFT_PATH}/cpp/include` is included in the C++ build args instead of the correct path.

[REVIEW] fix setting RAFT_DIR from the RAFT_PATH env var

---

CHANGELOG.md
benchmarks/README.md
datasets/README.md
datasets/get_test_data.sh

Updated `get_test_data.sh` to also (optionally) download and install datasets for benchmark runs, and updated the corresponding README.md to describe it.
Also did some minor refactoring on `get_test_data.sh` to make it easier to add new datasets like this in the future.

[REVIEW] [ENH] Updated get_test_data.sh to also (optionally) download and install datasets for benchmark runs

---

.gitignore
CHANGELOG.md
python/cugraph/community/subgraph_extraction_wrapper.pyx
python/cugraph/proto/structure/bicliques.py
python/cugraph/structure/graph.py
python/cugraph/structure/renumber.py
python/cugraph/tests/test_betweenness_centrality.py
python/cugraph/tests/test_bfs.py
python/cugraph/tests/test_core_number.py
python/cugraph/tests/test_edge_betweenness_centrality.py
python/cugraph/tests/test_graph.py
python/cugraph/tests/test_hits.py
python/cugraph/tests/test_katz_centrality.py

* Fixes places that are breaking from changes in cuDF's `DataFrame.rename()` method
* Ensures columns are named `src, dst` in `Graph.view_edge_list()` when graph was created via `renumber_from_cudf`. Presently they're named `0_x` and `0_y`, causing `Graph.edges()` to throw an error

[REVIEW] Fix error in Graph.edges(), update cuDF rename() calls

---

CHANGELOG.md
python/cugraph/traversal/bfs_wrapper.pyx
python/cugraph/traversal/sssp_wrapper.pyx
python/cugraph/utilities/unrenumber.py

Reported in slack, several PRs are failing to build in CI due to a cuDF change.  A function that used to work now behaves a little differently and causes a failure.
Changed the way that the unrenumber is done.

[REVIEW] Fix unrenumber of predecessor

---

CHANGELOG.md
conda/environments/cugraph_dev_cuda10.0.yml
conda/environments/cugraph_dev_cuda10.1.yml
conda/environments/cugraph_dev_cuda10.2.yml

- Adding clang tools to the conda environment so that developers can use it to run clang format

[REVIEW] Add clang and clang tools to the conda env

---

CHANGELOG.md
ci/cpu/prebuild.sh

Update conda upload versions for new supported CUDA/Python
Edited ci/cpu/prebuild.sh with CUDA 10.1 and python 3.7 as new defaults.

[REVIEW] Update prebuild.sh

---

CHANGELOG.md
python/setup.cfg

Update setup.cfg for pytests to find tests from only under the cugraph/tests dir

[REVIEW] update setup.cfg

---

CONTRIBUTING.md
README.md

This PR changes any 'master' references to 'main' in markdown files throughout the repo as part of the new 'master' to 'main' branch migration.

[skip ci] Update master references for main branch

---

CHANGELOG.md
notebooks/structure/Renumber.ipynb
python/cugraph/tests/test_bfs.py
python/cugraph/tests/test_graph.py
python/cugraph/tests/test_renumber.py

Update tests in correspondence to cudf PR rapidsai/cudf#5340

[REVIEW] fix_tests

---

CHANGELOG.md
ci/benchmark/build.sh

This PR adds the `requirements` field to the `benchmark-asv-metadata` flag of `pytest` in order to enable tooltips to appear on ASV graphs that contain dependency versions.

[REVIEW] Add tooltip requirements to benchmarks/build.sh [skip-ci]

---

CHANGELOG.md
ci/benchmark/build.sh

This PR fixes a typo for the benchmarks script.

Fix branch name variable for benchmarks script [skip-ci]

---

CHANGELOG.md
cpp/src/community/louvain_kernels.cu
cpp/src/layout/fa2_kernels.hpp
cpp/src/link_analysis/pagerank.cu
cpp/src/link_analysis/pagerank_1D.cu
cpp/src/link_analysis/pagerank_1D.cuh
cpp/src/link_prediction/jaccard.cu
cpp/src/link_prediction/overlap.cu
cpp/src/utilities/graph_utils.cuh
python/cugraph/dask/opg_pagerank/pagerank.py
python/cugraph/tests/dask/test_opg_pagerank.py

- Closes #999 
- Added tolerance in MG PR
- Removed error throwing when not reaching tolerance in both MG and SG. The solver now exits when the first one between max_iter and tolerance is reached.
- Fixed cuda launch bounds (so that we can accept this from the device properties/handle and not limit it with the old #define)
- The MG pagerank backend returns the number of iterations to the cpp API driver

[REVIEW] Add tolerance support to MG Pagerank and fix kernel launch

---

CHANGELOG.md
python/cugraph/structure/number_map.py
python/cugraph/tests/dask/test_mg_renumber.py
python/cugraph/tests/test_graph.py
python/setup.py

Fix bug found in testing MG pagerank.  Mixing cudf.DataFrame and dask_cudf.DataFrame wasn't working properly in NumberMap.
Also, cudf dropped support for tolist, which breaks one of our unit tests.  Changed to use the suggested method in the error message.

[REVIEW] Fix support for using a cudf.DataFrame with a MG graph

---

CHANGELOG.md
ci/benchmark/build.sh

This PR updates the benchmark CI scripts to use the new `ASV_LABEL` environment variable.

[skip-ci] [REVIEW] Update benchmark scripts to use ASV_LABEL var

---

CHANGELOG.md
python/cugraph/comms/comms.py
python/cugraph/dask/common/part_utils.py

--> fix repartitioning error due to index values stored as float for big datasets
--> fix warnings coming from dask cugraph
--> update to native coroutine (does not support python<3.5)

[REVIEW] force index dtype to int64

---

CHANGELOG.md
python/cugraph/community/spectral_clustering.py

Spectral clustering code in python is inherently written to rely upon the order of the vertices being preserved when we unrenumber.  This should be fixed, but in the meantime we can use the preserve_order flag to correct this.
Fixes #1032

[REVIEW] Fix spectral clustering renumbering issue

---

CHANGELOG.md
ci/benchmark/build.sh

Updates pytest to use an S3 bucket as the ASV results directory. The variable used here is defined inside the Jenkins build, I promise.
Depends on:

[WIP] Update ASV directory for benchmark run [skip-ci]

---

CHANGELOG.md
benchmarks/README.md
conda/environments/cugraph_dev_cuda10.1.yml
conda/environments/cugraph_dev_cuda10.2.yml
conda/environments/cugraph_dev_cuda11.0.yml

Updated benchmarks README to better describe how to get plugin, added rapids-pytest-benchmark plugin to conda dev environments.
Thanks to @aschaffer and @seunghwak for testing the conda environments.
closes #1086

[BUG] Updated benchmarks README to better describe how to get plugin, added rapids-pytest-benchmark plugin to conda dev environments

---

CHANGELOG.md
cpp/src/centrality/betweenness_centrality.cu
cpp/tests/centrality/betweenness_centrality_test.cu
cpp/tests/centrality/edge_betweenness_centrality_test.cu
python/cugraph/centrality/betweenness_centrality.py

* Removed unnecessary device-to-host copy which caused a performance regression
* Fixed some search-and-replace errors in comments
* Added more detail about `k` to the BC docstring
Verified performance regression was gone using the benchmarks:
```
> pytest -v bench_algos.py::bench_betweenness_centrality[ds=../datasets/csv/directed/cit-Patents.csv,mm=True,pa=True] --benchmark-autosave --benchmark-compare=0001
-------------------------------------------------------------------------------------------------------------------- benchmark: 2 tests ---------------------------------------------------------
Name (time in ms)                                                                                                Min                Max               Mean            StdDev            Outliers …
```

[BUG] Removed unnecessary device-to-host copy which caused a performance regression

---

CHANGELOG.md
build.sh
ci/cpu/cugraph/build_cugraph.sh
ci/cpu/cugraph/upload-anaconda.sh
ci/cpu/libcugraph/build_libcugraph.sh
ci/cpu/libcugraph/upload-anaconda.sh
ci/cpu/prebuild.sh
ci/gpu/build.sh
ci/test.sh

This PR outlines the changes necessary for the new build process (aka Project Flash) to work with cuGraph. This PR is necessary to begin shadow testing of the new build process.
The goal is to simultaneously support both the old and new build processes. CI is configured to activate the new process by setting `PROJECT_FLASH=1`. Additionally `BUILD_LIBCUGRAPH` and `BUILD_CUGRAPH` will be set to 1 as needed by CI in the new process.
CI will stage build artifacts for python and GPU builds in ci/artifacts/cugraph/cpu/ which the build scripts will then consume.

[REVIEW] New build process script changes

---

Dockerfile
ci/checks/changelog.sh
ci/cpu/cugraph/upload-anaconda.sh
ci/cpu/libcugraph/upload-anaconda.sh
conda_build.sh

This PR removes unecessary references to master or updates references to the new main branch in CI scripts and other OPS-owned files.

[REVIEW] Update CI scripts to remove references to master [skip ci] 

---

CHANGELOG.md
CONTRIBUTING.md
README.md
cpp/CMakeLists.txt

This PR removes unecessary references to master or updates references to the new main branch in CI scripts and other OPS-owned files.

[REVIEW] Update docs to remove references to master [skip ci]

---

CHANGELOG.md
cpp/CMakeLists.txt
cpp/cmake/thrust-ret-if-fail.patch

Auto-merge triggered by push to `branch-0.15` that creates a PR to keep `branch-0.16` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Auto-merge branch-0.15 to branch-0.16 [skip ci]

---

CHANGELOG.md
python/cugraph/__init__.py
python/cugraph/centrality/betweenness_centrality.py
python/cugraph/community/ktruss_subgraph.py
python/cugraph/community/subgraph_extraction.py
python/cugraph/community/triangle_count.py
python/cugraph/link_prediction/__init__.py
python/cugraph/link_prediction/jaccard.py
python/cugraph/structure/convert_matrix.py
python/cugraph/structure/graph.py

Updated docs to fix missing arguments
Added NetworkX like API

[REVIEW] doc and API fixes

---

CHANGELOG.md
cpp/CMakeLists.txt

Update RAFT version (to pull the updates removing deprecated RMM calls).
https://github.com/rapidsai/cuhornet/pull/44 needs to be merged first for this to pass CI.

[REVIEW] update RAFT git tag

---

CHANGELOG.md
cpp/include/utilities/cython.hpp
cpp/src/utilities/cython.cpp
python/cugraph/community/subgraph_extraction_wrapper.pyx
python/cugraph/dask/community/louvain_wrapper.pyx
python/cugraph/structure/graph_primtypes.pxd
python/cugraph/structure/hypergraph.py

Refactored the graph container to use `unique_ptr`s instead of raw pointers after conversation with @aschaffer , added additional legacy graph types to the factory function which will be needed for MG Pagerank.

[REVIEW] Graph container cleanup, added arg for instantiating legacy types and switch statements to factory function

---

CHANGELOG.md
cpp/CMakeLists.txt
cpp/src/traversal/mg/common_utils.cuh
cpp/src/utilities/spmv_1D.cu

RAFT allgatherv is updated to take size_t* instead of int_t[] for displs, cuGraph needs to updated accordingly.

[REVIEW] pass size_t* instead of int_t[] for raft allgatherv's input parameter displs

---

CHANGELOG.md
cpp/include/patterns/any_of_adj_matrix_row.cuh
cpp/include/patterns/copy_to_adj_matrix_col.cuh
cpp/include/patterns/copy_to_adj_matrix_row.cuh
cpp/include/patterns/copy_v_transform_reduce_nbr.cuh
cpp/include/patterns/count_if_e.cuh
cpp/include/patterns/transform_reduce_e.cuh
cpp/include/patterns/transform_reduce_v_with_adj_matrix_row.cuh
cpp/include/patterns/update_frontier_v_push_if_out_nbr.cuh

Some of the pattern accelerator calls have the misspelled calls in assert messages.

[REVIEW] BUG fix misspelling of function calls in asserts causing debug build to fail

---

CHANGELOG.md
ci/gpu/build.sh

Current functionality does not actually properly handle errors in testing the notebooks.
${WORKSPACE}/ci/gpu/test-notebooks.sh 2>&1 | tee nbtest.log
Will only error if the last command in the pipe errors.
set +e -Eo pipefail will allow us to detect errors earlier in the pipe and hold the EXITCODE till we need it.

[REVIEW] FIX Fix notebook error handling

---

CHANGELOG.md
cpp/CMakeLists.txt

In 0.16, we just include the necessary headers under the cugraph and cuml includes. 
In the 0.17 timeline, we can provide a means to install raft globally, but that will require shipping a new conda package and matching hashes.

[REVEIW] BLD Installing raft headers under cugraph

---

CHANGELOG.md
cpp/CMakeLists.txt

Auto-merge triggered by push to `branch-0.16` that creates a PR to keep `branch-0.17` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Auto-merge branch-0.16 to branch-0.17 [skip ci]

---

CHANGELOG.md
notebooks/cugraph_benchmarks/bfs_benchmark.ipynb
notebooks/cugraph_benchmarks/louvain_benchmark.ipynb
notebooks/cugraph_benchmarks/pagerank_benchmark.ipynb
notebooks/cugraph_benchmarks/release.ipynb
python/cugraph/structure/graph.py

Fixed benchmark notebooks
Fix docs in graph.py

[REVIEW] BUG fix benchmark notebooks for recent cudf changes

---

CHANGELOG.md
python/cugraph/layout/force_atlas2_wrapper.pyx

This PR removes deprecated method `DataFrame.from_gpu_matrix`
Fixes: https://github.com/rapidsai/cugraph/issues/1191

[REVIEW] BUG Remove deprecated call to from_gpu_matrix

---

CHANGELOG.md
ci/test.sh

Temporarily disabling all C++ tests for 0.16 due to intermittent failures from what appears to be an issue with Thrust (which does not appear to affect the Python API or notebooks). These will be re-enabled once this issue is resolved in 0.17.

[REVIEW] BUG Temporarily disabling C++ tests for 0.16

---

CHANGELOG.md
ci/test.sh
cpp/CMakeLists.txt
cpp/tests/traversal/sssp_test.cu

* Changes to call gunrock cmake using explicit -D options for each arch, similar to a prior version of the CMakeLists.txt, since the update to expand a variable into the arch options was being expanded as a single quoted value with spaces that wasn't recognized, resulting in gunrock being built for only compute 60 support. This caused C++ test crashes.
* Re-enabled C++ tests.
This was tested by building cugraph with this change and running the Pagerank C++ test 1000 times without failures/crashes.  Prior to this, the Pagerank C++ test (and others) would crash after 1-50 test run iterations.
The issue and corresponding fix was verified with a standalone reproducer, which can be seen here: https://github.com/rlratzel/cugraph_build_problem

[REVIEW] BUG Calling gunrock cmake using explicit -D options, re-enabling C++ tests

---

CHANGELOG.md
cpp/CMakeLists.txt

Updated cuco commit hash to latest as of 2020-10-30.  This fixes build breakages as reported here: https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci/job/cugraph/job/branches/job/cugraph-cpu-branch-build/5381/console
Update: removing the `GIT_SHALLOW` param is the actual fix (thanks to @ChuckHastings), since its use is only supported when a branch or tag are specified (not a hash): https://cmake.org/cmake/help/latest/module/ExternalProject.html
I'll keep the change to update the hash though since it's just a README change and might help future debugging efforts by being of a more recent date (fewer commits to bisect)

[REVIEW] BUG Updated cuco commit hash to latest as of 2020-10-30

---

CHANGELOG.md
cpp/CMakeLists.txt
cpp/src/link_analysis/gunrock_hits.cpp
python/cugraph/tests/test_hits.py

Closes #1154 
This PR makes the following changes to our gunrock integration:
1. Update the CMake files to point directly to the gunrock repository instead of cugunrock.  This makes it easier to integrate their changes.
1. Latest repo adds features to allow the HITS function to accept data already on device memory and to accept a tolerance parameter and to select which normalization function to use (networkx uses the L1 norm gunrock was using the L2 norm, now we can specify which one that gunrock should use
1. With the updated HITS we can now compare results to networkx, so updated the python test to compare results to networkx.

[REVIEW] Use latest Gunrock, update HITS implementation

---

cpp/CMakeLists.txt

This PR removes `GIT_SHALLOW` (which is not compatible with commit hashes) from the `cuco` fetch function to prevent build errors from occurring. This is similar to Rick's fix in #1250, but now needs to be backported to `0.16` since Ops needs to re-release `0.16` and this issue is causing build errors.
This fix was confirmed locally.
As outlined in the [CMake docs](https://cmake.org/cmake/help/v3.17/module/ExternalProject.html):
>If GIT_SHALLOW is enabled then GIT_TAG works only with branch names and tags. A commit hash is not allowed.

Remove GIT_SHALLOW from CMakeLists.txt [skip-ci-changelog]

---

conda/environments/cugraph_dev_cuda10.1.yml
conda/environments/cugraph_dev_cuda10.2.yml
conda/environments/cugraph_dev_cuda11.0.yml

Tried building `cugraph` from source today with `./build.sh`. I built my conda environment from `conda/environments/cugraph_dev_cuda11.0.yml`
I ran into docs build target failing because `doxygen` was not in the environment:
```
Scanning dependencies of target docs_cugraph
[100%] Generating CUGRAPH_DOXYGEN
/bin/sh: 1: doxygen: not found
CMakeFiles/docs_cugraph.dir/build.make:79: recipe for target 'CUGRAPH_DOXYGEN' failed
make[3]: *** [CUGRAPH_DOXYGEN] Error 127
CMakeFiles/Makefile2:217: recipe for target 'CMakeFiles/docs_cugraph.dir/all' failed
make[2]: *** [CMakeFiles/docs_cugraph.dir/all] Error 2
CMakeFiles/Makefile2:224: recipe for target 'CMakeFiles/docs_cugraph.dir/rule' failed
make[1]: *** [CMakeFiles/docs_cugraph.dir/rule] Error 2
Makefile:207: recipe for target 'docs_cugraph' …
```

[REVIEW][skip-ci-changelog] Include doxygen for new and clean conda environments

---

CHANGELOG.md
conda/environments/cugraph_dev_cuda10.1.yml
conda/environments/cugraph_dev_cuda10.2.yml
conda/environments/cugraph_dev_cuda11.0.yml
cpp/include/algorithms.hpp
cpp/src/layout/barnes_hut.hpp
cpp/src/layout/exact_fa2.hpp
cpp/src/layout/exact_repulsion.hpp
cpp/src/layout/fa2_kernels.hpp
cpp/src/layout/force_atlas2.cu
cpp/src/layout/utils.hpp
python/cugraph/layout/force_atlas2.pxd
python/cugraph/layout/force_atlas2.py
python/cugraph/layout/force_atlas2_wrapper.pyx

This PR updates the notebook for the blog post, the Python bindings and addresses the FIXMEs related to stream usage.

[REVIEW] ENH Update Force Atlas 2 notebook, wrapper and coding style

---

CHANGELOG.md
ci/test.sh

This forces the `ci/gpu/build.sh` script to install the local conda package artifact from the CUDA build. This is achieved by specifying the exact version and build string of the artifact.

[REVIEW] Force local install of conda artifact

---

CHANGELOG.md
python/cugraph/structure/graph.py

[REVIEW] add self loop check variable

---

CHANGELOG.md
PRTAGS.md
README.md
docs/source/cugraph_ref.rst

Update the README with new algorithms and multi-gpu status
Also cleaned up a few other stops

[REVIEW] Update README and some docs

---

CHANGELOG.md
docs/source/api.rst

Auto-merge triggered by push to `branch-0.17` that creates a PR to keep `branch-0.18` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Auto-merge branch-0.17 to branch-0.18 [skip ci]

---

CHANGELOG.md
python/cugraph/__init__.py
python/cugraph/structure/graph.py
python/cugraph/tests/test_graph.py
python/cugraph/tests/test_paths.py
python/cugraph/traversal/__init__.py
python/cugraph/traversal/sssp.py
python/cugraph/traversal/sssp_wrapper.pyx

Adds the ability to get the length/cost of path from source to destination(s). Closely follows [`networkx.shortest_path_length`](https://networkx.org/documentation/latest/reference/algorithms/generated/networkx.algorithms.shortest_paths.generic.shortest_path_length.html#networkx.algorithms.shortest_paths.generic.shortest_path_length). 
Similarities:
1) Takes an optional target vertex
2) If only source is provided, a `cudf` dataframe is returned with columns: `[vertex, distance]` (similar to `networkx` dictionary return)
3) If source and target are specified the exact length is returned or `sys.float_info.max` if the vertex is not reachable. 
Differences:
1) Requires that source be provided, as apposed to `networkx`
2) Nethod of graph traversal is not an option. 
Fixes:
1) Fixes #806 
2) …

[REVIEW] Add support for shortest_path_length and fix graph vertex checks

---

CHANGELOG.md
python/cugraph/centrality/betweenness_centrality_wrapper.pyx
python/cugraph/centrality/edge_betweenness_centrality_wrapper.pyx
python/cugraph/structure/graph_primtypes.pyx
python/cugraph/tests/test_betweenness_centrality.py
python/cugraph/tests/test_edge_betweenness_centrality.py
python/cugraph/tests/utils.py

This PR fixes the check for weights in betweenness_centrality and edge_betweenness_centrality wrappers.
Addresses issue https://github.com/rapidsai/cugraph/issues/1282.

[REVIEW] BUG Update weights check in bc and graph prims wrappers

---

ci/release/update-version.sh
conda/environments/cugraph_dev_cuda10.1.yml
conda/environments/cugraph_dev_cuda10.2.yml
conda/environments/cugraph_dev_cuda11.0.yml
python/cugraph/centrality/betweenness_centrality.py
python/cugraph/structure/graph_primtypes.pyx

Updated cuxfilter to 0.18 and removed datashader indirect dependency in cugraph conda dev environment files.

[REVIEW] Updated cuxfilter to 0.18, removed datashader indirect dependency in conda dev .yml files

---

python/cugraph/dask/common/mg_utils.py
python/cugraph/tests/dask/mg_context.py
python/cugraph/tests/dask/test_mg_batch_betweenness_centrality.py
python/cugraph/tests/dask/test_mg_batch_edge_betweenness_centrality.py
python/cugraph/tests/dask/test_mg_bfs.py
python/cugraph/tests/dask/test_mg_comms.py
python/cugraph/tests/dask/test_mg_degree.py
python/cugraph/tests/dask/test_mg_katz_centrality.py
python/cugraph/tests/dask/test_mg_louvain.py
python/cugraph/tests/dask/test_mg_pagerank.py
python/cugraph/tests/dask/test_mg_renumber.py
python/cugraph/tests/dask/test_mg_replication.py
python/cugraph/tests/dask/test_mg_sssp.py
python/cugraph/tests/dask/test_mg_utility.py
python/cugraph/tests/test_symmetrize.py
python/pytest.ini

This PR includes various updates to support nightly automated MG test runs, including:
* Adding a marker which nightly scripts use to run on all visible GPUs instead of a hardcoded number of GPUs, since the scripts rely on knowing the number of GPUs being used in the tests by setting the `CUDA_VISIBLE_DEVICES` env var.
* In the nightly scripts, the marker is used like so: `pytest -m "not preset_gpu_count" ...`
* Added a `client.wait_for_workers()` call to various setups to both match the approach taken by the `MGContext` class, and to ensure workers are running. This seemed to increase reliability in the test runs. 
* _side note: we should decide to use only the `MGContext` class or the `client_connection` pytest fixture in these tests, since they both aim to accomplish the same thing._

[REVIEW] Updates to support nightly MG test automation

---

ci/gpu/build.sh
cpp/src/community/louvain.cu
cpp/src/experimental/louvain.cuh
cpp/tests/CMakeLists.txt
cpp/tests/experimental/louvain_test.cu

`experimental::louvain` uses a `coco::static_map` which is not supported on Pascal and earlier GPUs.
The first attempt at implementing checks for Pascal attempted to exclusively use preprocessor directives to control building the executable and deciding whether to run it or not.  However, nvcc uses the preprocessor to create different files to be compiled for host, and each combination of devices being compiled.  Exclusively using preprocessor directives created a library that didn't have all of the host and device code necessary to run.
This PR adds a runtime check to raise an exception if running on Pascal, but it will still compile all of the necessary host and device code for other architectures.

Fix EXPERIMENTAL_LOUVAIN_TEST on Pascal

---

python/cugraph/dask/common/mg_utils.py
python/cugraph/tests/dask/test_mg_louvain.py
python/cugraph/utilities/utils.py
python/setup.py

MNMG Louvain uses a feature not supported on Pascal.  This PR updates the python unit tests so that it expects an exception to be raised if running on a Pascal GPU.

Fix MNMG Louvain tests on Pascal architecture

---

cpp/tests/experimental/bfs_test.cpp
cpp/tests/experimental/katz_centrality_test.cpp
cpp/tests/experimental/pagerank_test.cpp
cpp/tests/experimental/sssp_test.cpp

- Add const to input pointers.
- Use a double type counter in std::accumulate as std::accumulate is inaccurate in adding a large number of a comparably sized values.
- Fix random number generator seed.
- Re-enable a temporarily disabled test case.
- Relax the thresholds to skip comparison for lowly ranked vertices (with low scores which are more susceptible to the limited floating-point resolution)

Update SG PageRank C++ tests

---

ci/checks/style.sh
ci/utils/git_helpers.py

Updated git utils used by copyright.py for compatibility with current CI env, added debug prints.
<s>NOTE: I'm intentionally not updating the copyright date on the changed file to test that the check is working in the actual CI environment here.  Once verified, I'll change it from a draft PR and mark it ready for review.</s> _verified_

Updated git utils used by copyright.py for compatibility with current CI env

---

CHANGELOG.md
python/cugraph/dask/common/input_utils.py
python/cugraph/structure/graph.py
python/cugraph/structure/number_map.py
python/cugraph/tests/dask/test_mg_renumber.py
python/cugraph/tests/dask/test_mg_utility.py
python/cugraph/tests/test_renumber.py

[REVIEW] Fix graph nodes function and renumbering from series

---

CHANGELOG.md
ci/benchmark/build.sh

Benchmark builds were failing after recent CI updates with the following error:
```
ci/benchmark/build.sh: line 25: gpuci_logger: command not found
```
This fix moves the `PATH` variable update above the trap setup, which should provide access to our conda installed gpuCI tools, including `gpuci_logger`.

[REVIEW] FIX Set bash trap after PATH is updated [skip-ci]

---

cpp/CMakeLists.txt

Set a specific known working commit hash for gunrock instead of "dev", since current gunrock dev is causing cugraph build failures.
NOTE: the commit is a known working commit, no newer than Jan. 04 2021. This should be updated with a more recent stable commit later, if possible.

Set a specific known working commit hash for gunrock instead of "dev"

---

notebooks/link_analysis/Pagerank.ipynb

Hi!
I have updated this notebook to make use of the new generic from_edgelist() methods. I have also updated the notebook to mention that graphs can be created from cudf, dask_cudf and Pandas dataframes.
Hope it helps!
Regards,
Miguel
closes #1340

Fix #1340 - Use generic from_edgelist() methods

---

README.md
cpp/src/linear_assignment/README-hungarian.md
python/cugraph/__init__.py
python/cugraph/linear_assignment/__init__.py
python/cugraph/linear_assignment/lap.pxd
python/cugraph/linear_assignment/lap.py
python/cugraph/linear_assignment/lap_wrapper.pyx
python/cugraph/tests/test_hungarian.py

Expose an API for the dense implementation of the Hungarian algorithm.
The implementation is actually done in dense form, the sparse version (previously exposed) converts to a dense matrix before calling.
This change exposes the dense version directly to python, allowing users with dense matrices to send their data directly to the algorithm without converting it to a sparse representation first.
Also include some documentation updates.
Also modified the python return value to include both the cost and the assignment.

Expose dense implementation of Hungarian algorithm

---

cpp/CMakeLists.txt

Gunrock now creates release tags.  Tag v1.2 is the last stable version for our 0.18 release.

Pin gunrock to v1.2 for version 0.18

---

.github/CODEOWNERS
SOURCEBUILD.md

Added configuration for new cugraph-doc-codeowners review group.
This seems to agree with the syntax used elsewhere and described [here](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners), but will need to be tested after this is merged (I'm assuming?) by checking PRs that changed specific files to see if the cugraph-doc-codeowners group is added as expected.

Added configuration for new cugraph-doc-codeowners review group

---

cpp/src/utilities/cython.cu
python/cugraph/community/subgraph_extraction_wrapper.pyx
python/cugraph/link_analysis/pagerank.py
python/cugraph/link_analysis/pagerank_wrapper.pyx
python/cugraph/tests/test_pagerank.py
python/cugraph/tests/test_subgraph_extraction.py

[REVIEW] SG Pagerank transition 

---

conda/environments/cugraph_dev_cuda10.1.yml
conda/environments/cugraph_dev_cuda10.2.yml
conda/environments/cugraph_dev_cuda11.0.yml
python/pytest.ini

added the coverage plugin option by default
added pytest-cov package

Enabling pytest code coverage output by default

---

cpp/include/utilities/shuffle_comm.cuh
cpp/src/experimental/coarsen_graph.cu
cpp/src/experimental/graph.cu
cpp/src/experimental/relabel.cu
cpp/src/experimental/renumber_edgelist.cu

Bug fixes for MNMG coarsen_graph, renumber_edgelist, relabel

Bug fixes for MNMG coarsen_graph, renumber_edgelist, relabel

---

python/cugraph/traversal/traveling_salesperson.py
python/cugraph/traversal/traveling_salesperson_wrapper.pyx

The vertex list that was fed as input to TSP was of type `int64` which ended up being corrupted when passed down
to the cpp layer as `vtx_ptr`. I updated the wrapper to cast the vertices to `int32`. In addition, I fixed the handling of nstart in the wrapper which was assuming vertex ids were starting at 1.
Solves: https://github.com/rapidsai/cugraph/issues/1410

TSP fix route return

---

python/cugraph/traversal/traveling_salesperson.py
python/cugraph/traversal/traveling_salesperson_wrapper.pyx

Auto-merge triggered by push to `branch-0.18` that creates a PR to keep `branch-0.19` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Auto-merge branch-0.18 to branch-0.19 [skip ci]

---

cpp/include/compute_partition.cuh
cpp/include/patterns/count_if_e.cuh
cpp/include/patterns/transform_reduce_e.cuh
cpp/include/patterns/update_frontier_v_push_if_out_nbr.cuh
cpp/include/patterns/vertex_frontier.cuh
cpp/src/experimental/louvain.cuh

This PR partially addresses https://github.com/rapidsai/cugraph/issues/1390

Replace rmm::device_vector & thrust::host_vector with rmm::device_uvector & std::vector, respectively.

---

cpp/docs/DEVELOPER_GUIDE.md

We have long needed a developer's guide.  This PR creates one.  The expectation is that this document will be adapted over time.
I have copied the version from cuDF, edited things to make it cuGraph focused.  There are documentation holes here that will need to eventually be filled in.  However, it's probably useful to get something with holes in it that is approved so we can move forward with some documented standard.

Create cuGraph developers guide

---

cpp/tests/CMakeLists.txt
cpp/tests/experimental/bfs_test.cpp
cpp/tests/experimental/katz_centrality_test.cpp
cpp/tests/experimental/pagerank_test.cpp
cpp/tests/experimental/sssp_test.cpp
cpp/tests/pagerank/mg_pagerank_test.cpp
cpp/tests/utilities/generate_graph_from_edgelist.cu
cpp/tests/utilities/matrix_market_file_utilities.cu
cpp/tests/utilities/misc_utilities.cpp
cpp/tests/utilities/rmat_utilities.cu
cpp/tests/utilities/test_utilities.cu
cpp/tests/utilities/test_utilities.hpp

This partially addresses https://github.com/rapidsai/cugraph/issues/1382 and is a per-requsite for graph primitives performance optimization.

Update C++ MG PageRank and SG PageRank, Katz Centrality, BFS, and SSSP to use the new R-mat graph generator

---

conda/environments/cugraph_dev_cuda10.1.yml
conda/environments/cugraph_dev_cuda10.2.yml
conda/environments/cugraph_dev_cuda11.0.yml
conda/recipes/libcugraph/meta.yaml
cpp/CMakeLists.txt

upgraded FAISS to version 1.7
closes #1440

Update FAISS to 1.7.0

---

ci/gpu/notebook_list.py

A recent update to numba 0.53 in CI broke this script and caused CI failures. This makes the script compatible with both pre and post numba 0.53 versions.
Tested in a local env with numba 0.53 installed.

Update to make notebook_list.py compatible with numba 0.53

---

cpp/src/experimental/graph.cu

After rapidsai/rmm#725 is merged, this PR updates cuspatial to eliminate passing literal values to device_uvector::set_element_async.
Companion PR to rapidsai/cuspatial#367

Remove literals passed to `device_uvector::set_element_async`

---

README.md
docs/source/api.rst
docs/source/dask-cugraph.rst
docs/source/index.rst
python/cugraph/bsp/traversal/bfs_bsp.py
python/cugraph/community/egonet.py
python/cugraph/components/connectivity.py
python/cugraph/dask/centrality/katz_centrality.py
python/cugraph/dask/community/louvain.py
python/cugraph/dask/link_analysis/pagerank.py
python/cugraph/dask/traversal/bfs.py
python/cugraph/dask/traversal/sssp.py
python/cugraph/tree/minimum_spanning_tree.py

* added Hungarian to api.rst
* fixed missing examples
* fixed syntax

Updating docs

---

ci/gpu/build.sh
ci/test.sh
conda/recipes/libcugraph/meta.yaml
cpp/tests/CMakeLists.txt

* Removed unused dependencies from the `libcugraph` recipe.  This is motivated by the CuPy project to integrate `libcugraph` as the graph analytics backend with minimal extra dependencies ( https://github.com/cupy/cupy/issues/4219, https://github.com/cupy/cupy/issues/2431, https://github.com/cupy/cupy/pull/4054 )
* Moved non-test script code from test script to gpu build script. The `FIXME` addressed for this was added after discussing with @raydouglass earlier, and will allow any Project Flash failures to fail the build immediately instead of attempting to then run tests.
* Removed unused cudf lib reference from test cmake file.
Tested by doing a successful local `conda build` of the recipe.

Removed unused dependencies from libcugraph recipe, moved non-test script code from test script to gpu build script

---

cpp/CMakeLists.txt
cpp/cmake/Modules/Version.cmake
cpp/cmake/version_config.hpp.in

Adds cmake function and .hpp template for generating a `version_config.hpp` file, similar to RMM's file of the same name.  This allows C++ clients to include the file from the libcugraph install to query version information for reporting, checking compatibility, etc.
Tested by building and installing libcugraph and checking that `version_config.hpp` was present in the conda environment and contained the correct information.
closes #1472 
FYI @anaruse

Added cmake function and .hpp template for generating version_config.hpp file.

---

cpp/include/algorithms.hpp
cpp/src/traversal/tsp.cu
cpp/src/traversal/tsp.hpp
cpp/src/traversal/tsp_solver.hpp
cpp/src/traversal/tsp_utils.hpp
cpp/tests/CMakeLists.txt
cpp/tests/traversal/tsp_test.cu

Addressed comments from: https://github.com/rapidsai/cugraph/issues/1450
In addition:
1. Made raft handle const.
2. Split algorithm into multiple kernel calls and updated timers.
3. Removed global symbols to retrieve results in struct.

TSP solver bug fix

---

cpp/src/community/egonet.cu
cpp/tests/CMakeLists.txt
cpp/tests/experimental/ms_bfs_test.cpp
cpp/tests/experimental/streams.cu
python/cugraph/__init__.py
python/cugraph/tests/test_egonet.py
python/cugraph/traversal/__init__.py
python/cugraph/traversal/ms_bfs.py
python/cugraph/utilities/utils.py

There are various things in this PR.
Multi-Seed (MS) BFS: 
- API tentative 
- Saving research on memory feasability helper function (not in production)
- Saving research on running the current BFS concurrently with streams and threads for analysis perf comparison (not in production)
EgoNet:
- Multithreading in EgoNet which deserializes execution and comes with mild performance improvements on large sizes
- Some cleanup

MS BFS python APIs + EgoNet updates

---

conda/recipes/cugraph/meta.yaml

Ensure all conda packages created in this repo that depend on other packages are all version pinned to the same build number. This way it prevents a conda solve from picking mismatched versions of `cugraph` and `libcugraph` that can break this repo during builds and testing.

ENH Update conda recipes pinning of repo dependencies

---

cpp/CMakeLists.txt
cpp/tests/traversal/tsp_test.cu

Cugraph fix for: https://github.com/rapidsai/cugraph/issues/1499

Clean up nullptr cuda_stream_view arguments

---

cpp/CMakeLists.txt
cpp/tests/traversal/tsp_test.cu

Forward-merge triggered by push to `branch-0.19` that creates a PR to keep `branch-0.20` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-0.19 to branch-0.20 [skip ci]

---

cpp/CMakeLists.txt

By explicitly telling nvcc's fatbin pass to always compress device code
we can ensure that our binaries are the smallest possible size.
See https://github.com/rapidsai/cudf/pull/7583 for additional context.

Reduce the size of the cugraph libraries

---

conda/environments/cugraph_dev_cuda10.1.yml
conda/environments/cugraph_dev_cuda10.2.yml
conda/environments/cugraph_dev_cuda11.0.yml

Updated NetworkX version to latest version, which addresses an incompatibility with the latest `decorator` dependency.
Tested by running the BC tests which were previously failing with Nx 2.5

Updated NetworkX version to 2.5.1

---

cpp/CMakeLists.txt
cpp/include/utilities/path_retrieval.hpp
cpp/src/utilities/path_retrieval.cu
python/cugraph/tests/test_utils.py
python/cugraph/utilities/__init__.py
python/cugraph/utilities/path_retrieval.pxd
python/cugraph/utilities/path_retrieval.py
python/cugraph/utilities/path_retrieval_wrapper.pyx
python/cugraph/utilities/utils.py

Solves: https://github.com/rapidsai/cugraph/issues/1373

Add utility function for computing a secondary cost for BFS and SSSP output

---

docs/source/api.rst
python/cugraph/centrality/katz_centrality.py
python/cugraph/components/connectivity.py
python/cugraph/dask/centrality/katz_centrality.py
python/cugraph/dask/link_analysis/pagerank.py
python/cugraph/link_analysis/pagerank.py
python/cugraph/structure/symmetrize.py
python/cugraph/traversal/bfs.py
python/cugraph/traversal/traveling_salesperson.py

This pr fixes the following 
- Add traveling salesperson problem to the docs
- Update docs to address all build warnings
To remove some warnings. updated the use of `NOTE:` in cases like the one shown below.
| Old  | New |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/19949207/113936070-283a2380-97ac-11eb-9705-9f261c965fa9.png) | ![image](https://user-images.githubusercontent.com/19949207/113935703-b06bf900-97ab-11eb-93a4-7df2f711c1aa.png)  |

Update docs and remove all warnings [skip-ci]

---

python/cugraph/structure/number_map.py
python/cugraph/tests/dask/test_mg_batch_betweenness_centrality.py
python/cugraph/tests/dask/test_mg_batch_edge_betweenness_centrality.py
python/cugraph/tests/dask/test_mg_bfs.py
python/cugraph/tests/dask/test_mg_comms.py
python/cugraph/tests/dask/test_mg_degree.py
python/cugraph/tests/dask/test_mg_katz_centrality.py
python/cugraph/tests/dask/test_mg_louvain.py
python/cugraph/tests/dask/test_mg_pagerank.py
python/cugraph/tests/dask/test_mg_renumber.py
python/cugraph/tests/dask/test_mg_replication.py
python/cugraph/tests/dask/test_mg_sssp.py
python/cugraph/tests/dask/test_mg_utility.py

* @Iroy30 added missing dask `persist()` call to ensure deterministic indirection map state prior to merging renumbering results.
* @rlratzel updated MG renumbering test for latest API changes, removed redundant test, and updated test IDs to include the dataset name.

[REVIEW] fix mg_renumber non-deterministic errors

---

cpp/CMakeLists.txt

Got rid of the GIT_SHALLOW setting since it should not be enabled by default.

Disabling shallow fetch for cuhornet

---

ci/docs/build.sh

This PR updates the doc build paths in CI to reflect the changes in #1537.

Fix doc build paths for CI [skip ci]

---

CHANGELOG.md
docs/source/conf.py

This is necessary to get the build fix into `main`, but we are not releasing a hotfix for v0.19.

[RELEASE] Build fix for v0.19 cugraph [skip-ci]

---

cpp/CMakeLists.txt
cpp/src/traversal/mg/common_utils.cuh
cpp/src/traversal/mg/vertex_binning.cuh
cpp/tests/centrality/betweenness_centrality_test.cu
cpp/tests/centrality/edge_betweenness_centrality_test.cu

cuDF and RMM have updated to version 1.12, we have been requested to update as well.
This PR is dependent on:
* https://github.com/rapidsai/raft/pull/211
* https://github.com/rapidsai/cuhornet/pull/49
Also disabled some unit tests to reduce our CI time, since we've started seeing timeouts.  Issue #1555 will fully address this issue.

[FEA] Update our thrust version to 1.12

---

ci/docs/build.sh

This PR removes the conda & pip installs from the doc build script since they're already included in our environment at build time.

Remove conda & pip installs from doc script

---

CHANGELOG.md
cpp/CMakeLists.txt

This PR fixes the merge conflicts that prevent `branch-0.19` from cleanly merging into `branch-0.20`.

Merge `branch-0.19` into `branch-0.20`

---

ci/cpu/upload.sh
conda_build.sh

Remove progress output on conda packages upload

ENH Remove progress output on conda packages upload

---

cpp/CMakeLists.txt
cpp/include/patterns/copy_to_adj_matrix_row_col.cuh
cpp/include/patterns/copy_v_transform_reduce_in_out_nbr.cuh
cpp/include/patterns/copy_v_transform_reduce_key_aggregated_out_nbr.cuh
cpp/include/patterns/update_frontier_v_push_if_out_nbr.cuh
cpp/include/utilities/host_barrier.hpp
cpp/include/utilities/shuffle_comm.cuh
cpp/src/experimental/coarsen_graph.cu
cpp/src/experimental/generate_rmat_edgelist.cu
cpp/src/experimental/renumber_edgelist.cu
cpp/src/utilities/host_barrier.cpp

Two bug fixes for multi-GPU graph creation.
- Add barrier to avoid overlap between different communicators
- NCCL bug workaround on DGX1

Fix multi-GPU hang on graph generation

---

cpp/src/experimental/louvain.cuh

in MNMG mode, clusters assigned to different GPUs can increase between iterations.
Merge after #1596 
closes #1586

Bug fix for MNMG Louvain

---

cpp/src/experimental/coarsen_graph.cu

Bug fix in MG coarsen_grph

---

python/cugraph/utilities/utils.py

Fixing broken path utility

---

build.sh

Added `uninstall` target which uninstalls libcugraph and cugraph from a prior build/install step. Also extended the `clean` target to remove inplace artifacts (mainly cython-generated cpp files and inplace `.so` python extensions built from cython).
NOTE: since targets can be combined on the same command, a user can get the "scrub" behavior by running:
```
./build.sh uninstall clean
```

Added `uninstall` target which uninstalls libcugraph and cugraph from a prior build/install step

---

cpp/include/cugraph/experimental/graph_functions.hpp
cpp/include/cugraph/utilities/host_scalar_comm.cuh
cpp/src/experimental/renumber_utils.cu
cpp/tests/CMakeLists.txt
cpp/tests/community/mg_louvain_helper.cu
cpp/tests/community/mg_louvain_helper.hpp
cpp/tests/community/mg_louvain_test.cpp
cpp/tests/experimental/bfs_test.cpp
cpp/tests/experimental/katz_centrality_test.cpp
cpp/tests/experimental/mg_bfs_test.cpp
cpp/tests/experimental/mg_katz_centrality_test.cpp
cpp/tests/experimental/mg_sssp_test.cpp
cpp/tests/experimental/pagerank_test.cpp
cpp/tests/experimental/sssp_test.cpp
cpp/tests/pagerank/mg_pagerank_test.cpp
cpp/tests/utilities/device_comm_wrapper.cu
cpp/tests/utilities/device_comm_wrapper.hpp
cpp/tests/utilities/thrust_wrapper.cu
cpp/tests/utilities/thrust_wrapper.hpp

- Move the utility function to gather distributed vectors from tests/community/mg_louvain_helper.cu to tests/utilities/device_comm_wrapper.cu and rename the function to device_gatherv
- Update MG tests to gather the MG results in root and compare with the SG result in root.
- Few more minor updates (sort_by_key thrust wrapper return value, adding missing const in input parameter, add missing include statement, add barrier in MG performance measurement)
This update is necessary to simplify MG WCC testing.

Move the utility function to gather distributed vectors from tests/community to tests/utilities and update MG tests

---

cpp/CMakeLists.txt
cpp/src/traversal/sssp.cu

RMM is going to require specifying the stream in the device_buffer constructor.
This changes the one `cugraph` item and it updates to a version of `cuhornet` that makes the necessary changes.

Fea rmm device buffer change

---

cpp/docs/DEVELOPER_GUIDE.md

After recent RMM changes, the DEVELOPER_GUIDE.md examples for `rmm::device_buffer` needed to be updated/corrected.

[DOC] Fix developer guide examples for device_buffer [skip-ci]

---

cpp/docs/DEVELOPER_GUIDE.md

Forward-merge triggered by push to `branch-21.06` that creates a PR to keep `branch-21.08` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-21.06 to branch-21.08 [skip ci]

---

cpp/tests/utilities/base_fixture.hpp

Disabling MG C++ testing outputs for non-root processes has an undesirable side effect of disabling error messages (e.g. exception outputs) as well. This makes failure diagnosis difficult in large-scale runs.
Delete the code disabling MG C++ testing outputs for non-root processes in this PR. In long run, we need a more elegant mechanism to disable only redundant test progress messages while still allowing error messages to be displayed.

Undo disabling MG C++ testing outputs for non-root processes

---

cpp/include/cugraph/patterns/copy_v_transform_reduce_key_aggregated_out_nbr.cuh
cpp/include/cugraph/utilities/collect_comm.cuh
cpp/src/experimental/relabel.cu
cpp/src/experimental/renumber_edgelist.cu
cpp/src/experimental/renumber_utils.cu

Currently cuco::static_map instances in cuGraph are initialized with the cuco::static_map default allocator (which uses CUDA memory allocator).
Update to provide the RMM memory allocator instead.

Pass rmm memory allocator to cuco::static_map

---

cpp/src/layout/barnes_hut.hpp
cpp/src/layout/exact_fa2.hpp

Fixes an issue where the layout for all points converge to `(0,0)` when running multiple layout ticks after https://github.com/rapidsai/cugraph/pull/1607.
* Initializes the `d_old_forces` vector to fix layout issue.
* Updates to `barnes_hut.hpp` to use non-deprecated `rmm::exec_policy`.

[FIX] Initialize force_atlas2 `old_forces` device_uvector, use new `rmm::exec_policy`

---

conda/environments/cugraph_dev_cuda11.0.yml
conda/environments/cugraph_dev_cuda11.1.yml
conda/environments/cugraph_dev_cuda11.2.yml
conda/recipes/cugraph/meta.yaml

cc @raydouglass @pentschev @quasiben

Use UCX-Py 0.20

---

cpp/include/cugraph/matrix_partition_device.cuh
cpp/include/cugraph/patterns/copy_v_transform_reduce_key_aggregated_out_nbr.cuh

thrust::sort(thrust::seq, ....) does not work with arbitrary large input data size and this call can fail if the array size to locally sort is large. This code replaces many thread local sort with one thrust::sort call from host.

Remove thread local thrust::sort (thrust::sort with the execution policy thrust::seq) from copy_v_transform_reduce_key_aggregated_out_nbr

---

cpp/CMakeLists.txt

Similar to https://github.com/rapidsai/cuml/pull/3901. 
After #1491 and #rapids-cmake and #1585, now at install time, the cugraph headers are being nested into `path/to/env/include/cugraph/cugraph` instead of just `path/to/env/include/cugraph/`. This, as far as I'm aware, is unintentional and unlike the rest of RAPIDS projects (cuDF, RMM and cuML). 
cc @trxcllnt @robertmaynard

Correct install path for include folder to avoid double nesting

---

cpp/include/cugraph/patterns/transform_reduce_e.cuh

Discovered this bug during louvain testing.  The variable `idx` is an index controlling iteration over a subset of the vertices, while `major_offset` identifies a particular vertex offset in the overall data structure.  Several places where using `idx` where they needed to be using `major_offset`.

transform_reduce_e bug fixes

---

conda/environments/cugraph_dev_cuda11.0.yml
conda/environments/cugraph_dev_cuda11.1.yml
conda/environments/cugraph_dev_cuda11.2.yml
conda/recipes/cugraph/meta.yaml
conda/recipes/libcugraph/meta.yaml

Upgraded recipe and dev envs to NCCL 2.9.9.
The `cugraph` python conda recipe previously included NCCL, but (I think) it's a transient dependency since `libcugraph` actually needs it, so it was removed from the `cugraph` recipe.
cc @dantegd for consistency with cuML.
Note: the NCCL 2.9.9 upgrade was tested during benchmark runs, but the conda recipe changes have not been tested.

Upgraded recipe and dev envs to NCCL 2.9.9

---

cpp/src/community/triangles_counting.cu
cpp/tests/community/triangle_test.cu

Optimizations in the triangle counting logic did computations using available memory to determine the number of cuda blocks to use.
Computation was using a 32-bit integer and on an 80 GB memory system would overflow and generate a negative number - causing a crash.
Adjusted the computation to be done as `size_t` and cast to an int after determining the number of blocks.

[HOTFIX] Bug fix in triangle counting

---

CHANGELOG.md
ci/release/update-version.sh

Branch 21.08 merge 21.06

---

build.sh

Added accidentally-removed cpp-mgtests target back to the valid args list.  This was removed during an update to add `--buildfaiss`, likely due to a bad merge?
Tested by running with the target and observing the MG tests being built and the MPI library being pulled in (still building, will update if something goes wrong)

Added accidentally-removed cpp-mgtests target back to the valid args list

---

cpp/include/cugraph/algorithms.hpp
cpp/src/linear_assignment/hungarian.cu
python/cugraph/linear_assignment/lap.pxd
python/cugraph/linear_assignment/lap.py
python/cugraph/linear_assignment/lap_wrapper.pyx

Completes the work of exposing the precision parameter to the caller in python as requested by #1645 
Fixes a few PR comments from PR #1673 that were deferred as that PR required merging to fix the build.

Expose epsilon parameter (precision) through python layer

---

cpp/CMakeLists.txt

Now that rmm uses rapids-cmake we need to update to the 21.08 branch to get the new `rapids_cmake_write_version_file` function

Use the 21.08 branch of rapids-cmake as rmm requires it

---

python/cugraph/structure/symmetrize.py

fix the function symmetrizing the dask dataframe

fixing symmetrize_ddf

---

ci/checks/style.sh

The `gdf` conda environment has been replaced with the `rapids` environment. A symlink was put in place for `gdf` to continue to work, but the symlink will be removed in the near future. This PR updates all scripts to use the `rapids` environment name.

Update `conda` environment name for CI

---

conda/recipes/cugraph/meta.yaml

Updated cugraph recipe to include CUDA version in build string and depend on a specific cudatoolkit based on CUDA version. This pattern was copied from cuML's recipe.
closes #1708

Updated for CUDA-specific py packages

---

ci/cpu/prebuild.sh
ci/cpu/upload.sh

This PR removes some conditional statements & variables that prevent all the variants of the `cugraph` package from being uploaded to Anaconda.org. This is a continuation of #1709.

Fix `conda` uploads

---

cpp/cmake/thirdparty/get_cuco.cmake

We had an issue in CI that uncovered the fact that raft is referencing the `dev` branch of coco while `cugraph` has it pinned to a previous commit.  CI is using the newer `dev` branch version, which doesn't match what happens when we do local builds.
The original motivation for pinning was a temporary fix because of a bug introduced in `coco` which has since been resolved.  This PR reverts us back to using the `dev` branch.

[REVIEW] revert cuco to latest dev branch, issues should be fixed

---

cpp/cmake/thirdparty/get_cuco.cmake

Forward-merge triggered by push to `branch-21.08` that creates a PR to keep `branch-21.10` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-21.08 to branch-21.10 [skip ci]

---

cpp/cmake/thirdparty/get_cuco.cmake
cpp/cmake/thirdparty/get_raft.cmake

Using the latest `cuco` commit hash as the `GIT_TAG` for release purposes.  See also RAFT PR https://github.com/rapidsai/raft/pull/304 .
Also updated a debug message.
NOTE: using `skip-ci` until https://github.com/rapidsai/raft/pull/304 is merged.
NOTE: The commit hash will likely be reverted to `dev` in 21.10 during development, then a new hash will be used for 21.10 release, and so on.

[skip-ci] Pinning cuco to a specific commit hash for release

---

cpp/cmake/thirdparty/get_cuco.cmake
cpp/cmake/thirdparty/get_raft.cmake

Forward-merge triggered by push to `branch-21.08` that creates a PR to keep `branch-21.10` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-21.08 to branch-21.10 [skip gpuci]

---

cpp/cmake/thirdparty/get_cuco.cmake

Changed cuco cmake function to return early if cuco has already been added as a target.  This matches the technique used by raft [here](https://github.com/rapidsai/raft/blob/a3af3895410c19f3e713caa608ea2024f6008350/cpp/cmake/thirdparty/get_cuco.cmake#L19).
Tested by doing a build and install of cuML, followed by a build of cuGraph and observing a CPM error about the alias target `cuco::cuco` already existing.  Made the change to return early if cuco is already a target and observed the cuGraph `libcugraph.so` build succeed.

Changed cuco cmake function to return early if cuco has already been added as a target

---

cpp/src/community/louvain.cu

Discovered in MNMG testing.
Closes #1713

Modify MNMG louvain to support an empty vertex partition

---

cpp/CMakeLists.txt

This PR adds `include(CPack)` to CMakeLists.txt to support generating source packages for `cugraph`.
cc: @trxcllnt

Include `cpack` to generate source packages

---

cpp/tests/components/con_comp_test.cu
cpp/tests/components/mg_weakly_connected_components_test.cpp
cpp/tests/components/scc_test.cu
cpp/tests/components/weakly_connected_components_test.cpp
cpp/tests/experimental/bfs_test.cpp
cpp/tests/experimental/katz_centrality_test.cpp
cpp/tests/experimental/mg_bfs_test.cpp
cpp/tests/experimental/mg_katz_centrality_test.cpp
cpp/tests/experimental/mg_sssp_test.cpp
cpp/tests/experimental/pagerank_test.cpp
cpp/tests/experimental/sssp_test.cpp
cpp/tests/layout/force_atlas2_test.cu
cpp/tests/pagerank/mg_pagerank_test.cpp
cpp/tests/prims/mg_count_if_v.cu
cpp/tests/prims/mg_reduce_v.cu
cpp/tests/traversal/legacy/sssp_test.cu
cpp/tests/utilities/base_fixture.hpp

Apply the updates in PR #1755 (for MG PageRank) to
MG: Katz Centrality, BFS, SSSP, WCC, and primitive tests
SG: PageRank, Katz Centrality, BFS, SSSP, and WCC tests
@ChuckHastings I will defer Louvain test updates to you :-) once Louvain tests get updated to take R-mat graphs.

C++ benchmarking for additional algorithms

---

python/cugraph/link_analysis/pagerank_wrapper.pyx

fix hard coded pagerank dtype 
closes #1737

Remove hardcoded Pagerank dtype

---

python/cugraph/dask/common/part_utils.py
python/cugraph/dask/link_analysis/pagerank.py
python/cugraph/link_analysis/pagerank.py

fixes pagerank error when personalization is passed

[REVIEW] Bug dask cudf personalization

---

cpp/include/cugraph/detail/shuffle_wrappers.hpp
cpp/include/cugraph/graph_functions.hpp
cpp/src/detail/shuffle_wrappers.cu
cpp/src/structure/coarsen_graph.cu
cpp/src/structure/create_graph_from_edgelist.cpp
cpp/src/structure/renumber_edgelist.cu
cpp/src/utilities/cython.cu
cpp/tests/utilities/rmat_utilities.cpp

Partially addresses Issue https://github.com/rapidsai/cugraph/issues/1477
With the R-mat edge factor of 1 and a DGX machine with 8 GV100 GPUs (32 GB memory each), this PR improves the maximum R-mat scale we can run on the system from 30 to 31 (64 bit vertex & edge IDs).
This PR also includes few code refinements.
Key updates related to memory footprint improvements are in 
1) ```groupby_and_count_edgelist_by_local_partition_id``` (to allow optionally further groupby within a local partition by applying the compute_gpu_id_from_vertex_t to minor vertex IDs)
2) https://github.com/rapidsai/cugraph/pull/1769/files#diff-b8f50bff203b70295af567b06f68707dbd163c791e2630f8f21d4ad4b56f5262R754-R794 (renumber minor vertex IDs of each local partition in segments to limit the memory requirement).
One …

MNMG memory footprint improvement for low average vertex degree graphs (part 1)

---

cpp/src/centrality/betweenness_centrality.cu
cpp/src/community/legacy/egonet.cu
cpp/src/components/weakly_connected_components.cu
cpp/src/structure/graph.cu
cpp/src/structure/graph_view.cu

CUDA 11.4 reports additional warnings. Fix cuGraph warnings in this PR (still, there are many warnings coming from RAFT).

Fix unused variables/parameters warnings

---

ci/gpu/build.sh
conda/environments/cugraph_dev_cuda11.0.yml
conda/environments/cugraph_dev_cuda11.2.yml
conda/recipes/libcugraph/meta.yaml
cpp/cmake/thirdparty/get_rmm.cmake

This should unblock build locally and in CI. Needs to be undone after #1707 is merged. 
cc @ChuckHastings

Temporarily pin RMM while refactor removes deprecated calls

---

python/cugraph/layout/force_atlas2.py
python/cugraph/utilities/nx_factory.py

Allow `force_atlas2` to support hypercube_graph
The example provided in the issue linked to this PR works
closes #1767

[BUG] force_atlas2 to support nx hypercube_graph

---

cpp/tests/community/mg_louvain_helper.cu
cpp/tests/community/mg_louvain_test.cpp

Fix MG Louvain test compile errors after recent PR merges involving thrust execution policies.

Fix MG Louvain test compile errors

---

cpp/src/structure/create_graph_from_edgelist.cpp

create_graph_edgelist (invoked by WCC to create a graph from the edges emitted when concurrently growing BFS trees touch each other) called renumber_edgelist with a valid vertex list argument when invoked by WCC with an invalid vertex list (std::nullopt). This fix checks the validity of the vertex list and calls renumber_edgelist with a valid vertex list only when this function is called with a valid vertex list.

MG WCC bug fix

---

ci/cpu/build.sh
ci/test.sh
conda/recipes/libcugraph/build.sh

Also building cpp MG tests as part of conda/CI libcugraph builds.
This addresses recent issues where commits were merged that broke MG test builds that were not caught in CI.
Tested locally using both a CentOS and Ubuntu `gpuCI` container to run the same build command in the recipe, but did not run the actual `conda build` command on the recipe.  This required additional system packages to be installed in the `gpuCI` containers:
CentOS:
```
yum install openmpi-devel
export PATH=/usr/lib64/openmpi/bin:$PATH
```
Ubuntu:
```
apt install libopenmpi-dev openmpi-bin
```

Also building cpp MG tests as part of conda/CI libcugraph builds

---

ci/cpu/build.sh
ci/cpu/upload.sh
ci/gpu/build.sh
ci/test.sh
conda/recipes/pylibcugraph/build.sh
conda/recipes/pylibcugraph/meta.yaml
python/pylibcugraph/setup.py

Initial version of `pylibcugraph` conda recipe, and changes to CI scripts resulting in CI building and uploading the new `pylibcugraph` conda package as part of the "cpu" build.
Note that `pylibcugraph` build and testing was already taking place as part of the "gpu" build.
Tested the recipe by doing a local build, but I modified several parts of the recipe and build script to accommodate local settings that were different than CI, so full coverage was not achieved locally.

Initial version of `pylibcugraph` conda package and CI build script updates

---

conda/recipes/libcugraph/meta.yaml
docs/cugraph/source/api_docs/index.rst
docs/cugraph/source/api_docs/pylibcugraph.rst
python/pylibcugraph/pylibcugraph/components/_connectivity.pyx
python/pylibcugraph/pylibcugraph/tests/test_connected_components.py

* Changed API to use duck-typing on `__cuda_array_interface__` types instead of requiring users to access and pass the `__cuda_array_interface__` object in directly.
* Added initial placeholder for pylibcugraph docs and docstrings to cython file
* Updated tests to not access the `__cuda_array_interface__` attr directly, added fixtures for easier code reuse, added test for invalid inputs, added FIXMEs to track tech debt in how return values are checked.
Tested API changes by running new unit tests, and tested docs by running `./build.sh docs` and inspecting the html locally in a browser.
NOTE: since this package is still limited to nightly releases (ie. it has not been part of a release yet), it is using the "non-breaking" label even though the user API has changed.
attn: @BradReesWork and …

Changed pylibcugraph connected_components APIs to use duck typing for CAI inputs, added doc placeholders

---

python/cugraph/conftest.py
python/cugraph/cugraph/community/__init__.py
python/cugraph/cugraph/community/ktruss_subgraph.py

Changed code to disable k_truss on CUDA 11.4 to not use `numba.cuda.runtime.get_version()` at import time since this creates a CUDA context which breaks dask `LocalCUDACluster` init (causes a nccl init invaid usage exception).
This code change results in almost the same UX as before, except explicit imports of the k_truss module no longer raise the exception immediately, and instead raise only when a k_truss algo is called.
Tested by ensuring unit tests for the conditional enabling of k_truss still work and also checked that a `LocalCUDACluster` could properly be created.
Also changed `dask_client` fixture to `module` since `session` was not compatible with tests that tried to create a `LocalCUDACluster` independently within the same session (rmat tests).
cc @cjnolet @pentschev

Changed code to disable `k_truss` on CUDA 11.4 differently

---

python/cugraph/community/__init__.py
python/cugraph/community/ktruss_subgraph.py

Changed code to disable `k_truss` on CUDA 11.4 to not use `numba.cuda.runtime.get_version()` at import time since this creates a CUDA context which breaks dask `LocalCUDACluster` init (causes a nccl init invalid usage exception).
This code change results in almost the same UX as before, except explicit imports of the `k_truss` module no longer raise the exception immediately, and instead raise only when a `k_truss` algo is called.
Tested by ensuring unit tests for the conditional enabling of k_truss still work and also checked that a `LocalCUDACluster` could properly be created.
See #1811 for reference

[HOTFIX] Changed code to disable `k_truss` on CUDA 11.4 differently

---

cpp/src/traversal/tsp.cu
cpp/src/traversal/tsp.hpp
cpp/src/traversal/tsp_solver.hpp
cpp/src/traversal/tsp_utils.hpp
python/cugraph/community/__init__.py
python/cugraph/community/ktruss_subgraph.py
python/setup.py
thirdparty/LICENSES/LICENSE.texas_state_university

Removes `-g` from the compile commands generated by distutils to compile Cython files.
This will make our container images, conda packages, and python wheels smaller.

[HOTFIX] Remove `-g` from cython compile commands

---

cpp/include/cugraph/prims/count_if_v.cuh
cpp/include/cugraph/prims/reduce_v.cuh
cpp/include/cugraph/prims/transform_reduce_e.cuh
cpp/include/cugraph/prims/transform_reduce_v.cuh
cpp/include/cugraph/prims/vertex_frontier.cuh
cpp/include/cugraph/utilities/host_scalar_comm.cuh
cpp/src/community/louvain.cuh
cpp/src/components/weakly_connected_components_impl.cuh
cpp/src/link_analysis/pagerank_impl.cuh
cpp/src/structure/graph_impl.cuh
cpp/src/structure/graph_view_impl.cuh
cpp/src/structure/renumber_edgelist_impl.cuh
cpp/src/traversal/bfs_impl.cuh
cpp/src/utilities/cython.cu

Currently, host_scalar_(all)reduce assumes SUM reduction. Adding this input parameter will be necessary for other types of reductions (e.g. MAX).

Added the reduction op input parameter to host_scalar_(all)reduce utility functions.

---

cpp/CMakeLists.txt

Closes #1677 
We require gcc 9.3 and nvcc 11.0 from a feature perspective.  This change forces make to validate that someone building cugraph has these versions.

add compiler version checks to cmake to fail early

---

cpp/CMakeLists.txt

Forward-merge triggered by push to `branch-21.10` that creates a PR to keep `branch-21.12` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-21.10 to branch-21.12 [skip gpuci]

---

cpp/src/structure/graph_impl.cuh

Temporarily disable input argument checks for meta data that are used for the currently disabled feature.

Temporarily disable input argument checks for a currently disabled feature

---

cpp/src/utilities/cython.cu

Changed the value of the expensive check param to false in the call to `populate_graph_container`.
Since the expensive check is still valuable for test and debugging, the option will be exposed to the python user in a separate PR as part of a debug mode API, and for now it's assumed there's test coverage using the expensive check in the C++ tests.
see also #1840 
NOTES:
* This PR has the `bug` label since it prevents a bug from surfacing in the C++ expensive check, but it was not the root cause of the recent test failures. Setting expensive check to false needs to happen regardless for performance reasons.
* This was not built and tested locally yet!

Changed value of the expensive check param to `false` in `populate_graph_container`

---

conda/environments/cugraph_dev_cuda11.0.yml
conda/environments/cugraph_dev_cuda11.2.yml
conda/environments/cugraph_dev_cuda11.4.yml
conda/recipes/cugraph/meta.yaml

Changes to be in-line with: https://github.com/rapidsai/cudf/pull/9286/

Pin max dask and distributed versions to 2021.09.1

---

benchmarks/python_e2e/main.py

fix benchmark exit status

---

python/cugraph/cugraph/centrality/betweenness_centrality.py
python/cugraph/cugraph/centrality/katz_centrality.py
python/cugraph/cugraph/community/ecg.py
python/cugraph/cugraph/community/egonet.py
python/cugraph/cugraph/community/ktruss_subgraph.py
python/cugraph/cugraph/community/leiden.py
python/cugraph/cugraph/community/louvain.py
python/cugraph/cugraph/community/spectral_clustering.py
python/cugraph/cugraph/community/subgraph_extraction.py
python/cugraph/cugraph/community/triangle_count.py
python/cugraph/cugraph/components/connectivity.py
python/cugraph/cugraph/cores/core_number.py
python/cugraph/cugraph/cores/k_core.py
python/cugraph/cugraph/generators/rmat.py
python/cugraph/cugraph/layout/force_atlas2.py
python/cugraph/cugraph/link_analysis/hits.py
python/cugraph/cugraph/link_analysis/pagerank.py
python/cugraph/cugraph/link_prediction/jaccard.py
python/cugraph/cugraph/link_prediction/overlap.py
python/cugraph/cugraph/link_prediction/sorensen.py
python/cugraph/cugraph/sampling/random_walks.py
python/cugraph/cugraph/structure/graph_classes.py
python/cugraph/cugraph/traversal/bfs.py
python/cugraph/cugraph/traversal/sssp.py
python/cugraph/cugraph/tree/minimum_spanning_tree.py
python/cugraph/cugraph/tree/minimum_spanning_tree_wrapper.pyx
python/cugraph/cugraph/utilities/__init__.py
python/cugraph/cugraph/utilities/nx_factory.py
python/cugraph/cugraph/utilities/utils.py
python/pylibcugraph/pylibcugraph/components/_connectivity.pyx

* Changed type check code to no longer require NetworkX and instead only check Nx types if installed. #1851
* Cleaned up imports, removed unused imports.
* Changed `import_optional` to use `importlib` instead, and return `MissingModule` instances for easier error reporting.
* Fixed format of example in `rmat` docstring #1807
* Added docstrings for `pylibcugraph` `*_connected_components` APIs. #1782 
Tested changes to optional import and type checking code by uninstalling `NetworkX`, observing the failure shown in #1851, applying change, then testing to observe the same script runs to completion without Nx installed.
closes #1851 
closes #1807 
closes #1782

Removed NetworkX requirement for type checks, fixed docstring, added new docstrings, import cleanups

---

cpp/cmake/thirdparty/get_cuco.cmake

updating cmake to use the latest cuco

Updating cuco to latest

---

cpp/cmake/thirdparty/get_cuco.cmake

Cugraph 21.10 testing uncovered a bug in the latest cuco. This updates cugraph to point to the cuco version with the bug fix.
Merge after https://github.com/rapidsai/raft/pull/346

update cuco version to pick up bug fix

---

python/cugraph/cugraph/centrality/betweenness_centrality.py
python/cugraph/cugraph/structure/graph_implementation/simpleDistributedGraph.py
python/cugraph/cugraph/structure/graph_implementation/simpleGraph.py
python/cugraph/cugraph/tests/test_bfs.py
python/cugraph/cugraph/tests/test_edge_betweenness_centrality.py
python/cugraph/cugraph/tests/test_modularity.py
python/cugraph/cugraph/tests/test_nx_convert.py
python/cugraph/cugraph/utilities/nx_factory.py

Fixed a number of issues with conversion of Nx directed graphs.  Fix nx tests, fixed issues with using new Graph(directed=true) but checking for DiGraph

Fixing Nx and Graph/DiGraph issues

---

ci/docs/build.sh
ci/release/update-version.sh
cpp/doxygen/Doxyfile

This PR updates cpp/doxygen/Doxyfile to consume the generated Doxygen tags from rmm (see rapidsai/rmm#672). This will enable linking between the cugraph docs and rmm docs.

Enable crosslink to rmm

---

cpp/include/cugraph/graph_functions.hpp
cpp/src/structure/coarsen_graph_impl.cuh
cpp/src/structure/create_graph_from_edgelist_impl.cuh
cpp/src/structure/graph_impl.cuh
cpp/src/structure/renumber_edgelist_impl.cuh
cpp/src/structure/renumber_edgelist_mg.cu
cpp/src/structure/renumber_edgelist_sg.cu
cpp/tests/utilities/base_fixture.hpp
cpp/tests/utilities/test_graphs.hpp

Reduce MNMG memory requirements

---

ci/gpu/build.sh
python/cugraph/cugraph/tests/dask/test_mg_degree.py
python/cugraph/cugraph/tests/dask/test_mg_renumber.py
python/cugraph/cugraph/tests/dask/test_mg_replication.py
python/cugraph/cugraph/tests/test_jaccard.py
python/cugraph/cugraph/tests/test_overlap.py
python/cugraph/cugraph/tests/test_random_walks.py
python/cugraph/cugraph/tests/test_renumber.py
python/cugraph/cugraph/tests/test_sorensen.py
python/cugraph/cugraph/tests/test_wjaccard.py
python/cugraph/cugraph/tests/test_woverlap.py
python/cugraph/cugraph/tests/test_wsorensen.py

cuDF PR https://github.com/rapidsai/cudf/pull/9542 fixes a problem where comparisons between Series objects would return `True` even if the Series names were different, which is inconsistent with Pandas.  Some cuGraph tests relied on the old behavior which ignored names and were failing.
This PR updates those tests to use the proper comparison utility provided by cuDF to restore the intended behavior of the test assertions.
This PR also updates the `gpu` CI script to use `mamba` for an install step to hopefully speed up CI runs.

Updates to support correct comparisons of cuDF Series with different names

---

python/cugraph/cugraph/structure/graph_classes.py
python/cugraph/cugraph/tests/test_graph.py

* Updated error message and using a proper TypeError exception when an invalid MultiGraph is passed in.
* Added test to verify.
This PR replaces #1914 since that one is not passing the style check and the author has not responded.

Updated error message and using a proper TypeError exception when an invalid MultiGraph is passed in

---

cpp/src/generators/generate_rmat_edgelist.cu

There was a bug in the R-mat generator that always leaves the LSB to 0.

Bug fix in the R-mat generator

---

python/cugraph/cugraph/dask/common/part_utils.py

Hi cuGraph team! I was looking at a couple things across RAPIDS related to Python 3.10 compatibility. There is one spot where the deprecated name `collections.Sequence` is used. This was moved to `collections.abc.Sequence` in Python 3.3 and has been deprecated for a while. In Python 3.10 the deprecated names for abstract base classes like `collections.Sequence` were removed.
This PR fixes that module path to help with eventual compatibility with Python 3.10+. I think this is the only instance of this deprecated name across RAPIDS packages.
(I don't have permissions to set labels or project boards, so the label checker will fail until someone else does that.)

Use collections.abc.Sequence instead of deprecated collections.Sequence.

---

notebooks/demo/mg_louvain.ipynb

Added a demonstration notebook for running MNMG Louvain

add new demo notebook for louvain

---

cpp/tests/utilities/test_graphs.hpp
cpp/tests/utilities/thrust_wrapper.cu
cpp/tests/utilities/thrust_wrapper.hpp

Necessary for #1909 
Add options to filter out self-loops & multi-edges after edge generation and before graph creation in C++ test graph generation API.

Add options to drop self-loops & multi_edges in C++ test graph generation

---

cpp/include/cugraph/detail/decompress_matrix_partition.cuh
cpp/include/cugraph/graph_view.hpp
cpp/include/cugraph/prims/copy_v_transform_reduce_in_out_nbr.cuh
cpp/include/cugraph/prims/transform_reduce_by_adj_matrix_row_col_key_e.cuh
cpp/include/cugraph/prims/transform_reduce_e.cuh
cpp/include/cugraph/prims/update_frontier_v_push_if_out_nbr.cuh
cpp/src/structure/graph_view_impl.cuh
cpp/tests/CMakeLists.txt
cpp/tests/link_analysis/mg_pagerank_test.cpp
cpp/tests/structure/count_self_loops_and_multi_edges_test.cpp
cpp/tests/structure/mg_count_self_loops_and_multi_edges_test.cpp

Close #537
Count the number of self-loops & multi-edges.

Count self-loops and multi-edges

---

cpp/cmake/thirdparty/get_raft.cmake
cpp/src/detail/shuffle_wrappers.cu
cpp/src/detail/utility_wrappers.cu
cpp/src/sampling/rw_traversals.hpp
cpp/tests/sampling/random_walks_profiling.cu
cpp/tests/sampling/random_walks_test.cu
cpp/tests/sampling/rw_low_level_test.cu

Depends on https://github.com/rapidsai/raft/pull/356/

Accounting for raft::random detail changes

---

benchmarks/python_e2e/main.py
python/cugraph/cugraph/structure/graph_classes.py
python/cugraph/cugraph/tests/conftest.py
python/cugraph/cugraph/tests/dask/test_mg_renumber.py

A bug was reported when calling a MNMG algo with unrenumbered edge list. 
This PR returns an error if `renumber=False `
Change the algo name for asv reporting 
closes #1936

[BUG] Enforce renumbering for MNMG algos

---

conda/environments/cugraph_dev_cuda11.0.yml
conda/environments/cugraph_dev_cuda11.2.yml
conda/environments/cugraph_dev_cuda11.4.yml
cpp/scripts/run-clang-format.py

This upgrade is required to be in-line with: rapidsai/cudf#9716
Depends on: rapidsai/integration#390

[REVIEW] Upgrade `clang` to `11.1.0`

---

conda/environments/cugraph_dev_cuda11.0.yml
conda/environments/cugraph_dev_cuda11.2.yml
conda/environments/cugraph_dev_cuda11.4.yml
cpp/scripts/run-clang-format.py

Forward-merge triggered by push to `branch-21.12` that creates a PR to keep `branch-22.02` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-21.12 to branch-22.02 [skip gpuci]

---

conda/recipes/libcugraph/meta.yaml

Starting with CUDA 11.1, cusolver updated the major SOVERSION from 10 to 11. To allow execution with the cudatoolkit=11.0 we
need to package the ABI 11 version.

Explicitly install cusolver version with the correct ABI version

---

benchmarks/python_e2e/cugraph_dask_funcs.py
benchmarks/python_e2e/main.py

This PR add the option to initialize workers with an RMM pool size when creating a cluster for SNMG runs
This parameter is essential for benchmarks

add rmm pool option for SNMG runs

---

conda/recipes/libcugraph_etl/meta.yaml

Updates to `libcugraph_etl` conda recipe for CUDA Enhanced Compatibility.  These were not tested locally.

Updates to `libcugraph_etl` conda recipe for CUDA Enhanced Compatibility

---

cpp/tests/community/louvain_test.cpp
cpp/tests/utilities/test_graphs.hpp

Testructure louvain tests to use new test configuration, add rmat tests

Add rmat tests to Louvain C++ unit tests

---

benchmarks/python_e2e/cugraph_dask_funcs.py
python/cugraph/cugraph/tests/conftest.py

The MNMG tests/benchmarks runs rely on killing the dask cluster process ID to stop all python/dask processes
This PR uses `client.shutdown` to shutdown the connected scheduler and workers

Shutdown the connected scheduler and workers

---

cpp/tests/community/egonet_test.cu
cpp/tests/community/induced_subgraph_test.cpp
cpp/tests/structure/coarsen_graph_test.cpp
cpp/tests/structure/degree_test.cpp
cpp/tests/structure/weight_sum_test.cpp

Improve consistency in C++ test case names and add R-mat tests to graph coarsening

---

python/cugraph/cugraph/structure/graph_primtypes_wrapper.pyx

The number of vertices calculation in the previous implementation relied on getting the max of the source and destination's max. Each worker computes the max of its partition however, workers having empty partition attempt to do the same causing an error. This seems to be caused by a recent change on how dask handle empty partitions with the `max()` function. 
This PR calculates the total number of vertices by summing each partition's number of vertices which is inspired from our code base.

fix bug when calculating the number of vertices

---

cpp/src/structure/relabel_impl.cuh

There was one place still using CUDA memory allocator in using cuco::static_map. This PR fixes this.

Pass RMM memory allocator to cuco

---

cpp/tests/link_analysis/hits_test.cpp
cpp/tests/link_analysis/pagerank_test.cpp
cpp/tests/structure/coarsen_graph_test.cpp
cpp/tests/structure/graph_test.cpp
cpp/tests/utilities/base_fixture.hpp
cpp/tests/utilities/test_graphs.hpp

Modified the most expensive C++ tests to run fewer tests.  Closes #1555 
Added an option (like in the rmat tests) to run a specific test file if the developer wants to manually run larger tests.  For example:
```tests/COARSEN_GRAPH_TEST --gtest_filter=file_ben* --test_file_name=test/datasets/ljournal-2008.mtx```
The smaller graphs *should* be small enough to test things.  Once we add C++ code coverage we should be able to verify this.
On my local workstation this reduced the time spent executing the C++ tests by about 25 minutes.

make C++ tests run faster (fewer tests)

---

conda/environments/cugraph_dev_cuda11.0.yml
conda/environments/cugraph_dev_cuda11.2.yml
conda/environments/cugraph_dev_cuda11.4.yml
conda/environments/cugraph_dev_cuda11.5.yml
conda/recipes/cugraph/meta.yaml
python/cugraph/cugraph/utilities/utils.py

Please do not merge until https://github.com/rapidsai/rmm/pull/930 is merged.
For the reasons described in that PR, this API has changed to accept a `cuda.cudart.cudaDeviceAttr` object, `cuda` being the official CUDA Python bindings package.

Fix call to `getDeviceAttribute` following API change in RMM.

---

ci/cpu/build.sh

The directory moving for `cugraph` was missing a `*` in the `cp` command which was creating the wrong directory hierarchy. Fixing this by using `mv` instead

Fix build script

---

cpp/CMakeLists.txt
cpp/include/cugraph_c/algorithms.h
cpp/src/c_api/bfs.cpp
cpp/src/c_api/sssp.cpp
cpp/tests/CMakeLists.txt
cpp/tests/c_api/bfs_test.c
cpp/tests/c_api/c_test_utils.h
cpp/tests/c_api/extract_paths_test.c
cpp/tests/c_api/sssp_test.c
cpp/tests/c_api/test_utils.c

@rlratzel needed the SSSP C API squeezed into version 22.02.  Skipped the usual API PR and implementation PR to squeeze these together in the interest of time.  Note that SSSP is nearly identical (semantically) to BFS which is already in the C API using a similar API.
This PR provides:
* C API definition of SSSP
* C unit test for SSSP
* Implementation of the C API of SSSP (calling the underlying C++ implementation)

Add SSSP API, test and implementation

---

ci/cpu/build.sh

This PR should prevent building CUDA libs in Python jobs and speed up CI

Do not build CUDA libs in Python jobs

---

notebooks/structure/Renumber-2.ipynb
notebooks/structure/Renumber.ipynb
python/cugraph/cugraph/dask/centrality/katz_centrality.py
python/cugraph/cugraph/dask/centrality/mg_katz_centrality_wrapper.pyx
python/cugraph/cugraph/dask/common/input_utils.py
python/cugraph/cugraph/dask/community/louvain.py
python/cugraph/cugraph/dask/community/louvain_wrapper.pyx
python/cugraph/cugraph/dask/components/connectivity.py
python/cugraph/cugraph/dask/components/mg_connectivity_wrapper.pyx
python/cugraph/cugraph/dask/link_analysis/mg_pagerank_wrapper.pyx
python/cugraph/cugraph/dask/link_analysis/pagerank.py
python/cugraph/cugraph/dask/traversal/bfs.py
python/cugraph/cugraph/dask/traversal/mg_bfs_wrapper.pyx
python/cugraph/cugraph/dask/traversal/mg_sssp_wrapper.pyx
python/cugraph/cugraph/dask/traversal/sssp.py
python/cugraph/cugraph/structure/graph_classes.py
python/cugraph/cugraph/structure/graph_implementation/simpleDistributedGraph.py
python/cugraph/cugraph/structure/graph_implementation/simpleGraph.py
python/cugraph/cugraph/structure/graph_primtypes.pyx
python/cugraph/cugraph/structure/graph_primtypes_wrapper.pyx
python/cugraph/cugraph/structure/number_map.py
python/cugraph/cugraph/structure/renumber_wrapper.pyx
python/cugraph/cugraph/tests/dask/test_mg_katz_centrality.py
python/cugraph/cugraph/tests/dask/test_mg_renumber.py
python/cugraph/cugraph/tests/test_renumber.py

* Updates to enable `NumberMap` to generate unique src/dst column names instead of assuming the names `src` and `dst`. This is needed since cudf no longer allows for duplicate column names, and some user input may contain "src" and "dst" as pre-existing column names intended for other purposes.
* This commit also cleans up various tech debt items (exception types, docstrings, etc.).
Tested by ensuring the existing python unit tests for SG and MG (2 GPUs) passed, and also ran all notebooks as tests. New tests to emphasize support for specific column names that previously failed with the latest cudf were also added.

Updates to enable NumberMap to generate unique src/dst column names

---

cpp/tests/CMakeLists.txt

This PR adds a CMake `install` rule for test targets. This step is a prerequisite to being able to package tests in their own `conda` package, which will enable us to deprecate _Project Flash_.

Add CMake `install` rules for tests

---

cpp/src/community/louvain.cuh
cpp/tests/community/mg_louvain_test.cpp

R-mat usecase parameters weren't set for multi-GPU tests. Fixed in this PR.

[BUG] MG Louvain C++ test R-mat usecase parameters

---

python/pylibcugraph/pylibcugraph/graphs.pyx
python/pylibcugraph/pylibcugraph/pagerank.pyx
python/pylibcugraph/pylibcugraph/sssp.pyx
python/pylibcugraph/pylibcugraph/tests/test_connected_components.py
python/pylibcugraph/pylibcugraph/utils.pxd
python/pylibcugraph/pylibcugraph/utils.pyx

Refactored common code that copies device arrays returned by `cugraph_*` C APIs to cupy arrays into a utility function.  This eliminates a significant amount of repeated code, and will be especially helpful as new `pylibcugraph` APIs are added that copy the existing patterns.
Tested by running existing `pylibcugraph` unit tests.

Added `pylibcugraph` utility for setting up return array values

---

cpp/src/c_api/bfs.cpp
cpp/src/c_api/extract_paths.cpp
cpp/src/c_api/pagerank.cpp
cpp/src/c_api/sssp.cpp
cpp/src/c_api/utils.hpp

Pull out common cascading logic/error handling into a template function.  This cleans up the existing C API implementations and will make new C API implementations a bit simpler.
Note: #2069 uses the old paradigm.  Depending on merge order we might want to modify the node2vec implementation to use this technique also.  Can decide whether to do that in 2069 if this PR merges first, or if 2069 merges first we can either add that to this PR or leave it as tech debt to address later.

C API code cleanup

---

docs/cugraph/source/api_docs/centrality.rst
docs/cugraph/source/api_docs/community.rst
docs/cugraph/source/api_docs/components.rst
docs/cugraph/source/api_docs/cores.rst
docs/cugraph/source/api_docs/graph_implementation.rst
docs/cugraph/source/api_docs/index.rst
docs/cugraph/source/api_docs/layout.rst
docs/cugraph/source/api_docs/linear_assignment.rst
docs/cugraph/source/api_docs/link_analysis.rst
docs/cugraph/source/api_docs/link_prediction.rst
docs/cugraph/source/api_docs/pylibcugraph.rst
docs/cugraph/source/api_docs/sampling.rst
docs/cugraph/source/api_docs/structure.rst
docs/cugraph/source/api_docs/traversal.rst
python/cugraph/cugraph/centrality/betweenness_centrality.py
python/cugraph/cugraph/components/connectivity.py
python/cugraph/cugraph/cores/core_number.py
python/cugraph/cugraph/layout/force_atlas2.py
python/cugraph/cugraph/linear_assignment/lap.py
python/cugraph/cugraph/link_prediction/overlap.py
python/cugraph/cugraph/link_prediction/sorensen.py
python/cugraph/cugraph/structure/graph_implementation/simpleGraph.py
python/cugraph/cugraph/structure/number_map.py
python/cugraph/cugraph/utilities/utils.py

Increases consistency between the API docs and the namespace in which the method can be called from, reducing potential confusion. Ex: cugraph.centrality.betweenness_centrality.betweenness_centrality can now be found as cugraph.betweenness_centrality. Note: both are valid ways of calling the same method.
Includes methods and attributes of a graph object once data is loaded (from SimpleGraphImpl), such as number_of_vertices, has_edge, get_two_hops_neighbors, etc.
Ready for review.

API Doc Namespace Edits + SimpleGraphImpl methods

---

cpp/include/cugraph/detail/shuffle_wrappers.hpp
cpp/include/cugraph/graph_functions.hpp
cpp/include/cugraph/prims/copy_v_transform_reduce_key_aggregated_out_nbr.cuh
cpp/include/cugraph/prims/transform_reduce_by_adj_matrix_row_col_key_e.cuh
cpp/include/cugraph/utilities/collect_comm.cuh
cpp/include/cugraph/utilities/cython.hpp
cpp/include/cugraph/utilities/shuffle_comm.cuh
cpp/src/community/louvain.cuh
cpp/src/components/weakly_connected_components_impl.cuh
cpp/src/detail/shuffle_wrappers.cu
cpp/src/structure/coarsen_graph_impl.cuh
cpp/src/structure/create_graph_from_edgelist_impl.cuh
cpp/src/structure/graph_impl.cuh
cpp/src/structure/relabel_impl.cuh
cpp/src/structure/renumber_edgelist_impl.cuh
cpp/src/utilities/cython.cu
cpp/tests/utilities/test_graphs.hpp

Previously, graph creation requires roughly edge data size * 2 + alpha (if we can destroy the input edge data and reclaim the memory, * 3 if the input edge data cannot be destroyed). This PR cuts this to edge data size * 1.5 + alpha.
This is a breaking PR for projects using functions under https://github.com/rapidsai/cugraph/blob/branch-22.04/cpp/include/cugraph/utilities/shuffle_comm.cuh (@aschaffer You may be affected).
There will be a follow-up PR further optimizing memory footprint. Wrapping up this PR to avoid creating a giant PR.

Reduce peak memory requirement in graph creation (part 1/2)

---

cpp/include/cugraph/detail/decompress_matrix_partition.cuh
cpp/include/cugraph/detail/graph_utils.cuh
cpp/src/structure/coarsen_graph_impl.cuh
cpp/tests/community/louvain_test.cpp
cpp/tests/structure/coarsen_graph_test.cpp

If you coarsen a symmetric (i.e. undirected) graph, the output graph should be symmetric as well.
However, due to limited floating point resolution, edge weights can be slightly asymmetric after coarsening (e.g. for a triplet of src, dst, weight, we may see (1, 2, 1.0) and its reverse edge (2, 1, 1.0 + 1e-7), this is only approximately symmetric and not strictly symmetric).
This PR fixes this by coarsening using only the lower triangular part (including the diagonal) after relabeling and reconstructing a symmetric graph from the lower triangular part (if the input graph is symmetric).

Coarsening symmetric graphs leads to slightly asymmetric edge weights

---

cpp/src/sampling/random_walks.cuh
cpp/tests/c_api/node2vec_test.c

Random walk implementation returns a list of paths (vertex ids) and a list of edge weights for the edges on those paths.
@betochimas discovered that the size of the returned arrays is the same, even though the contents are different sizes.  In his example, if the return path contains one path:  `[ 0, 1, 3, 5 ]` it returns a weights array with 4 elements `[0.1, 2.1, 7.2, ???]` even though only the first three elements are valid.  The weights are edge weights, the path `[0,1,3,5]` only has 3 edges.  The first 3 elements in the returned array are correct.  Interpreting the results as intended will never reference that value.  However the sizes should be correct.
This PR fixes the initialization of the arrays to the correct size, which seems to correct the bug.

Fix bug Random Walk in array sizes

---

cpp/cmake/thirdparty/get_libcugraphops.cmake
cpp/include/cugraph/algorithms.hpp
cpp/src/sampling/neighborhood.cu
cpp/src/utilities/cugraph_ops_utils.hpp

cugraph-ops header files are being renamed to be better inline with rapids.

Fix cugraph-ops header names

---

cpp/include/cugraph/prims/extract_if_e.cuh

extract_if_e primitive bug fix.
This primitive takes a device_view of row(or column)_properties_t objects, and in the internal implementation, we need to properly set the local edge partition ID to properly retrieve row properties (if CSR-ish data structure is used).
This cod was missing and this PR fixes the bug.

extract_if_e bug fix.

---

python/cugraph/cugraph/sampling/random_walks.py
python/pylibcugraph/pylibcugraph/_cugraph_c/algorithms.pxd
python/pylibcugraph/pylibcugraph/experimental/__init__.py
python/pylibcugraph/pylibcugraph/graphs.pyx
python/pylibcugraph/pylibcugraph/node2vec.pyx
python/pylibcugraph/pylibcugraph/tests/test_node2vec.py
python/pylibcugraph/pylibcugraph/utils.pxd
python/pylibcugraph/pylibcugraph/utils.pyx

Helps close #2058, when combined with a future PR for the cugraph layer implementation of node2vec, which depends on this PR. Ready for review. Disregard #2084 and #2063.

Add `node2vec` wrappers to pylibcugraph

---

conda/environments/cugraph_dev_cuda11.0.yml
conda/environments/cugraph_dev_cuda11.2.yml
conda/environments/cugraph_dev_cuda11.4.yml
conda/environments/cugraph_dev_cuda11.5.yml
conda/recipes/cugraph/meta.yaml

This PR upgrades `dask` & `distributed` min versions to be inline with: https://github.com/rapidsai/cudf/pull/10182/

[REVIEW] Upgrade `dask` and `distributed`

---

conda/recipes/cugraph/meta.yaml

Merged PR #2093 requires `pylibcugraph`. This PR adds `pylibcugraph` as a run dependency to the `cugraph` conda package.

Add pylibcugraph as a run dep to the cugraph conda package

---

python/pylibcugraph/pylibcugraph/raft/common/handle.pxd

Removed unused cython code referencing RAFT APIs that are no longer present. Tested locally by doing a build with the latest RAFT.

Remove unused cython code referencing RAFT APIs that are no longer present

---

cpp/include/cugraph/graph_functions.hpp
cpp/include/cugraph/utilities/cython.hpp
cpp/src/structure/create_graph_from_edgelist_impl.cuh
cpp/src/structure/renumber_edgelist_impl.cuh
cpp/src/structure/renumber_edgelist_mg.cu
cpp/src/structure/renumber_edgelist_sg.cu
cpp/src/utilities/cython.cu
cpp/tests/community/mg_louvain_helper.cu
cpp/tests/community/mg_louvain_helper.hpp
cpp/tests/structure/renumbering_test.cpp
python/cugraph/cugraph/structure/graph_utilities.pxd
python/cugraph/cugraph/structure/renumber_wrapper.pyx

Partially addresses #2003
We should not use major,minor (instead of src, dst) in the public non-detail API and should use major,minor in the detail space.
The public non-detail namespace renumber_edgelist currently uses major, minor and this PR fixes this.
This PR also replaces row/col to src/dst in `single_gpu_renumber_edgelist_given_number_map` as we're aiming to consistently use src/dst instead of row/col in our public C++ API.
This is possibly breaking as this PR changes the public API (but I am not aware of any non-cugraph libraries directly calling renumber_edgelist).

Remove major/minor from renumber_edgelist public functions.

---

conda/environments/cugraph_dev_cuda11.0.yml
conda/environments/cugraph_dev_cuda11.2.yml
conda/environments/cugraph_dev_cuda11.4.yml
conda/environments/cugraph_dev_cuda11.5.yml

Forward-merge triggered by push to `branch-22.04` that creates a PR to keep `branch-22.06` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-22.04 to branch-22.06 [skip gpuci]

---

cpp/CMakeLists.txt
cpp/cmake/thirdparty/get_libcugraphops.cmake
cpp/cmake/thirdparty/get_raft.cmake

Depends on https://github.com/rapidsai/raft/pull/583 and https://github.com/rapidsai/cugraph-ops/pull/70
This PR uses `CPMFindPackage` to find (or build) `cugraph-ops`.
This enables building from source against a local `cugraph-ops` build via `-D cugraph-ops_ROOT=/cugraph-ops/build`.

[FIX] Use `rapids_find_package` to get `cugraph-ops`

---

cpp/include/cugraph/detail/shuffle_wrappers.hpp
cpp/include/cugraph/graph_functions.hpp
cpp/include/cugraph_c/graph.h
cpp/src/c_api/bfs.cpp
cpp/src/c_api/hits.cpp
cpp/src/c_api/pagerank.cpp
cpp/src/c_api/sssp.cpp
cpp/src/detail/shuffle_wrappers.cu
cpp/src/structure/renumber_utils_impl.cuh
cpp/src/structure/renumber_utils_mg.cu
cpp/src/structure/renumber_utils_sg.cu
cpp/tests/CMakeLists.txt
cpp/tests/c_api/bfs_test.c
cpp/tests/c_api/c_test_utils.h
cpp/tests/c_api/extract_paths_test.c
cpp/tests/c_api/hits_test.c
cpp/tests/c_api/mg_hits_test.c
cpp/tests/c_api/mg_pagerank_test.c
cpp/tests/c_api/mg_test_utils.cpp
cpp/tests/c_api/mg_test_utils.h
cpp/tests/c_api/node2vec_test.c
cpp/tests/c_api/pagerank_test.c
cpp/tests/c_api/sssp_test.c
cpp/tests/c_api/test_utils.cpp

Closes #2092 
Provide the C API implementation for HITS.  Adds a unit tester for MG, updates the unit tests for both SG and MG.

HITS C API implementation

---

conda/environments/cugraph_dev_cuda11.2.yml
conda/environments/cugraph_dev_cuda11.4.yml
conda/environments/cugraph_dev_cuda11.5.yml
conda/recipes/libcugraph/meta.yaml
conda/recipes/libcugraph_etl/meta.yaml

CMake 3.23 has a bug that breaks our conda-build based builds in CI, this avoids that issue.

Pin cmake in conda recipe to <3.23

---

cpp/CMakeLists.txt
cpp/include/cugraph_c/algorithms.h
cpp/src/c_api/centrality_result.cpp
cpp/src/c_api/centrality_result.hpp
cpp/src/c_api/eigenvector_centrality.cpp
cpp/src/c_api/pagerank.cpp
cpp/tests/CMakeLists.txt
cpp/tests/c_api/eigenvector_centrality_test.c
cpp/tests/c_api/mg_eigenvector_centrality_test.c
cpp/tests/c_api/mg_pagerank_test.c
cpp/tests/c_api/pagerank_test.c
python/cugraph/cugraph/structure/hypergraph.py
python/pylibcugraph/pylibcugraph/_cugraph_c/algorithms.pxd
python/pylibcugraph/pylibcugraph/pagerank.pyx

This PR defines the C API for eigenvector centrality.  It is the first of a series of PRs to address #2146
It also does the following:
* Renames `cugraph_pagerank_result_t` to `cugraph_centrality_result_t` to allow it to be reused for all centrality algorithms
* Reorganizes the code for the results into a separate file
* Provides an initial implementation of eigenvector centrality that can be used for testing the API.  NOTE: It literally calls pagerank with some hardcoded parameters.  The return formats for the algorithms are the same, so this will mimic the API behavior (although the scores will be different once eigenvector centrality is implemented
* Provided a C unit test that validates the results (will need to be updated to validate eigenvector centrality results once the real …

Define C API for eigenvector centrality

---

build.sh
cpp/src/c_api/katz.cpp

I added a new algorithm while Seunghwa modified a graph_view method name.  The two PRs passed and merged but introduced this error.

Fix error from two conflicting merges

---

notebooks/link_analysis/Pagerank.ipynb

Fixes some small inconsistencies between code blocks / diagrams and their associated captions in the Pagerank notebook. We might want to resolve the FutureWarning raised in `from_cudf_edgelist` first, as it crops up in the outputs (xref https://github.com/rapidsai/cugraph/issues/2174).
Closes #2182

Make diagram and caption consistent in Pagerank.ipynb

---

cpp/include/cugraph/utilities/cython.hpp
cpp/src/utilities/cython.cu
python/cugraph/cugraph/structure/graph_utilities.pxd
python/cugraph/cugraph/structure/renumber_wrapper.pyx

Closes #2217 
The issue identifies some issues if the partitioning ends up with some empty partitions.  There were two issues here:
1. The `call_shuffle` method determines whether a graph has weights by comparing the weight pointer to `nullptr`.  But if an MNMG partition is empty then the weight pointer will be `nullptr` even if the graph has weights.  Added a parameter to identify if the graph is weighted.
2. The `renumber_helper` method was missing an else and was overwriting the correct value with an invalid value if the return from shuffling on a gpu had no entries.
These are corrected in the PR.

Address some MNMG issues in cython.cu

---

python/cugraph/cugraph/tests/dask/test_mg_bfs.py
python/cugraph/cugraph/tests/dask/test_mg_comms.py
python/cugraph/cugraph/tests/dask/test_mg_connectivity.py
python/cugraph/cugraph/tests/dask/test_mg_degree.py
python/cugraph/cugraph/tests/dask/test_mg_hits.py
python/cugraph/cugraph/tests/dask/test_mg_louvain.py
python/cugraph/cugraph/tests/dask/test_mg_pagerank.py
python/cugraph/cugraph/tests/dask/test_mg_sssp.py
python/cugraph/cugraph/tests/dask/test_mg_utility.py
python/cugraph/cugraph/tests/utils.py
python/cugraph/cugraph/utilities/utils.py

replace all DiGraph with Graph(directed=True)
Set some test to run on single GPU

updated MG Test code to not use DiGraph

---

cpp/CMakeLists.txt
cpp/include/cugraph/algorithms.hpp
cpp/src/community/triangle_counts_impl.cuh
cpp/src/community/triangle_counts_mg.cu
cpp/src/community/triangle_counts_sg.cu

Define C++ API for triangle counting.

Triangle Counts C++ API

---

cpp/libcugraph_etl/include/hash/concurrent_unordered_map.cuh
python/cugraph/cugraph/structure/hypergraph.py

Updated as part of https://github.com/rapidsai/cudf/pull/10462
Update namespace for default_hash.
Also update a python call that was changed in cudf.

cudf moved the default_hash into the cudf::detail namespace

---

cpp/include/cugraph_c/algorithms.h
cpp/src/c_api/uniform_neighbor_sampling.cpp
cpp/tests/c_api/mg_uniform_neighbor_sample_test.c
cpp/tests/c_api/uniform_neighbor_sample_test.c

Added an API for the new uniform neighborhood sampling implementation.
Added the API with an experimental tag in its name so it won't break the current python code.  Plan is to have the new API replace the existing API during this release.
Plan for this release will be to have the edge weight be an edge index (passed by the calling python code), so the return "index" value will be the edge weight.  Down the road we will release this restriction and allow real edge weights.
Addresses part 1 of #2226

add API for the new uniform neighborhood sampling

---

notebooks/link_prediction/Overlap-Similarity.ipynb
python/cugraph/cugraph/tree/minimum_spanning_tree.py

Branch 22.06 bugs

---

python/cugraph/cugraph/tests/test_maximum_spanning_tree.py
python/cugraph/cugraph/tests/test_minimum_spanning_tree.py
python/cugraph/cugraph/tree/minimum_spanning_tree.py

This PR resolves #2251 , where minimum spanning tree and maximum spanning tree had different behaviors when using edge list data versus adjacency list data, specifically that a call to compute the adjacency list had to be made before running maximum spanning tree because of how weights were calculated. After adding a check to verify that the adjacency list was computed, examples for both mst algorithms were uncommented.

Resolves maximum spanning tree bug when using Edgelist instead of Adjlist

---

cpp/CMakeLists.txt
cpp/include/cugraph_c/algorithms.h
cpp/include/cugraph_c/community_algorithms.h
cpp/src/c_api/triangle_count.cpp
cpp/tests/CMakeLists.txt
cpp/tests/c_api/c_test_utils.h
cpp/tests/c_api/mg_triangle_count_test.c
cpp/tests/c_api/triangle_count_test.c

This defines the C API for triangle counting.
This PR is independent of #2253 and can be merged independently.  The change here defines the C API and returns the `CUGRAPH_NOT_IMPLEMENTED` error when called.  Once #2253 is completed and merged, a follow-up PR will fill in the C API implementation for triangle counting (although the code is written and untested in this PR).

Define triangle_count C API

---

cpp/include/cugraph/prims/count_if_e.cuh
cpp/include/cugraph/prims/count_if_v.cuh
cpp/include/cugraph/prims/extract_if_e.cuh
cpp/include/cugraph/prims/per_src_dst_key_transform_reduce_e.cuh
cpp/include/cugraph/prims/per_v_transform_reduce_dst_key_aggregated_outgoing_e.cuh
cpp/include/cugraph/prims/per_v_transform_reduce_incoming_outgoing_e.cuh
cpp/include/cugraph/prims/reduce_v.cuh
cpp/include/cugraph/prims/transform_reduce_e.cuh
cpp/include/cugraph/prims/transform_reduce_v.cuh
cpp/include/cugraph/prims/update_edge_partition_src_dst_property.cuh

Partially address #2003
Add the `do_expensive_check` input parameter to graph primitives.

Add do_expensive_check to graph primitives

---

cpp/src/c_api/bfs.cpp
cpp/src/c_api/sssp.cpp
cpp/tests/CMakeLists.txt
cpp/tests/c_api/mg_bfs_test.c
cpp/tests/c_api/mg_sssp_test.c

@alexbarghi-nv found some issues testing BFS for MG through the C API.  Essential problem is that the C API needs to shuffle the source vertices across the GPUs.
Did the following:
* Add Alex B's mg_bfs_test
* Add missing mg_sssp_test
* Add shuffle of vertex ids for MG in bfs
* Fix sizing of array in sssp

Fix MG BFS through C API

---

conda/recipes/cugraph/conda_build_config.yaml
conda/recipes/cugraph/meta.yaml
conda/recipes/libcugraph/conda_build_config.yaml
conda/recipes/libcugraph/meta.yaml
conda/recipes/pylibcugraph/conda_build_config.yaml
conda/recipes/pylibcugraph/meta.yaml
python/pylibcugraph/setup.py

This PR enables the usage of conda compilers to build conda packages. This is required to use `mambabuild`

Use conda compilers

---

cpp/include/cugraph_c/array.h
cpp/src/c_api/array.cpp
cpp/src/sampling/detail/graph_functions.hpp
cpp/src/sampling/detail/sampling_utils_impl.cuh
cpp/src/sampling/detail/sampling_utils_mg.cu
cpp/src/sampling/detail/sampling_utils_sg.cu
cpp/src/sampling/uniform_neighbor_sampling_impl.hpp
cpp/tests/c_api/mg_test_utils.cpp
cpp/tests/c_api/mg_test_utils.h
cpp/tests/c_api/mg_uniform_neighbor_sample_test.c
cpp/tests/c_api/uniform_neighbor_sample_test.c

Missed this in the last uniform neighborhood sampling updates.
Added a mechanism for creating a graph using an edge index as the weight.  This is a temporary mechanism until we add direct support for edge indexes in the graph.

Add and test mechanism for creating graph with edge index as weight

---

cpp/CMakeLists.txt
cpp/include/cugraph_c/community_algorithms.h
cpp/src/c_api/louvain.cpp
cpp/tests/CMakeLists.txt
cpp/tests/c_api/louvain_test.c
cpp/tests/c_api/mg_louvain_test.c

This PR adds Louvain to the C API.  This PR is a full implementation including:
* C API definition
* C API implementation calling the C++ version of Louvain
* SG and MG unit tests exercising the Louvain implementation
* A small documentation update to triangle counting that was discovered in the final review of the triangle counting C API PR

Add Louvain to the C API

---

python/cugraph/cugraph/structure/convert_matrix.py
python/cugraph/cugraph/structure/graph_implementation/simpleGraph.py
python/cugraph/cugraph/tests/test_convert_matrix.py
python/cugraph/cugraph/tests/test_graph.py

Fixes the bug where "to_pandas_edgelist" ignores output column names

fixes BUG 2275

---

python/cugraph/cugraph/tests/mg/test_mg_symmetrize.py

This PR refactors and fixes mg symmetrize tests
closes #2277

Refactor mg symmetrize tests 

---

conda/environments/cugraph_dev_cuda11.2.yml
conda/environments/cugraph_dev_cuda11.4.yml
conda/environments/cugraph_dev_cuda11.5.yml
conda/recipes/cugraph/meta.yaml

Pinning to be in line with: https://github.com/rapidsai/cudf/pull/10987

[REVIEW] Pin `dask` and `distributed` for release

---

cpp/src/sampling/detail/sampling_utils_impl.cuh

Bug was discovered in how the sampling code is looking up DCSR offset.

fix sampling handling of dscr region

---

docs/cugraph/source/api_docs/dask-cugraph.rst

This PR fixes the `comms` import in the API docs.

Fix  import in the api_docs

---

cpp/tests/CMakeLists.txt

Closes #2314
Rather than relying on the output from nvidia-smi, MG C++ tests will default to 1 GPU.  This default can be overridden by the developer by calling `cmake` with the option: `-DGPU_COUNT=` and specifying the desired number of GPUs.
Note that the user can always run individual tests by directly calling `mpirun`.  This only affects the default used by `ctest`, `make test` or `ninja test` to run the entire suite of tests.

Default GPU_COUNT to 1 in cmake file

---

cpp/src/sampling/detail/sampling_utils_impl.cuh

@jnke2016 found a bug in the sampling code.
Fix weight lookup to match index lookup.  The weight array mirrors the indices array in its structure, but the computation to do the lookup was correct for the indices array but incorrect for the weights array.

Fix sampling bug

---

cpp/CMakeLists.txt
cpp/include/cugraph/algorithms.hpp
cpp/src/utilities/cython.cu
cpp/tests/CMakeLists.txt

Legacy SSSP implementation should not be referenced any longer.

Remove legacy sssp implementation

---

notebooks/cugraph_benchmarks/release.ipynb

There was an issue where some Nx methods return a generator and not a full answer. These functions (WCC, Jaccard, and BFS) were identified and fixed for the purpose of getting more accurate ("apples-to-apples") comparisons against cuGraph methods. 
Next, `time.time()` was replaced with `time.perf_counter()` to get appropriate interval timings.

Release notebook: Nx Generators & Adding Perf_counter

---

python/cugraph/cugraph/gnn/graph_store.py
python/cugraph/cugraph/tests/test_graph_store.py
python/cugraph/cugraph/utilities/utils.py

This PR fixes sampling  when for the default value of -1 which is called below: 
https://github.com/rapidsai/cugraph/blob/92f6ba451b2d9e6c3f60dbccfa05bbf3c480e43a/python/cugraph/cugraph/gnn/graph_store.py#L129-L133
In workflows this is called during inference so we need this to work for inference to work .with CuGraphStorage .

[REVIEW]Fix Fanout -1

---

cpp/cmake/thirdparty/get_cuco.cmake
cpp/include/cugraph/prims/detail/nbr_intersection.cuh
cpp/include/cugraph/prims/per_v_transform_reduce_dst_key_aggregated_outgoing_e.cuh
cpp/include/cugraph/utilities/collect_comm.cuh
cpp/src/structure/relabel_impl.cuh
cpp/src/structure/renumber_edgelist_impl.cuh
cpp/src/structure/renumber_utils_impl.cuh

RAFT is updating to the newest version of `cuco` in this PR: https://github.com/rapidsai/raft/pull/714
This PR makes the necessary changes to cugraph to support the latest `cuco`.  It should be merged after the RAFT PR.
* update version of cuco
* update constructor calls to cuco::static_map

Support raft updating to new version of cuco

---

cpp/src/detail/utility_wrappers.cu

With the RAFT changes here: https://github.com/rapidsai/raft/pull/690 we should be able to use the PC generator again.  The PC generator is significantly faster.
Closes #2266

Switch back to PC generator

---

cpp/src/sampling/detail/sampling_utils_impl.cuh

@jnke2016 found a few more issues.
This update changes the hyper sparse computation, passes more of the MG tests.

Update sampling primitive again, fix hypersparse computations

---

docs/cugraph/source/conf.py

Needed for Sphinx 5 compatibility. Should fix the following warning occurring in doc builds.
```
Invalid configuration value found: 'language = None'. Update your configuration to a valid langauge code. Falling back to 'en' (English).
```
xref: https://github.com/sphinx-doc/sphinx/pull/10481

[REVIEW] Switch `language` from `None` to `"en"` in docs build

---

cpp/include/cugraph/legacy/eidecl_graph.hpp
cpp/include/cugraph/legacy/eidir_graph.hpp
cpp/include/cugraph/legacy/graph.hpp
cpp/include/cugraph/utilities/cython.hpp
cpp/src/utilities/cython.cu

Delete the legacy CSC graph objects.  They are no longer used (all transposed=True algorithms have been migrated to the new graph objects).
Marked `breaking` since it deletes a C++ API feature, although should no longer be used.

Remove GraphCSC/GraphCSCView object, no longer used

---

docs/cugraph/source/api_docs/dask-cugraph.rst

This PR updates the multi-GPU example in the docs to include input data generation using `rmat`, as well as resolving the missing / unnecessary imports.

Update multi-GPU example to include data generation [skip-ci]

---

ci/gpu/build.sh
ci/test.sh

cpp_changed==cpp+python+notebooks, python_changed==python+notebooks, notebooks_changed==notebooks

Run relevant CI tests based on what's changed in the ChangeList

---

python/cugraph/cugraph/dask/structure/mg_property_graph.py
python/cugraph/cugraph/structure/property_graph.py

This PR fixes drop duplicates scalability by removing apply which does serial processing. 
**Benchmark Data**
```python
n_nodes = 100_000 
n_rows  = 1_500_000
df = cudf.DataFrame({'src':cp.random.randint(0,n_nodes,n_rows),
'dst':cp.random.randint(0,n_nodes,n_rows)})
```
**### After PR:**
```python
17.8 ms ± 536 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
**### Before PR:**
```python
26.3 s ± 78.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

[REVIEW] Optimize has_duplicate_edges 

---

python/cugraph/cugraph/gnn/graph_store.py
python/cugraph/cugraph/tests/test_graph_store.py

This PR enables https://github.com/rapidsai/dgl/pull/14  by adding the following functions/classes to CuGraphStore:
1. add_node_data
2. add_edge_data
3. get_node_storage
4. get_edge_storage
5. CuFeatureStorage

[REVIEW]Add get_node_storage and get_edge_storage to CuGraphStorage

---

cpp/include/cugraph/utilities/device_comm.cuh
cpp/src/prims/update_edge_partition_src_dst_property.cuh
cpp/src/structure/graph_impl.cuh

Dependent on https://github.com/rapidsai/raft/pull/742
Place multiple broadcast operations inside ncclGroupStart and ncclGroupEnd wrappers to improve performance.

Enable concurrent broadcasts in update_edge_partition_minor_property()

---

python/cugraph/cugraph/__init__.py

A breaking change in 22.06 moved the functionalities of `comms` to `cugraph/dask` where it should belong as it is only part of the multi GPU API. However `cugraph/__init__.py` is still importing the the comms when it shouldn't.
This PR removes the `comms` import in `cugraph/__init__.py `
closes #2379
closes #2329

Remove the comms import from cugraph's init file

---

cpp/CMakeLists.txt
cpp/include/cugraph/algorithms.hpp
cpp/include/cugraph_c/sampling_algorithms.h
cpp/src/c_api/random_walks.cpp
cpp/src/sampling/random_walks_mg.cu
cpp/src/sampling/random_walks_sg.cu
cpp/tests/CMakeLists.txt
cpp/tests/c_api/mg_random_walks_test.c
cpp/tests/c_api/sg_random_walks_test.c
cpp/tests/sampling/mg_random_walks_test.cu
cpp/tests/sampling/sg_random_walks_test.cu

This PR defines the API for MG random walk in the C API and the C++ API.
C and C++ tests are defined, although some of the code is ifdef'ed out since there is not a working implementation here.

Define API for MG random walk

---

cpp/include/cugraph/detail/decompress_edge_partition.cuh
cpp/src/sampling/uniform_neighbor_sampling_impl.hpp
cpp/tests/c_api/uniform_neighbor_sample_test.c

Uniform neighbor sampling isn't working properly with fanout specifying -1.
The `partially_decompress_edge_partition_to_fill_edgelist` function didn't handle SG properly.
closes #2425

fix handling of fanout == -1

---

cpp/CMakeLists.txt
cpp/tests/CMakeLists.txt

Close #2442 
We no longer use OpenMP in cuGraph. Remove code segments searching for OpenMP.

Remove OpenMP dependencies from CMake

---

python/cugraph/cugraph/structure/property_graph.py
python/cugraph/cugraph/tests/test_property_graph.py

See: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
This implementation requires column names to be strings, which is hopefully fine (but could be changed).
The downside is that this sometimes copies data when unnecessary.  It's pretty hard to know when objects are views or not when using public APIS.  Pandas objects have a `._is_view` attribute that tell us this.  I don't know about cugraph, or if this is even an issue in cugraph.
CC @rlratzel

Fix pandas SettingWithCopyWarning, which really shouldn't be ignored.

---

python/cugraph/cugraph/dask/structure/mg_property_graph.py
python/cugraph/cugraph/structure/property_graph.py
python/cugraph/cugraph/tests/test_property_graph.py

Fixes #2459
The tests already specify the use of directed graphs most places, so this required minimal changes.

Change default return type `PropertyGraph.extract_subgraph() -> cugraph.Graph(directed=True)`

---

cpp/tests/CMakeLists.txt

Guard the compilation of cugraphmgtestutil to only happen when BUILD_CUGRAPH_MG_TESTS is enabled so you can build a subset of tests without MPI

Only build cugraphmgtestutil when requested

---

python/cugraph/CMakeLists.txt
python/pylibcugraph/CMakeLists.txt

These typos would prevent properly handling required CMake features as determined by `rapids_cuda_init_architectures`. This only affects compilations where `FIND_CUGRAPH_CPP=OFF`.

Fix typos in Python CMakeLists CUDA arch file

---

conda/environments/cugraph_dev_cuda11.2.yml
conda/environments/cugraph_dev_cuda11.4.yml
conda/environments/cugraph_dev_cuda11.5.yml
conda/recipes/cugraph/meta.yaml

This PR pins `dask` & `distributed` to `2022.7.1` for `22.08` release.
xref: https://github.com/rapidsai/cudf/pull/11433

[REVIEW] Pin `dask` & `distributed` for release

---

python/cugraph/cugraph/gnn/graph_store.py
python/cugraph/cugraph/tests/test_bfs.py
python/cugraph/cugraph/tests/test_connectivity.py
python/cugraph/cugraph/tests/test_graph_store.py
python/cugraph/cugraph/tests/test_sssp.py

This PR switches `cugraphstore` to use  uniform neighbor sampling. 
Opening this in favor of https://github.com/rapidsai/cugraph/pull/2426

[REVIEW]Uniform neighbor sample 

---

python/cugraph/cugraph/cores/k_core.py

closes #2505 
`cugraph.k_core()` will check if the input graph is directed or undirected. If directed, the method will raise a `ValueError`, specifying that the input must be an undirected instance.

Update `k_core.py` to Check for Graph Direction

---

docs/cugraph/source/conf.py

This PR switches the loading of `custom.js` to defer because we will need the entire page to be loading until the methods in this script can even execute correctly.
xref: https://github.com/rapidsai/cudf/pull/11465

[REVIEW] Defer loading of `custom.js`

---

conda/environments/cugraph_dev_cuda11.2.yml
conda/environments/cugraph_dev_cuda11.4.yml
conda/environments/cugraph_dev_cuda11.5.yml
conda/recipes/cugraph/meta.yaml

This PR unpins `dask` & `distributed` for `22.10` development.
xref: https://github.com/rapidsai/cudf/pull/11492

[REVIEW] Unpin `dask` and `distributed` for development

---

python/cugraph/cugraph/gnn/graph_store.py
python/cugraph/cugraph/tests/test_graph_store.py

This PR fixes https://github.com/rapidsai/cugraph/issues/2520
**Speedup Details**
We see a 2.6x speedup , ranging from 0.8x to 10x. 
**Benchmarking Gist:**
Benchmark Link: https://gist.github.com/VibhuJawa/38da2f151141c0582a0532a364458602                                                                                                                                                                                        
**Benchmarking Table:**
| dataset     | fanout | seednodes | PR cugraph\_t (ms) | Main cugraph\_t (ms) | Speedup      |
| ----------- | ------ | --------- | ------------------ | -------------------- | ------------ |
| livejournal | 5      | 6400      | 9.77469367         | 36.14                | 3.697743722  |
| livejournal | 5      | 12800     | 10.24105188        | 37.04 …

[REVIEW]  Use edge_ids directly in uniform sampling call to prevent cost of edge_id lookup

---

cpp/tests/c_api/mg_louvain_test.c

Add extra logic to support arbitrary numbering of clusters.
Our Louvain implementation is deterministic based on the number of GPUs (that is, with k GPUs and a given graph it will always generate the same answer).  However, in the case of this test a different number of GPUs can generate a different result based on how the vertices are numbered.
We could unrenumber the result, but that's an extra step that's not necessary in the ordinary flow.  Added a more sophisticated test that will recreate the necessary subset of the number map and validate according to that.

Fix MG Louvain C API test 

---

ci/cpu/build.sh
conda/recipes/cugraph/meta.yaml
python/cugraph/cugraph/dask/cores/core_number.py
python/cugraph/cugraph/dask/link_analysis/pagerank.py
python/cugraph/cugraph/dask/sampling/uniform_neighbor_sample.py
python/cugraph/cugraph/dask/traversal/bfs.py

Dask doesn't always release some of the inactive futures fast enough. This can be problematic when running the same `algo` several times with the same `PLC graph` because those futures can be cache in the next iteration causing a hang if some get released midway.
This PR manually delete inactive futures.
closes #2568

Fix MG PLC algos intermittent hang

---

python/cugraph/cugraph/tests/mg/test_mg_pyg_extensions.py

This PR will correct an error that shows up occasionally in the MG tests, especially when running on an odd number of GPUs.  This error is related to issue #2665 and resolves it temporarily while the C++ team works on a permanent fix.

Small fix to the MG PyG Test to Account for Current Sampling Behavior

---

cpp/include/cugraph_c/community_algorithms.h
cpp/src/c_api/louvain.cpp
cpp/tests/c_api/louvain_test.c

The C API defined for Louvain was missing the modularity score.  Add the modularity score to the result and add an accessor that allows the modularity score to be accessed.

Add modularity to return result for louvain

---

python/cugraph/cugraph/dask/structure/mg_property_graph.py
python/cugraph/cugraph/structure/property_graph.py
python/cugraph/cugraph/tests/mg/test_mg_property_graph.py
python/cugraph/cugraph/tests/test_property_graph.py

Closes #2627 and CC @VibhuJawa 
Currently only SG as we hammer out the API and behavior.
This returns a dataframe with start and stop for each type.  Should stop be inclusive or exclusive?
How should we handle vertex ids that only exist in edge data?  Should we raise (for now) if this condition exists?  I think we can handle this without _too_ much difficulty, but it will take more work.
Since we number edge data, I think edge IDs will often be added in a way that is already contiguous per type.  We could keep track of this to avoid unnecessary computation.
Also, I want to confirm that we _cannot_ have multiple rows for a single vertex ID, right?  I think we settled on this.  Multiple rows with the same ID would cause a problem with the current implementation--it currently gives each row …

Renumber PG to be contiguous per type

---

python/cugraph/cugraph/dask/structure/mg_property_graph.py
python/cugraph/cugraph/structure/property_graph.py
python/cugraph/cugraph/tests/mg/test_mg_property_graph.py
python/cugraph/cugraph/tests/test_property_graph.py

Closes #2692.
Currently SG only.  ~MG version coming shortly!~  MG version done.

PG allow get_vertex_data to accept single type or id

---

python/cugraph/cugraph/structure/number_map.py
python/cugraph/cugraph/testing/utils.py
python/cugraph/cugraph/tests/mg/test_mg_doctests.py
python/cugraph/cugraph/tests/mg/test_mg_renumber.py

fixes #2686 
* Moved assignment of a variable that sets a dtype to a point _after_ the mappings from vertex strings to integer IDs are applied in order to capture the correct dtype of the internal dataframes. This bug was not detected earlier since integer vertex IDs had matching dtypes before and after any initial mappings were applied, and there was no test coverage for MG string vertex IDs.
* Added test that uses a graph containing string vertex IDs then runs `pagerank` using both SG and MG versions and ensures the results are identical.  This new test was based on the code provided in issue #2686 
* Fixed several bugs in MG test code that prevented `pytest` from collecting tests when the entire `mg` suite was specified. This probably would have been uncovered sooner if the MNMG …

Fixes bug in `NumberMap` preventing use of string vertex IDs for MG graphs

---

python/cugraph/cugraph/tests/test_triangle_count.py

closes https://github.com/rapidsai/cugraph/issues/2615
closes https://github.com/rapidsai/cugraph/issues/2616
replaces #2626 which was closed

added tests for triangle count on unweighted graphs and graphs with int64 vertex types 

---

conda/environments/cugraph_dev_cuda11.5.yml
python/cugraph/cugraph/__init__.py
python/cugraph/cugraph/dask/common/input_utils.py
python/cugraph/cugraph/dask/common/mg_utils.py
python/cugraph/cugraph/dask/comms/comms.py

This PR updates the way `raft` is imported following changes on the `raft` new conda packages.
closes #2727

Update raft import

---

conda/environments/cugraph_dev_cuda11.2.yml
conda/environments/cugraph_dev_cuda11.4.yml
conda/environments/cugraph_dev_cuda11.5.yml
conda/recipes/cugraph/meta.yaml
conda/recipes/libcugraph/meta.yaml
conda/recipes/pylibcugraph/meta.yaml
cpp/CMakeLists.txt
cpp/cmake/thirdparty/get_raft.cmake
cpp/src/community/legacy/spectral_clustering.cu
python/cugraph/CMakeLists.txt
python/pylibcugraph/CMakeLists.txt

Closes #2678 
raft updated some k-means logic and dramatically increased the compile time of our spectral clustering implementation.  This PR adds an include that will suppress the expansion of templates that we are not using.

suppress expansion of unused raft spectral templates

---

cpp/src/community/legacy/extract_subgraph_by_vertex.cu
cpp/src/components/legacy/weak_cc.cuh
cpp/src/generators/generator_tools.cu
cpp/src/linear_assignment/hungarian.cu
cpp/src/prims/per_v_transform_reduce_incoming_outgoing_e.cuh
cpp/src/prims/property_op_utils.cuh
cpp/src/sampling/random_walks.cu
cpp/src/sampling/random_walks.cuh
cpp/src/sampling/rw_traversals.hpp
cpp/src/serialization/serializer.cu
cpp/src/structure/detail/structure_utils.cuh
cpp/src/structure/graph_impl.cuh
cpp/src/structure/legacy/graph.cu
cpp/src/traversal/legacy/mg/common_utils.cuh
cpp/src/tree/mst.cu
cpp/src/utilities/graph_utils.cuh
cpp/tests/structure/streams.cu

Fix warnings due to recent raft deprecation and more.

Fix cuGraph compile-time warnings.

---

python/cugraph/cugraph/dask/sampling/uniform_neighbor_sample.py
python/cugraph/cugraph/tests/mg/test_mg_uniform_neighbor_sample.py

Resolves a critical bug where the whole start list was sent to every vertex resulting in duplicate samples.
Closes #2760

[BUG] Properly Distribute Start Vertices for MG Uniform Neighbor Sample

---

ci/release/update-version.sh

This PR adds `raft-dask` & `pylibraft` to `update-version.sh`

[REVIEW] Add missing entries in `update-version.sh`

---

cpp/CMakeLists.txt
cpp/src/link_prediction/jaccard_impl.cuh
cpp/src/link_prediction/overlap_impl.cuh
cpp/src/link_prediction/similarity_impl.cuh
cpp/src/link_prediction/sorensen_impl.cuh
cpp/src/prims/per_v_pair_transform_dst_nbr_intersection.cuh
cpp/tests/link_prediction/mg_similarity_test.cpp
cpp/tests/link_prediction/similarity_compare.cpp
cpp/tests/link_prediction/similarity_compare.hpp
cpp/tests/link_prediction/similarity_test.cpp
cpp/tests/prims/mg_per_v_pair_transform_dst_nbr_intersection.cu
cpp/tests/utilities/test_utilities.hpp

Closes #2543 
Implements unweighted similarity algorithms using the new primitive defined in #2728.
Weighted implementations will be tracked by issue #2749

C++ implementation for unweighted Jaccard/Sorensen/Overlap

---

ci/cpu/build.sh

When building `main` and `INSTALL_DASK_MAIN=0` results in removing the `dask/label/dev` twice which fails on the second one. This change prevents this behavior.

REL Fix main branch builds

---

cpp/CMakeLists.txt
cpp/include/cugraph/algorithms.hpp
cpp/include/cugraph/edge_partition_device_view.cuh
cpp/src/components/weakly_connected_components_impl.cuh
cpp/src/prims/transform_reduce_v_frontier_outgoing_e_by_dst.cuh
cpp/src/prims/vertex_frontier.cuh
cpp/src/traversal/k_hop_nbrs_impl.cuh
cpp/src/traversal/k_hop_nbrs_mg.cu
cpp/src/traversal/k_hop_nbrs_sg.cu
cpp/tests/CMakeLists.txt
cpp/tests/traversal/k_hop_nbrs_test.cpp
cpp/tests/traversal/mg_k_hop_nbrs_test.cpp
cpp/tests/utilities/device_comm_wrapper.cu

K-hop neighbors implementation (mainly to support 2-hop neighbors).

K-hop neighbors

---

cpp/tests/CMakeLists.txt
cpp/tests/community/mg_louvain_test.cpp
cpp/tests/link_analysis/mg_pagerank_test.cpp
cpp/tests/link_analysis/pagerank_test.cpp
cpp/tests/structure/graph_test.cpp
cpp/tests/structure/renumbering_test.cpp
cpp/tests/utilities/csv_file_reader.cpp
cpp/tests/utilities/csv_file_utilities.cu
cpp/tests/utilities/matrix_market_file_utilities.cu
cpp/tests/utilities/test_graphs.hpp
cpp/tests/utilities/test_utilities.hpp
cpp/tests/utilities/thrust_wrapper.cu
cpp/tests/utilities/thrust_wrapper.hpp

Clean-up the C++ test graph generation code and add a minimal C++ CSV (this can read edge lists only in a strict format this reader is expecting) reader.
The CSV reader is added to support edge list with non-stand vertex IDs (e.g. negative vertex IDs).

C++ minimal CSV reader

---

.git-blame-ignore-revs
python/cugraph/cugraph/structure/graph_implementation/simpleGraph.py

closes #2808 
* Adds `.git-blame-ignore-revs` for recent .py files reformatting by `black`
* Minor change to improve an exception message, realized after seeing [this log](https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci/job/cugraph/job/prb/job/cugraph-gpu-test/CUDA=11.2,GPU_LABEL=driver-450,LINUX_VER=centos7,PYTHON=3.8/2361/testReport/junit/cugraph.tests/test_egonet/test_ego_graph_nx_1_0_graph_file0_/).

Adds `.git-blame-ignore-revs` for recent .py files reformatting by `black`

---

cpp/include/cugraph/utilities/cython.hpp
cpp/src/utilities/cython.cu
python/cugraph/cugraph/structure/graph_utilities.pxd

`populate_graph_container_legacy` & `random_walks_to_coo` are no longer used.

Delete dead code in cython.cu

---

CHANGELOG.md
ci/cpu/build.sh
ci/docs/build.sh

Forward-merge triggered by push to `branch-22.10` that creates a PR to keep `branch-22.12` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-22.10 to branch-22.12 [skip gpuci]

---

cpp/src/community/detail/common_methods.cuh
cpp/src/prims/per_v_transform_reduce_incoming_outgoing_e.cuh
cpp/src/prims/transform_reduce_e_by_src_dst_key.cuh

transform_reduce_e_by_src|dst_key is updated to take an additional input parameter (ReduceOp reduce_op).
Marked as non-breaking as primitives are currenlty not part of the public API (located in src/prims).

Updte transform_reduce_e_by_src|dst_key to take a custom reduction op

---

python/cugraph/cugraph/structure/property_graph.py
python/cugraph/cugraph/tests/test_dataset.py
python/cugraph/cugraph/tests/test_property_graph.py

@alexbarghi-nv want to give this a try?  I previously made these changes to MG (was there an issue for it?), but not SG.

Fix concat with different index dtypes in SG PropertyGraph

---

cpp/src/c_api/uniform_neighbor_sampling.cpp
python/pylibcugraph/pylibcugraph/tests/test_neighborhood_sampling.py

Fix memory leak in uniform neighborhood sampling.  Earlier updates adjusted the results but didn't fix the free method.
Closes #2788

Fix uniform neighborhood sampling memory leak

---

.github/workflows/add-to-project.yml

This PR adds a small GitHub Action to automatically add all issues and PRs created in cuGraph to the tracking project.
Closes #2604

GitHub Action adding issues/prs to project board

---

python/cugraph/cugraph/dask/traversal/bfs.py
python/cugraph/cugraph/structure/number_map.py
python/cugraph/cugraph/tests/mg/test_mg_renumber.py

The `global_id` column representing the renumbered `edgelist` are of type int64 by default and this is problematic if the user's input dataframe is of type `int32`. 
This PR:
1. Ensures the renumbered edgelist matches the original edgelist `dtype `unless non integers vertices are provided.
2. Add tests verifying the above.
3. Ensures the `source`'s `dtype` in `BFS` matches edgelist `dtype`.
closes #2845 
close #2846

Ensure correct data type

---

docs/cugraph/source/basics/cugraph_cascading.md

Created a markdown file that explains the cuGraph stance on method cascading.
This is in response to both issues, direct messages, and stack overflow questions. 
It might be easier to review the page by looking at:  https://github.com/BradReesWork/cugraph/blob/22.12-cascade-doc/docs/cugraph/source/basics/cugraph_cascading.md

Create a page on why we do not support cascading

---

ci/gpu/build.sh
ci/test.sh
conda/environments/cugraph_dev_cuda11.2.yml
conda/environments/cugraph_dev_cuda11.4.yml
conda/environments/cugraph_dev_cuda11.5.yml
python/cugraph/cugraph/structure/graph_primtypes.pyx
python/cugraph/cugraph/tests/mg/test_mg_uniform_neighbor_sample.py
python/cugraph/cugraph/tests/test_uniform_neighbor_sample.py

A breaking `pytest `change removed the `py` package from its list of dependencies causing the SG/MG tests to fail.
This PR  adds the package to our list of dependencies. 
In addition to the above, this PR also:
1. Reduces the value of the `fanout_vals` when testing `uniform_neighbor_sampling`
2. Updates the ownership transfer of `device_buffer_unique_ptr` to cuDF buffer through the call `as_buffer()`
closes #2857 
closes #2881

Add package to the list of dependencies

---

cpp/include/cugraph/edge_src_dst_property.hpp
cpp/src/prims/transform_reduce_e_by_src_dst_key.cuh

- Add view_concat for edge_minor_property_view_t 
- update transform_reduce_e_by_dst_key to support reduce_ops on tuple types
closes #2878

Add view_concat for edge_minor_property_view_t and update transform_reduce_e_by_dst_key to support reduce_op on tuple types

---

python/cugraph/CMakeLists.txt
python/cugraph/cugraph/centrality/CMakeLists.txt
python/cugraph/cugraph/community/CMakeLists.txt
python/cugraph/cugraph/components/CMakeLists.txt
python/cugraph/cugraph/cores/CMakeLists.txt
python/cugraph/cugraph/dask/centrality/CMakeLists.txt
python/cugraph/cugraph/dask/comms/CMakeLists.txt
python/cugraph/cugraph/dask/components/CMakeLists.txt
python/cugraph/cugraph/dask/structure/CMakeLists.txt
python/cugraph/cugraph/generators/CMakeLists.txt
python/cugraph/cugraph/internals/CMakeLists.txt
python/cugraph/cugraph/layout/CMakeLists.txt
python/cugraph/cugraph/linear_assignment/CMakeLists.txt
python/cugraph/cugraph/link_prediction/CMakeLists.txt
python/cugraph/cugraph/sampling/CMakeLists.txt
python/cugraph/cugraph/structure/CMakeLists.txt
python/cugraph/cugraph/tree/CMakeLists.txt
python/cugraph/cugraph/utilities/CMakeLists.txt
python/pylibcugraph/CMakeLists.txt
python/pylibcugraph/pylibcugraph/CMakeLists.txt
python/pylibcugraph/pylibcugraph/components/CMakeLists.txt
python/pylibcugraph/pylibcugraph/internal_types/CMakeLists.txt
python/pylibcugraph/pylibcugraph/raft/common/CMakeLists.txt
python/pylibcugraph/pylibcugraph/testing/CMakeLists.txt

The new functionality creates a single source of truth defining the location at which a library will be, allowing rapids-cmake to handle the necessary relative paths in the RPATH and avoiding the current error-prone approach that requires each CMakeLists.txt to correctly assign the relative path.

Use new rapids-cmake functionality for rpath handling.

---

README.md
ci/benchmark/build.sh
conda/environments/cugraph_dev_cuda11.2.yml
conda/environments/cugraph_dev_cuda11.4.yml
conda/environments/cugraph_dev_cuda11.5.yml
conda/recipes/cugraph/meta.yaml
conda/recipes/libcugraph/meta.yaml
conda/recipes/pylibcugraph/meta.yaml
conda_build.sh

This should resolve a segfault we are seeing with `cuda-python=11.7.0` (https://github.com/rapidsai/cudf/issues/11941).

[HOTFIX] Update cuda-python dependency to 11.7.1

---

cpp/tests/CMakeLists.txt
cpp/tests/centrality/betweenness_centrality_validate.cu

I found two errors when building locally that this PR fixes.
- The cugraph test util target relies on gtest headers but doesn't use the `GTest::gtest` target. This works in CI due to the conda env placing the GTest headers in a directory found by other `-I`
- The `cpp/tests/centrality/betweenness_centrality_validate.cu` test uses the wrong `nearly_equal` function which fails due to calling a host only function from a device/host function.

Correct build failures when doing a local build

---

cpp/src/c_api/core_number.cpp
cpp/src/structure/transpose_graph_impl.cuh
cpp/src/structure/transpose_graph_storage_impl.cuh
cpp/tests/c_api/weakly_connected_components_test.c

The `tranpose_storage` function was incorrectly setting graph properties.

Fix bug in how is_symmetric is set when transposing storage

---

cpp/include/cugraph_c/graph_functions.h
cpp/src/c_api/graph_functions.cpp
cpp/src/c_api/graph_functions.hpp
cpp/src/c_api/graph_helper.cu
cpp/tests/CMakeLists.txt
cpp/tests/c_api/mg_two_hop_neighbors_test.c
cpp/tests/c_api/two_hop_neighbors_test.c

Implements the two hop neighbors C API using the k_hop_nbrs algorithm.
This should unblock #2704

Implement two_hop_neighbors C API

---

python/cugraph/cugraph/dask/structure/mg_property_graph.py
python/cugraph/cugraph/structure/property_graph.py
python/cugraph/cugraph/tests/test_property_graph.py

This PR fixes #2903  . 
We reduce the memory foot print by  `3.5x` and speeds up the add_data by `557x` and also allows us to not be limited in the size of edges we can save.  (Time is in seconds vs ms) 
Before PR:
```python3
Name (time in s, mem in bytes)       Mean                  GPU mem            GPU Leaked mem            Rounds            GPU Rounds          
----------------------------------------------------------------------------------------------------------------------------------------------
bench_add_edge_data[15000000]      2.3044 (1.0)      2,160,000,064 (1.0)                   0 (1.0)           1           1
bench_add_edge_data[30000000]      4.7941 (2.08)     4,320,000,064 (2.00)                  0 (1.0)           1           1
bench_add_edge_data[60000000]      8.7235 …
```

[REVIEW] Optimize  `PG.add_data`

---

cpp/src/community/egonet_impl.cuh
cpp/src/structure/decompress_to_edgelist_impl.cuh
cpp/tests/CMakeLists.txt
cpp/tests/community/mg_egonet_test.cu

@jnke2016 identified some issues while creating the python bindings for egonet.  This PR addresses issues found while testing MG egonet in different MG configurations.

Debug MG egonet issues

---

build.sh

closes #2934 
Fixes options added to build.sh for building without cugraph-ops that were dropped in a merge mistake.

[BUG] Fixes options added to build.sh for building without cugraph-ops that were dropped in a merge mistake.

---

build.sh

Forward-merge triggered by push to `branch-22.12` that creates a PR to keep `branch-23.02` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

[gpuCI] Forward-merge branch-22.12 to branch-23.02 [skip gpuci]

---

.gitignore

Resolves #2947 
Excludes egg files from git.  Previously, only egg files in a certain directory were excluded.  This broadens the exclusion to the whole repository.

Update gitignore to Exclude Egg Files

---

python/cugraph-service/scripts/default-config.sh
python/cugraph-service/scripts/run-dask-process.sh
python/cugraph-service/tests/test_mg_e2e.py

This PR fixes  cluster startup script

[REVIEW] Fix cluster startup script

---

docs/cugraph/source/api_docs/property_graph.rst
python/pylibcugraph/pylibcugraph/utilities/api_tools.py

closes #3006 
* Updated experimental warning wrapper to also pass-through __doc__ attr
* Updated PropertyGraph doc .rst file to use the proper experimental namespace.

Updates experimental warning wrapper and PropertyGraph docs for correct experimental namespace name

---

.github/workflows/wheels.yml
python/cugraph/cugraph/dask/cores/k_core.py

We need to install dask-cuda from source during wheel builds for cugraph CI to pass because dask evolves too fast to pin. We also don't want to build wheels on every PR, so we'll need that disabled. I'll make that change once I confirm that wheel builds pass tests here.
This PR also fixes an unrelated issue causing doctests to fail. I'm guessing that because the docstring is in tests/mg it isn't being discovered during conda gpuCI because we exclude that directory from the pytest command in ci/test.sh.

Update dask-cuda version and disable wheel builds in CI

---

python/cugraph/CMakeLists.txt
python/pylibcugraph/CMakeLists.txt

This is necessary because our dependencies are pulling in the CUDA language.

Initialize CUDA architectures for all Python cugraph builds

---

python/pylibcugraph/pylibcugraph/internal_types/CMakeLists.txt
python/pylibcugraph/pylibcugraph/testing/CMakeLists.txt

pylibcugraph is currently linking to the `cugraph_c` target directly rather than via the exported alias `cugraph::cugraph_c`. I am unsure under exactly what circumstances the former should be working, but I don't think it is reliable. I see failures locally without the change. I have currently made this PR into 22.12 because it seems like an important fix, but I can push it to 23.02 if needed.

Fix cugraph_c target name in Python builds

---

python/cugraph-service/tests/test_remote_graph.py

closes #3050 
Docker image builds that include `cugraph-service` but do/can not include `cugraph-pyg` are blocked since they cannot run cugraph-service tests.  This PR allows those builds to skip the tests that use the cugraph-pyg feature and avoid the import of `cugraph_pyg`

[HOTFIX] Makes `cugraph-pyg` an optional depenency for `cugraph-service` tests

---

build.sh
conda/environments/cugraph_dev_cuda11.2.yml
conda/environments/cugraph_dev_cuda11.4.yml
conda/environments/cugraph_dev_cuda11.5.yml
conda/environments/cugraph_dev_cuda11.6.yml

When building using build.sh we should allow the installation to find packages that have already been installed into the environment. This is crucial if users are installing multiple RAPIDS from source, for instance.

Always build without isolation

---

build.sh
conda/environments/cugraph_dev_cuda11.2.yml
conda/environments/cugraph_dev_cuda11.4.yml
conda/environments/cugraph_dev_cuda11.5.yml
conda/environments/cugraph_dev_cuda11.6.yml
python/cugraph-service/server/setup.py
python/pylibcugraph/pylibcugraph/egonet.pyx
python/pylibcugraph/pylibcugraph/testing/utils.py
python/pylibcugraph/setup.py

closes #3064 
closes #3057 
* Removed unused testing code that caused a `cudf` dependency
* Updated setup.py to remove cudf dependency
* Minor update to docstring to not specify cudf type
* Changed `cupy` dependency in `cugraph-service-server` to match the `cupy-cuda11x` dependency in `cugraph`
* Updated conda environment .yml files to add cupy
Note that the `pylibcugraph.testing` package is part of every install, and therefore any dependencies added to `testing` will cause all users to require them. The separate `extras_requires` are optional dependencies, in this case for running the unit tests. Some unit tests still use `cudf`, so cudf should be in `extras_require` and not `install_requires` since the ability to run the separate unit tests is optional.

[HOTFIX] Removed unused testing code that caused a cudf dependency

---

conda/recipes/cugraph-pyg/meta.yaml
conda/recipes/cugraph-service/meta.yaml
conda/recipes/cugraph/meta.yaml

This PR includes the following changes:
- Uses `pin_subpackage` to specify the relationship between `cugraph-service-client` and `cugraph-service-server`
- Switches the `cugraph` dependency to use a regular version specifier since `pin_compatible` and `pin_subpackage` aren't applicable since `cugraph` is built in a different recipe
These changes are necessary because `pin_compatible` only works with dependencies that are listed in the `build`/`host` section of a given package ([relevant conda docs](https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html#extra-jinja2-functions)).
Additionally: 
- the `cudatoolkit` package has been removed from the `run` dependencies since it's not explicitly used in `cugraph-pyg` and comes in transitively through the other dependencies …

Update `cugraph` recipes

---

.github/workflows/pr.yaml
conda/environments/all_cuda-115_arch-x86_64.yaml
dependencies.yaml

This PR contains fixes for some things I missed in #3095.
Specifically:
- Adds the `conda-notebook-tests` job as a dependency of the `pr-builder` job
- Removes a duplicate `notebook` dependency from `dependencies.yaml`

GH Actions Notebook Testing Fixes

---

ci/test_notebooks.sh
ci/test_python.sh
conda/environments/all_cuda-115_arch-x86_64.yaml
dependencies.yaml

This PR TEMPORARILY allows python and notebook tests that return exit code 139 to pass.
This allows CI to pass for PRs that are failing with 139 on exit, due to a bug that exists that results in a Seg Fault on exit, which is blocking all other PRs.  An example can be seen [here](https://github.com/rapidsai/cugraph/actions/runs/3852570263/jobs/6565471015).
This will be reverted ASAP!
Note that failing pytest tests result in return codes of something other than 139, so PRs that fail tests for reasons other than a Seg Fault will still be blocked from merging.  This also does not apply to C++ tests.

TEMPORARILY allows python and notebook tests that return exit code 139 to pass.

---

conda/environments/all_cuda-115_arch-x86_64.yaml
dependencies.yaml
python/cugraph/cugraph/tests/generators/test_rmat.py
python/cugraph/cugraph/tests/test_betweenness_centrality.py
python/cugraph/cugraph/tests/test_bfs.py
python/cugraph/cugraph/tests/test_convert_matrix.py
python/cugraph/cugraph/tests/test_edge_betweenness_centrality.py
python/cugraph/cugraph/tests/test_graph.py
python/cugraph/cugraph/tests/test_hungarian.py
python/cugraph/cugraph/tests/test_paths.py
python/cugraph/cugraph/traversal/sssp.py

Closes #3084 and mostly takes care of #3068 (I didn't update `PendingDeprecationWarning`s that originate from `cugraph`).
Old versions of NetworkX should continue to work.
I ran the tests (and many--but not all--of the notebooks) with `-Werror::DeprecationWarning` to uncover issues.
`tornado` warns `DeprecationWarning: make_current is deprecated; start the event loop first`, which originate from their code. They deprecated it, but didn't update their code yet, so I updated the tests to ignore it.

Update to support NetworkX 3.0 (and handle other deprecations)

---

cpp/cmake/thirdparty/get_cuhornet.cmake

Updates cuhornet to include these fixes:
- https://github.com/rapidsai/cuhornet/pull/60
- https://github.com/rapidsai/cuhornet/pull/61
Needed to unblock `spdlog` / `fmt` changes in `rapids-cmake` and `rmm`.

Update cuhornet to fix `using namespace rmm;`.

---

cpp/cmake/thirdparty/get_cuhornet.cmake

Forward-merge triggered by push to `branch-23.02` that creates a PR to keep `branch-23.04` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

Forward-merge branch-23.02 to branch-23.04

---

python/pylibcugraph/pylibcugraph/raft/common/handle.pxd

This PR updates the Cython libraft exports to match the header structure from https://github.com/rapidsai/raft/pull/1140.

Import handle from core

---

python/cugraph/cugraph/dask/sampling/uniform_neighbor_sample.py
python/cugraph/cugraph/tests/test_uniform_neighbor_sample.py

In multi client environments our sampling algorithms tend to hang, this PR adds a lock to prevent that from happening.  This PR closes https://github.com/rapidsai/cugraph/issues/3186
See [notebooks](https://gist.github.com/VibhuJawa/1b705427f7a0c5a2a4f58e0a3e71ef21) here with MRE to reproduce. 
Before PR (HANG): 
After PR (NO HANG): 
I have not added tests for this here because mocking dask with multi client environment is not possible in CI yet so we will do this as future work. 
Also includes a bug fix in our sampling code path.

[FEA] Enable using cugraph uniform sampling in multi client environments

---

python/cugraph/cugraph/dask/structure/mg_property_graph.py
python/cugraph/cugraph/tests/mg/test_mg_property_graph.py

Drop extraneous columns that were appearing in MGPropertyGraph

---

python/cugraph/_custom_build/backend.py
python/cugraph/setup.py
python/pylibcugraph/_custom_build/backend.py
python/pylibcugraph/setup.py

We introduced a change to pin RAPIDS wheel dependencies to the same release version. However, branch 23.04 was created before that last PR was merged, so as of now cugraph's 23.4 wheels are installing 23.2 RAPIDS dependencies. This PR updates those pins to the current release.
This should solve the error in #3160 (where the old pylibcugraph-cu11==23.2 is being pulled in the test step as opposed to the desired 23.4 version).

Bump pinned pip wheel deps to 23.4

---

cpp/CMakeLists.txt

We migrated away from using cuBLAS as we've moved to the primitive implementation.  It is no longer used, not sure how long it hasn't been used.

Remove cublas from the link dependencies

---

.github/workflows/pr.yaml

This reverts #3267. I realized after filing that PR that ARM smoke tests were spending extra time and bandwidth fetching datasets that they don’t use. I am reverting that change in favor of a comment explaining why ARM builds can skip fetching the datasets.
Context: https://github.com/rapidsai/cugraph/pull/3267#issuecomment-1427076608

Disable dataset downloads in ARM smoke tests.

---

.github/workflows/pr.yaml
.pre-commit-config.yaml

This change allows local and remote runs to handle calls to dfg identically, and removes the need for a separate CI check.

Add dfg as a pre-commit hook.

---

python/cugraph/cugraph/__init__.py

This PR removes an unused raft import which was causing an `ImportError` due to it being recently relocated in the RAFT namespace.

Remove unused RAFT import causing `ImportError`

---

conda/recipes/cugraph/meta.yaml
conda/recipes/libcugraph/meta.yaml
conda/recipes/pylibcugraph/meta.yaml

This PR ensures that the `AWS_SESSION_TOKEN` and `SCCACHE_S3_USE_SSL` environment variables are passed to our conda build process.
`AWS_SESSION_TOKEN` is necessary in order to support using temporary credentials via AWS STS (we recently adopted this method in CI).
`SCCACHE_S3_USE_SSL` has been reported to increase cache performance for S3.

Pass `AWS_SESSION_TOKEN` and `SCCACHE_S3_USE_SSL` vars to conda build

---

ci/build_cpp.sh
ci/build_python.sh
ci/test_cpp.sh
ci/test_python.sh
conda/environments/all_cuda-118_arch-x86_64.yaml
conda/recipes/cugraph/meta.yaml
conda/recipes/libcugraph/meta.yaml
conda/recipes/pylibcugraph/meta.yaml
cpp/CMakeLists.txt
cpp/cmake/thirdparty/get_raft.cmake
cpp/src/community/legacy/spectral_clustering.cu
dependencies.yaml

Pleae note, this should not be merged until https://github.com/rapidsai/raft/pull/1333 is ready to be merged.

Updating cugraph to use consolidated libraft target

---

ci/build_cpp.sh
ci/build_python.sh
ci/test_cpp.sh
ci/test_python.sh
python/cugraph/cugraph/dask/comms/comms.py

A `dask` breaking change updates the way a worker is passed into the distributed function causing all the MG tests to fail.
This PR properly handles the change and also removes the temporary raft PR pinned in the `ci` shell script.

Properly handle dask change

---

cpp/libcugraph_etl/include/hash/concurrent_unordered_map.cuh
cpp/libcugraph_etl/src/renumbering.cu
cpp/tests/structure/streams.cu
cpp/tests/utilities/mg_utilities.cpp

Replace CUDA_TRY with RAFT_CUDA_TRY in three files.
Also replaced CHECK_CUDA with RAFT_CHECK_CUDA
https://github.com/rapidsai/raft/pull/1304 removed the old macros, we still had a few references.
Currently blocked by https://github.com/rapidsai/cugraph-ops/pull/448... once that is merged we should be able to finish building and merge this.

Replace CUDA_TRY with RAFT_CUDA_TRY

---

python/pylibcugraph/pylibcugraph/__init__.py

The `__version__` attribute appears to have been accidentally deleted in #2971.

Add back deleted version attribute

---

.github/workflows/pr.yaml
.github/workflows/test.yaml
ci/release/update-version.sh
conda/environments/all_cuda-118_arch-x86_64.yaml
dependencies.yaml

Looks like we failed to update the `update-version.sh` script to handle `libraft` instead of `libraft-distance` when we made the raft changes in 23.04.
This PR fixes that and updates the raft version to 23.06.

Update raft dependency to 23.06

---

python/cugraph/cugraph/dask/sampling/uniform_neighbor_sample.py
python/cugraph/cugraph/tests/sampling/test_uniform_neighbor_sample_mg.py

Currently, cudf does not merge series properly when they already share an index.  I'm not sure if this is a bug in cudf, or intentional behavior.  This issue does not occur with dask_cudf.  The resolution is to use `cudf.concat` when passing a `cudf.Series` for start vertices and batch ids, and `df.to_frame().merge` when passing in a `dask_cudf.Series` for start vertices and batch ids.
This PR also adds an additional test which tests both cudf and dask_cudf inputs to catch these sort of problems in the future.

[BUG] Critical: Force cudf.concat when passing in a cudf Series to MG Uniform Neighbor Sample

---

build.sh

https://github.com/rapidsai/rapids-cmake/commit/fb7033e8860594beb5b0351c204068c12f1d6a0a removed a deprecated feature that we were inadvertently still using.
This PR updates the second reference to `CMAKE_CUDA_ARCHITECTURES` as `ALL`

Fix issue with latest rapids-make

---

ci/release/update-version.sh
conda/environments/all_cuda-118_arch-x86_64.yaml
dependencies.yaml
docs/cugraph/source/api_docs/cugraph-ops/bipartite_operators.rst
docs/cugraph/source/api_docs/cugraph-ops/dimenet.rst
docs/cugraph/source/api_docs/cugraph-ops/fg_operators.rst
docs/cugraph/source/api_docs/cugraph-ops/graph_types.rst
docs/cugraph/source/api_docs/cugraph-ops/index.rst
docs/cugraph/source/api_docs/cugraph-ops/mfg_operators.rst
docs/cugraph/source/api_docs/cugraph-ops/pytorch.rst
docs/cugraph/source/api_docs/cugraph-ops/pytorch.rst.txt
docs/cugraph/source/api_docs/cugraph-ops/static_operators.rst
docs/cugraph/source/api_docs/index.rst
docs/cugraph/source/index.rst

The goal is to have a unified docs area for all graph work.  This PR is the first step in getting cugraph-ops included in the main graph doc area

adding cugraph-ops

---

cpp/src/prims/per_v_transform_reduce_incoming_outgoing_e.cuh

The initial value may not be applied to every vertex if we use (key, value) pairs to store edge src|dst property values (as we apply the initial value to the storage object storing edge (src, dst) property values, but when we use (key, value) pairs, the storage object does not store property values for the entire minor vertex range).

per_v_transform_reduce_incoming|outgoing_e bug fix (when we're using (key, value) pairs to store edge src|dst property values)

---

ci/test_python.sh
python/cugraph-dgl/cugraph_dgl/nn/conv/gatconv.py
python/cugraph-dgl/cugraph_dgl/nn/conv/relgraphconv.py
python/cugraph-dgl/cugraph_dgl/nn/conv/sageconv.py

DGL v1.1.0 introduced a breaking change that renames `adj_sparse` to `adj_tensors`, causing the following error in our CI:
```
nn/test_gatconv.py::test_gatconv_equality[False-None-1-False] - AttributeError: 'DGLGraph' object has no attribute 'adj_sparse'
nn/test_gatconv.py::test_gatconv_equality[False-None-1-True] - AttributeError: 'DGLBlock' object has no attribute 'adj_sparse'
```
This PR updates the usage in `cugraph-dgl` tests.
CC: @alexbarghi-nv

Update dgl APIs for v1.1.0

---

conda/environments/all_cuda-118_arch-x86_64.yaml
conda/recipes/libcugraph/conda_build_config.yaml
dependencies.yaml

This PR updates GTest pinnings to >=1.13.0. This aligns with recent changes in rapids-cmake: https://github.com/rapidsai/rapids-cmake/pull/401.

Update recipes to GTest version >=1.13.0

---

.github/workflows/build.yaml

The build workflow was not updated along with the pr workflow in #3525

Fix path to cugraphops in build workflow

---

thirdparty/LICENSES/LICENSE.cugraph-ops.NVIDIA

needed in cuGraph repo since cugraph-ops repo is private.  Need a spot that can be references until the EULA gets published

cugraph-ops license

---

cpp/libcugraph_etl/src/renumbering.cu

https://github.com/rapidsai/cudf/pull/13341 changed the constructors for `cudf::column`.
This PR updates the constructor calls to work with the latest cudf changes.

update cudf column constructor calls

---

notebooks/README.md
notebooks/demo/uvm.ipynb

resolves [graph_dl issue 192](https://github.com/rapidsai/graph_dl/issues/192) 
fixed deprecated item in uvm notebook

UVM notebook update and add tracker for notebooks to readme

---

python/pylibcugraph/pylibcugraph/tests/test_uniform_neighbor_sample.py

This PR disables the assertions intended to check if memory is being allocated and free'd as expected.  [Recent failures](https://github.com/rapidsai/cugraph/actions/runs/5188532065/jobs/9352311316) occurring seemingly infrequently have caused suspicion as to whether these are accurately ensuring if memory is free'd or not. Plus, if the tests change to use memory pools, or pytest-xdist which result in GPU sharing, these assertions will also fail.
Instead, this PR adds a variable which can be easily set to enable or disable the assertions.  This will make it convenient for testing for memory leaks locally when the developer knows the environment is appropriate for these assertions.  We will likely add memory leak checking back in on a case-by-case basis, possibly using different tools, in …

Disables memory usage assertions

---

cpp/src/sampling/random_walks_impl.cuh
cpp/tests/c_api/sg_random_walks_test.c

CUDA-12 testing for release 23.06 detected a non-deterministic failure in the random walks test.
After some verification work, we determined there is a bug in the Random Walks implementation that can trigger out-of-bounds memory references.
This PR adds a test that triggers the OOB error (if run with `compute-sanitizer`) and a fix that resolves the issue.

[HOTFIX] Fix random walks error identified in CUDA-12 testing

---

python/cugraph/cugraph/gnn/data_loading/bulk_sampler.py

This PR optimizes bulk sampling by persisting the samples to prevent redundant computations . 
I see a 50% boost and consistent perf with this PR on `13.5 s` vs `9s`  on https://github.com/rapidsai/cugraph/pull/3628

[REVIEW] Optimize bulk sampling

---

.github/workflows/pr.yaml
.github/workflows/test.yaml
cpp/src/sampling/neighborhood.cu
cpp/src/utilities/cugraph_ops_utils.hpp
python/cugraph-dgl/cugraph_dgl/nn/conv/gatconv.py
python/cugraph-dgl/cugraph_dgl/nn/conv/transformerconv.py
python/cugraph-dgl/tests/nn/test_transformerconv.py
python/cugraph-pyg/cugraph_pyg/nn/conv/base.py
python/cugraph-pyg/cugraph_pyg/nn/conv/gat_conv.py
python/cugraph-pyg/cugraph_pyg/nn/conv/gatv2_conv.py
python/cugraph-pyg/cugraph_pyg/nn/conv/transformer_conv.py

This PR:
- renames `cugraph-ops` symbols and updates tests in `cugraph-dgl` and `-pyg` based on cugraph-ops refactoring
- updates GHA workflows to call pytest via `python -m pytest`. This is to fix the `pytest not found error` in [log](https://github.com/rapidsai/cugraph/actions/runs/5420960384/jobs/9855784044#step:9:260).

[FIX] Rename `cugraph-ops` symbols (refactoring) and update GHA workflows to call pytest via `python -m pytest`

---

cpp/src/detail/graph_partition_utils.cuh
cpp/tests/prims/mg_count_if_e.cu
cpp/tests/prims/mg_count_if_v.cu
cpp/tests/prims/mg_extract_transform_e.cu
cpp/tests/prims/mg_extract_transform_v_frontier_outgoing_e.cu
cpp/tests/prims/mg_per_v_transform_reduce_incoming_outgoing_e.cu
cpp/tests/prims/mg_reduce_v.cu
cpp/tests/prims/mg_transform_e.cu
cpp/tests/prims/mg_transform_reduce_e.cu
cpp/tests/prims/mg_transform_reduce_v.cu
cpp/tests/prims/mg_transform_reduce_v_frontier_outgoing_e_by_dst.cu
cpp/tests/prims/property_generator.cuh
cpp/tests/sampling/detail/nbr_sampling_utils.cuh

Currently we are including `cuco/detail/hash_functions.cuh` but cuCollection now has `cuco/hash_functions.cuh`. Include the public one instead.

Include cuCollection public header for hash functions

---

.github/workflows/build.yaml
.github/workflows/pr.yaml
.github/workflows/test.yaml

We are planning to enable CUDA 12 CI jobs on July 18, per https://github.com/rapidsai/shared-action-workflows/issues/112. This PR must be merged to disable CUDA 12 CI jobs for cugraph until #3271 / #3456 are merged.

Only run cugraph conda CI for CUDA 11.

---

cpp/include/cugraph/utilities/device_functors.cuh
cpp/libcugraph_etl/include/hash/concurrent_unordered_map.cuh
cpp/src/community/detail/common_methods.cuh
cpp/src/community/detail/refine_impl.cuh
cpp/src/prims/detail/nbr_intersection.cuh
cpp/src/prims/kv_store.cuh
cpp/src/prims/per_v_pair_transform_dst_nbr_intersection.cuh
cpp/src/prims/per_v_random_select_transform_outgoing_e.cuh
cpp/src/prims/per_v_transform_reduce_dst_key_aggregated_outgoing_e.cuh
cpp/src/structure/relabel_impl.cuh

Fix namesapce to default_hash and  hash_functions

[BUG]   Fix namesapce to default_hash and hash_functions

---

conda/environments/all_cuda-118_arch-x86_64.yaml
dependencies.yaml
python/cugraph-dgl/conda/cugraph_dgl_dev_cuda-118.yaml

This PR reorders the channels to be compatible with other RAPIDS libs.
#3693 added two new channels, but they were ordered differently than [other libraries](https://github.com/rapidsai/cudf/blob/branch-23.08/dependencies.yaml#L163-L169). This caused [an error](https://github.com/rapidsai/docker/actions/runs/5591817313/jobs/10223438072?pr=545#step:10:349) in the `conda-merge` script in https://github.com/rapidsai/docker/pull/545.
It's also worth noting that docker overhaul requiring the channel ordering being consistent across libraries' `dependencies.yaml` seems very fragile and will undoubtedly cause more issues down the line. Curious if anyone has thoughts on making this more reliable.

Reorder dependencies.yaml channels

---

cpp/src/prims/transform_e.cuh

@jnke2016 found a bug in MG edge betweenness centrality.  Upon investigation, the `major_offset` in this block of code wasn't being set correctly if `major` is in the hypersparse region.

Fix primitive bug discovered in MG edge betweenness centrality testing

---

cpp/src/community/legacy/spectral_clustering.cu

This PR removes a deprecation warning coming from RAFT. Including the specializations header no longer has an effect, so it can be safely removed.

Remove RAFT specialization.

---

cpp/tests/sampling/mg_uniform_neighbor_sampling.cu
cpp/tests/sampling/sg_uniform_neighbor_sampling.cu

Updated sampling call in the `#ifdef NO_CUGRAPH_OPS` branch of the SG unit test.  The MG unit test was correctly updated previously.
Fixes #3726

Fix sampling call parameters if compiled with -DNO_CUGRAPH_OPS

---

cpp/tests/sampling/mg_uniform_neighbor_sampling.cu
cpp/tests/sampling/sg_uniform_neighbor_sampling.cu

Forward-merge triggered by push to `branch-23.08` that creates a PR to keep `branch-23.10` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

Forward-merge branch-23.08 to branch-23.10

---

.github/workflows/build.yaml
.github/workflows/pr.yaml
.github/workflows/test.yaml
ci/build_wheel.sh
ci/build_wheel_cugraph.sh
ci/build_wheel_pylibcugraph.sh
ci/test_wheel.sh
ci/test_wheel_cugraph.sh
ci/test_wheel_pylibcugraph.sh

Moves the wheel build and test logic out of the workflow into the repo. This matches conda tests more closely and allows each repo to manage its own wheels more easily.

Switch to new wheel building pipeline

---

build.sh

This PR adds the following:
* Removes the now unnecessary "." path used in the install options when `--pydevelop` is used, which resulted in an error when called.
* Temporarily adds a call to `setup.py bdist_ext --inplace` only when `--pydevelop` is used to workaround a [bug in scikit-build](https://github.com/scikit-build/scikit-build/issues/981) when `setuptools>=64` is installed.

Fixes options for `--pydevelop` to remove unneeded CWD path ("."), restores use of `setup.py` temporarily for develop builds

---

cpp/src/c_api/graph_functions.cpp

A customer identified an issue trying to run Jaccard.  In MG calls they were seeing failed memory allocation calls.
Vertices were being shuffled incorrectly in the C API, so we were getting vertices processed on the wrong GPU, resulting in out-of-bounds memory references.
Moved the shuffle before renumbering, which puts vertices to be on proper GPU
Closes #3746

Fix bug discovered in Jaccard testing

---

conda/environments/all_cuda-118_arch-x86_64.yaml
conda/environments/all_cuda-120_arch-x86_64.yaml
conda/recipes/cugraph-pyg/meta.yaml
conda/recipes/cugraph/meta.yaml
conda/recipes/pylibcugraph/meta.yaml
dependencies.yaml
python/cugraph/cugraph/community/ktruss_subgraph_wrapper.pyx
python/cugraph/cugraph/structure/graph_primtypes.pxd
python/cugraph/cugraph/structure/graph_primtypes.pyx
python/cugraph/pyproject.toml
python/pylibcugraph/pylibcugraph/uniform_neighbor_sample.pyx
python/pylibcugraph/pyproject.toml

This PR contains the minimal set of changes to compile using Cython 3 without warnings. Future PRs can be made to take advantage of new or improved features.
The main change is that a the graph_primtypes module runs into https://github.com/cython/cython/issues/5554. I was able to work around that issue by removing all the fused type logic and instead just duplicate one function. There were multiple functions present that were not used at all corresponding to fused type specializations that were never instantiated, so the changes still ended up being a net reduction in code.

Update to Cython 3.0.0

---

python/cugraph/cugraph/structure/graph_implementation/simpleDistributedGraph.py

closes #3745 
This PR adds updates to replace the `get_distributed_data()` call with `persist_dask_df_equal_parts_per_worker()` and `get_persisted_df_worker_map()` to avoid a problem where `get_distributed_data()` does not distribute data properly across all workers.  This resulted in a `KeyError` when the data was accessed via worker, when that worker was not a key in the map.
More details are in the [linked issue](https://github.com/rapidsai/cugraph/issues/3745).
This PR also does minor refactoring in `get_two_hop_neighbors()` and reorganizes the imports according to [PEP 8](https://peps.python.org/pep-0008/#imports).
Tested manually on a 4-GPU system, where the problem described in #3745 was reproduced, the change in the PR applied and re-run, and the error no longer occurring.

Fixes `KeyError` for `get_two_hop_neighbors` when called with a small start vertices list

---

.github/workflows/build.yaml
.github/workflows/pr.yaml

cugraph-dgl is not supported for CUDA 12 yet and but the doc build use rapidsai/ci:latest which is on CUDA 12 now.

 Use rapidsai/ci:cuda11.8.0-ubuntu22.04-py3.10 for docs build

---

python/cugraph/cugraph/link_prediction/jaccard.py
python/cugraph/cugraph/link_prediction/sorensen.py

A [PR](https://github.com/rapidsai/cugraph/pull/3002) updating the vertex pair column names was merged few releases ago however few docstrings weren't.
This PR updates the docstrings for Jaccard and Sorensen.

Update the docstrings of the similarity algorithms

---

ci/test_python.sh
ci/test_wheel.sh
python/cugraph/cugraph/tests/centrality/test_betweenness_centrality_mg.py
python/cugraph/cugraph/tests/centrality/test_edge_betweenness_centrality_mg.py
python/cugraph/cugraph/tests/centrality/test_eigenvector_centrality_mg.py
python/cugraph/cugraph/tests/centrality/test_katz_centrality_mg.py
python/cugraph/cugraph/tests/comms/test_comms_mg.py
python/cugraph/cugraph/tests/components/test_connectivity_mg.py
python/cugraph/cugraph/tests/core/test_k_core_mg.py
python/cugraph/cugraph/tests/internals/test_renumber_mg.py
python/cugraph/cugraph/tests/link_analysis/test_hits_mg.py
python/cugraph/cugraph/tests/link_analysis/test_pagerank_mg.py
python/cugraph/cugraph/tests/link_prediction/test_jaccard_mg.py
python/cugraph/cugraph/tests/link_prediction/test_overlap_mg.py
python/cugraph/cugraph/tests/link_prediction/test_sorensen_mg.py
python/cugraph/cugraph/tests/sampling/test_egonet_mg.py
python/cugraph/cugraph/tests/sampling/test_random_walks_mg.py
python/cugraph/cugraph/tests/traversal/test_bfs_mg.py
python/cugraph/cugraph/tests/traversal/test_sssp_mg.py

This PR is on top off the changes from #3831. 
Temporarily disables single-GPU "MG" tests in CI until https://github.com/rapidsai/cugraph/issues/3790 is closed.
This will unblock CI for PRs unrelated to the issue in https://github.com/rapidsai/cugraph/issues/3790 at the risk of removed coverage for MG code paths. Hopefully nightly MG testing will minimize the risk.
A followup PR will be submitted that re-enables the tests and must be merged prior to 23.10 burndown.

Disable mg tests

---

cpp/CMakeLists.txt
cpp/cmake/thirdparty/get_raft.cmake
python/cugraph/CMakeLists.txt
python/pylibcugraph/CMakeLists.txt

https://github.com/rapidsai/raft/pull/1746 added static targets for RAFT that can be used directly now instead of building RAFT static explicitly

Use new `raft::compiled_static` targets

---

python/cugraph-pyg/cugraph_pyg/loader/cugraph_node_loader.py

Add a property getter for batch size.  Requested by JoC.

[IMP] Add ability to get batch size from the loader in cuGraph-PyG

---

ci/build_cpp.sh
ci/build_python.sh

Applies same changes for the same reasons as cuDF PR https://github.com/rapidsai/cudf/pull/14067 to cuGraph.

Uses `conda mambabuild` rather than `mamba mambabuild`

---

cpp/src/prims/detail/nbr_intersection.cuh

Closes https://github.com/rapidsai/graph_dl/issues/259
A customer found a subtle memory leak in Jaccard similarity.  Tracked it down to this subtle error.
`major_nbr_indices` is an `std::optional` that is initialized to `std::nullopt`.  Overwriting the dereferenced entry replaces the value but does not mark the optional as containing a value.  So the resulting value is never destroyed.

Fix subtle memory leak in nbr_intersection primitive

---

.pre-commit-config.yaml
cpp/src/components/legacy/scc_matrix.cuh
cpp/src/cores/core_number_impl.cuh
cpp/src/prims/per_v_random_select_transform_outgoing_e.cuh
cpp/src/sampling/random_walks.cuh
cpp/src/structure/renumber_edgelist_impl.cuh
cpp/src/traversal/bfs_impl.cuh
cpp/tests/prims/mg_extract_transform_e.cu
cpp/tests/traversal/mg_sssp_test.cpp
cpp/tests/traversal/sssp_test.cpp
cpp/tests/utilities/test_utilities.hpp

This PR updates cugraph to use clang 16.0.6. The previous version 16.0.1 has some minor formatting issues affecting several RAPIDS repos.

Update to clang 16.0.6.

---

cpp/src/sampling/sampling_post_processing_impl.cuh
cpp/tests/sampling/sampling_post_processing_test.cu

cugraph::sort_sampled_edgelist currently returns (label, hop) offsets of all zero.
This PR fixes this.

MFG C++ code bug fix

---

python/cugraph-dgl/tests/nn/test_gatconv.py
python/cugraph-dgl/tests/nn/test_gatv2conv.py
python/cugraph-dgl/tests/nn/test_relgraphconv.py
python/cugraph-dgl/tests/nn/test_sageconv.py
python/cugraph-dgl/tests/nn/test_transformerconv.py
python/cugraph-pyg/cugraph_pyg/tests/nn/test_gat_conv.py
python/cugraph-pyg/cugraph_pyg/tests/nn/test_gatv2_conv.py
python/cugraph-pyg/cugraph_pyg/tests/nn/test_rgcn_conv.py
python/cugraph-pyg/cugraph_pyg/tests/nn/test_sage_conv.py
python/cugraph-pyg/cugraph_pyg/tests/nn/test_transformer_conv.py

Forward-merge triggered by push to `branch-23.10` that creates a PR to keep `branch-23.12` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

Forward-merge branch-23.10 to branch-23.12

---

docs/cugraph/source/installation/source_build.md

closes #3722 
Updates the source build docs to include `libcugraphops` as a build prerequisite.

Updates the source build docs to include libcugraphops as a build prerequisite

---

python/cugraph/cugraph/community/louvain.py
python/cugraph/cugraph/tests/community/test_louvain.py
python/cugraph/cugraph/utilities/utils.py

- Adds logic to handle isolated vertices
- Clamp downs max level to a sane number
closes #3804

Adds logic to handle isolated vertices at python layer

---

conda/environments/all_cuda-118_arch-x86_64.yaml
conda/environments/all_cuda-120_arch-x86_64.yaml
dependencies.yaml

Running certain notebooks requires downloading datasets via https://github.com/rapidsai/cugraph/blob/branch-23.10/notebooks/cugraph_benchmarks/dataPrep.sh which uses `wget`, so this PR ensures the `test_notebooks` environment created in `rapidsai/docker` will have `wget` installed.

Add wget to test_notebook dependencies

---

ci/test_python.sh
ci/test_wheel.sh

This PR temporarily disables single-GPU "MG" tests in CI until the dask related transient failures are resolved.
The PR to re-enable them, intended to block the 23.12 release, is [here](https://github.com/rapidsai/cugraph/pull/3941).

Temporarily disable mg testing

---

python/nx-cugraph/nx_cugraph/interface.py

This test is flaky b/c Louvain in PLC does not have a seed or random state parameter. This test holds the seed fixed and changes the threshold, but clearly this may not work if we can't set the seed.

nx-cugraph: xfail test_louvain.py:test_threshold in Python 3.9

---

python/nx-cugraph/_nx_cugraph/__init__.py
python/nx-cugraph/lint.yaml
python/nx-cugraph/nx_cugraph/algorithms/__init__.py
python/nx-cugraph/nx_cugraph/algorithms/centrality/__init__.py
python/nx-cugraph/nx_cugraph/algorithms/centrality/degree_alg.py
python/nx-cugraph/nx_cugraph/algorithms/community/louvain.py
python/nx-cugraph/nx_cugraph/algorithms/core.py
python/nx-cugraph/nx_cugraph/algorithms/isolate.py
python/nx-cugraph/nx_cugraph/classes/digraph.py
python/nx-cugraph/nx_cugraph/classes/function.py
python/nx-cugraph/nx_cugraph/classes/graph.py
python/nx-cugraph/nx_cugraph/classes/multigraph.py
python/nx-cugraph/nx_cugraph/convert.py
python/nx-cugraph/nx_cugraph/tests/test_convert.py
python/nx-cugraph/nx_cugraph/tests/test_match_api.py
python/nx-cugraph/pyproject.toml

New algorithms:
- `degree_centrality`
- `in_degree_centrality`
- `k_truss`
- `number_of_selfloops`
- `out_degree_centrality`
Also, rename `row_indices, col_indices` to `src_indices, dst_indices`

nx-cugraph: add k_truss and degree centralities

---

ci/test_wheel_cugraph.sh
conda/environments/all_cuda-118_arch-x86_64.yaml
conda/environments/all_cuda-120_arch-x86_64.yaml
conda/recipes/cugraph-pyg/meta.yaml
conda/recipes/cugraph-service/meta.yaml
conda/recipes/cugraph/meta.yaml
dependencies.yaml

This PR relaxes `dask` and `distributed` versions pinning for `23.12` development.
xref: https://github.com/rapidsai/cudf/pull/14320

Unpin `dask` and `distributed` for `23.12` development

---

ci/build_docs.sh

The previous `aws s3 cp` command failed for developers who tried to run `build_docs.sh` locally. This PR addresses the issue by providing a CDN URL that delivers the tarred XML artifact.

Download `xml` docs artifact through CloudFront endpoint

---

python/cugraph-pyg/cugraph_pyg/tests/test_cugraph_loader.py

The CSC (CSR) code path in cugraph-pyg requires `torch_sparse` package. However, `torch_sparse` does not seem to work out of box for rockylinux8. This PR fixes such [CI failures](https://github.com/rapidsai/cugraph/actions/runs/6691094105/job/18177667677).
Closes https://github.com/rapidsai/graph_dl/issues/343

Skip certain `cugraph-pyg` tests when `torch_sparse` is not available

---

python/cugraph-pyg/cugraph_pyg/data/cugraph_store.py

OGB and many other datasets express the edge index in CSR order, but in release 23.10, the default order was changed to CSC, which broke downstream workflows.  This PR restores the original default, which should be acceptable for the most common datasets, and familiar to most PyG users.
Closes #3969

[BUG] Restore the original default order of CSR, which does not reverse edges in cuGraph-PyG

---

cpp/src/centrality/eigenvector_centrality_impl.cuh
cpp/src/link_analysis/hits_impl.cuh
cpp/tests/c_api/eigenvector_centrality_test.c
cpp/tests/centrality/eigenvector_centrality_test.cpp
cpp/tests/link_analysis/hits_test.cpp
python/cugraph/cugraph/tests/link_analysis/test_hits.py

Address a couple of bugs discovered in nx-cugraph testing.
HITS should raise an exception if it fails to converge.
Eigenvector computation was not quite right, nx-cugraph testing discovered an edge condition where it was obvious.
Closes #3971
Closes #3972

Fix eigenvector testing and HITS testing discrepancies

---

python/cugraph/cugraph/structure/graph_classes.py
python/cugraph/cugraph/structure/graph_implementation/simpleGraph.py

This PR contains two changes.
- A change that defers to `numpy.asarray` to process array objects that `cugraph` consumes
- An update from using `unique` to use `drop_duplicates` in `simpleGraph.py`, which always always returns a Series to preserve pandas compatibility.

CuGraph compatibility fixes

---

python/nx-cugraph/README.md

* Fixes typos (repeated word, extra periods)
* Updates link to the current docs on NetworkX backends

Fixes to nx-cugraph README: fixes typos, updates link to NX backend docs

---

ci/release/update-version.sh
python/nx-cugraph/_nx_cugraph/__init__.py

Adds `update-version.sh` support for:
* nx-cugraph meta-data files
* `cugraph-pyg`, `cugraph-dgl` env yaml files
* `*-cu11`, `*-cu12` wheel dependencies in dependencies.yaml

Adds `update-version.sh` support for recently added files containing RAPIDS versions

---

build.sh
cpp/CMakeLists.txt
cpp/tests/CMakeLists.txt
python/cugraph/cugraph/structure/property_graph.py

Forward-merge triggered by push to `branch-23.12` that creates a PR to keep `branch-24.02` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

Forward-merge branch-23.12 to branch-24.02

---

conda/recipes/cugraph-dgl/meta.yaml
conda/recipes/cugraph-pyg/meta.yaml

This PR fixes some pinnings in cuGraph conda recipes. The problem is similar to that handled in https://github.com/rapidsai/cudf/pull/14420. The `{{ version }}` variable can only be used to constrain conda packages built by CI workflows in the _same repository_ because `{{ version }}` includes information about the git commit. We must use `{{ minor_version }}` to constrain other RAPIDS packages. In cuGraph, that means that `pylibcugraphops` (which is built by the cugraph-ops repository) and `rapids-dask-dependency` must pin with `={{ minor_version }}` instead of `={{ version }}`.

Pin to minor versions of packages outside the cuGraph repository.

---

cpp/CMakeLists.txt

RAPIDS currently relies on copies of CCCL headers bundled into rmm. This dependency is centralized by virtue of rmm installing these into the package and everything else finding those installed packages. To do this, however, rmm must be loaded first so that the libcudacxx install location is patched into CMake's search paths. cugraph also uses cuco, which requires libcudacxx but does not bundle its own, so rmm must be found first so that cuco can find libcudacxx where rmm installed it.

Find rmm before cuco

---

docs/cugraph/source/installation/source_build.md

closes #4008 
* Removes unsupported `setup.py` calls, which resulted in issue #4008 . The document now describes how to use `build.sh`, which is more consistent with docs for other RAPIDS libs.
* Removes `build.sh` output from docs in favor of documenting how to use `--help` to eliminate the doc being out-of-date with the script.
* Removes extra wording in places and cleans up various sections.

Removes unsupported `setup.py` calls, cleans up text

---

cpp/tests/structure/mg_select_random_vertices_test.cpp

`% 0` throws an exception (`mg_graph_view.local_vertex_partition_range_size()` & `num_of_elements_in_given_set` can be 0). This PR fixes the bug.

Fix % 0 bug in MG_SELECT_RANDOM_VERTICES test

---

.github/workflows/labeler.yml

RAPIDS repos are using the `main` branch of https://github.com/actions/labeler which recently introduced [breaking changes](https://github.com/actions/labeler/releases/tag/v5.0.0).
This PR pins to the latest v4 release of the labeler action until we can evaluate the changes required for v5.
This PR also moves the labeler workflow to the correct location in the repo.

Pin actions/labeler to v4

---

python/cugraph/cugraph/dask/common/mg_utils.py
python/cugraph/cugraph/structure/graph_implementation/simpleDistributedGraph.py

This PR introduces a short term fix for https://github.com/rapidsai/cugraph/issues/4037 . 
CC: @jnke2016 , @rlratzel

Add a barrier before cugraph Graph creation

---

ci/build_wheel_cugraph.sh
ci/build_wheel_pylibcugraph.sh
python/cugraph/CMakeLists.txt
python/pylibcugraph/CMakeLists.txt

Some minor simplification in advance of the scikit-build-core migration to better align wheel and non-wheel Python builds.

Remove CUGRAPH_BUILD_WHEELS and standardize Python builds

---

dependencies.yaml

This PR changes all references to pypi.nvidia.com to pypi.anaconda.org/rapidsai-wheels-nightly.

Update dependencies.yaml to new pip index

---

cpp/src/community/flatten_dendrogram.hpp

Fix non-type template parameter to `cugraph::relabel`

[BUG]Fix non-type template parameter to cugraph::relabel

---

ci/test_python.sh
ci/test_wheel_cugraph-pyg.sh
python/cugraph-pyg/cugraph_pyg/tests/mg/test_mg_cugraph_store.py
python/cugraph-pyg/pyproject.toml

This is an oversight from #4075. With this fix, the generated wheels should have proper a CUDA suffix (e.g. `cugraph-pyg-cu12`).
Edit: This PR also fixes https://github.com/rapidsai/graph_dl/issues/421 
The mg tests were not skipped as expected due to wrong relative path in `test_wheel_cugraph-pyg.sh`.

Correct `cugraph-pyg` package name used in wheels and fix test script

---

python/nx-cugraph/_nx_cugraph/__init__.py
python/nx-cugraph/nx_cugraph/_version.py
python/nx-cugraph/nx_cugraph/algorithms/community/louvain.py
python/nx-cugraph/nx_cugraph/algorithms/components/connected.py
python/nx-cugraph/nx_cugraph/tests/__init__.py
python/nx-cugraph/nx_cugraph/tests/test_connected.py

Hooray for removing and cleaning code! Tests also added (we already tested isolated nodes for Louvain).
nx-cugraph was updated to handle isolated nodes by passing the node set to PLC in #4077

nx-cugraph: PLC now handles isolated nodes; clean up our workarounds

---

cpp/include/cugraph/edge_partition_device_view.cuh
cpp/include/cugraph/graph_view.hpp
cpp/src/link_prediction/similarity_impl.cuh
cpp/src/prims/detail/nbr_intersection.cuh
cpp/src/prims/per_v_pair_transform_dst_nbr_intersection.cuh
cpp/src/prims/transform_e.cuh
cpp/src/structure/graph_view_impl.cuh
cpp/src/utilities/error_check_utils.cuh
cpp/tests/CMakeLists.txt
cpp/tests/structure/count_self_loops_and_multi_edges_test.cpp
cpp/tests/structure/has_edge_and_compute_multiplicity_test.cpp
cpp/tests/structure/mg_has_edge_and_compute_multiplicity_test.cpp
cpp/tests/utilities/device_comm_wrapper.cu
cpp/tests/utilities/test_utilities.hpp

Forward-merge triggered by push to `branch-24.02` that creates a PR to keep `branch-24.04` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

Forward-merge branch-24.02 to branch-24.04

---

cpp/include/cugraph_c/community_algorithms.h
cpp/include/cugraph_c/sampling_algorithms.h
cpp/include/cugraph_c/traversal_algorithms.h
docs/cugraph/source/api_docs/cugraph_c/community.rst
docs/cugraph/source/api_docs/cugraph_c/labeling.rst
docs/cugraph/source/api_docs/cugraph_c/sampling.rst
docs/cugraph/source/api_docs/cugraph_c/similarity.rst
docs/cugraph/source/api_docs/cugraph_c/traversal.rst

Fixes broken links in C API docs in Traversal, Sampling and Community algorithm sections
resolves issue #4116

corrected links in C API and added groups for support functions

---

.github/workflows/test.yaml

Fixes https://github.com/rapidsai/graph_dl/issues/446
fixes https://github.com/rapidsai/graph_dl/issues/447
Cannot test these wheels in CI due to lack of ARM binary builds for pytorch.

Constraint pytorch-dependent wheel test to only run on amd64

---

ci/test_wheel_cugraph-dgl.sh
ci/test_wheel_cugraph-pyg.sh
cpp/libcugraph_etl/CMakeLists.txt
cpp/libcugraph_etl/src/renumbering.cu
python/cugraph-dgl/cugraph_dgl/dataloading/utils/sampling_helpers.py
python/cugraph/cugraph/gnn/data_loading/bulk_sampler_io.py
python/cugraph/cugraph/gnn/dgl_extensions/dgl_uniform_sampler.py
python/cugraph/cugraph/sampling/sampling_utilities.py
python/cugraph/cugraph/tests/sampling/test_bulk_sampler.py
python/cugraph/cugraph/tests/sampling/test_bulk_sampler_mg.py
python/cugraph/cugraph/tests/sampling/test_uniform_neighbor_sample.py
python/cugraph/cugraph/tests/sampling/test_uniform_neighbor_sample_mg.py

This PR contains a number of different fixes currently required to get cugraph tests passing:
- There are two main changes for pandas 2 compatibility:
- [pandas renamed `DataFrame.applymap` to `DataFrame.map`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.map.html) so creating the renumbering map with a column `map` caused problems for attribute-based column access `renumber_map.map`. Those columns are now renamed to `renumber_map`.
- Empty columns now default to str rather than float, so tests that assumed we could access the values as cupy arrays failed because cudf's string columns cannot be converted to cupy arrays. These columns are now always cast to float in the tests before the cupy conversion.
- cugraph-dgl and cugraph-pyg's wheel builds were not downloading the …

Fixes for pandas 2, latest cudf, and wheel building

---

python/cugraph-dgl/pyproject.toml
python/cugraph-equivariant/pyproject.toml
python/cugraph-equivariant/setup.py
python/cugraph-pyg/pyproject.toml
python/cugraph-service/client/pyproject.toml
python/cugraph-service/server/pyproject.toml
python/cugraph/pyproject.toml
python/nx-cugraph/pyproject.toml
python/pylibcugraph/pyproject.toml

This reverts commit 5c6c4d3e716c49932ba46642a4d0ad9cb82f0036.
This change introduced [testing errors](https://github.com/rapidsai/cugraph/actions/runs/7828355710/job/21358058232), so reverting for `24.02` and will fix in `24.04`.

Revert "Exclude tests from builds (#4147)"

---

conda/environments/all_cuda-118_arch-x86_64.yaml
conda/environments/all_cuda-120_arch-x86_64.yaml
dependencies.yaml

This PR fixes issues with devcontainer builds where `cuda-nvtx-dev` was missing when building `libcugraph_etl`.

Add cuda-nvtx-dev, add missing CUDA library dependencies.

---

python/cugraph/cugraph/structure/number_map.py

Addresses #4163 
This PR uses `iloc` when referencing the index in a Series object, which removes the `FutureWarning` that was seen at graph creation.

Fix `FutureWarnings` in Graph Creation

---

python/cugraph/cugraph/community/induced_subgraph.py
python/cugraph/cugraph/tests/community/test_induced_subgraph_mg.py

Addresses [#459](https://github.com/rapidsai/graph_dl/issues/459)
Changes:
- Updates `cugraph/community/induced_subgraph.py` to use `Series.iloc` to avoid a `DeprecationWarning` when calling the function
- This PR fixes a bug in `test_mg_induced_subgraph` where it would break when passed an `ndarray` object while trying to construct an MG induced sub-graph. 
- This unit test has been cleaned up to use the `cugraph.datasets` API to construct SG and MG graph objects, as well as the `sample_random_vertices` function to construct sub-graphs the proper way.
Notes:
- The `offsets` parameter is not ready for testing yet.
- There is no one-hop neighbor check in place to verify if the sub-graphs are actually generated correctly.
- This test will be updates once those are available.

Refactor and Fix `test_induced_subgraph_mg`

---

docs/cugraph/source/installation/getting_cugraph.md

Update installation docs for CUDA 12.

---

.github/workflows/pr.yaml
.github/workflows/test.yaml
ci/test_python.sh
ci/test_wheel_cugraph-dgl.sh
python/cugraph/cugraph/structure/hypergraph.py
python/cugraph/cugraph/tests/data_store/test_property_graph.py
python/nx-cugraph/_nx_cugraph/__init__.py
python/nx-cugraph/nx_cugraph/algorithms/community/louvain.py
python/nx-cugraph/nx_cugraph/tests/test_match_api.py

* Updates cudf usage in hypergraph to use `cudf.core.column.as_column` instead of the deprecated `cudf.core.column.full` API
* Adds code to call louvain using a signature that's compatible with both pre and post NX 3.3
* Adds an upper bound to the DGL version pin to ensure a compatible version is used
* Updates a PropertyGraph test to handle minor ordering changes in the result DataFrame
* Test matrices starting 24.04 have changed, resulting in an "empty matrix" error when attempting to use the supported combination used for PyG (PyG wheel tests need pytorch with CUDA 12.2 on arm64), so the matrix was simplified to remove the CUDA 11.8 requirement. cc @tingyu66

Fix `louvain_communities`, `PropertyGraph`, cudf `column.full`, dgl 2.1.0 CI failures

---

cpp/src/structure/graph_view_impl.cuh

Remove CUGRAPH_EXPECTS(!(this->has_edge_mask()), unimplemented.)

Remove CUGRAPH_EXPECTS(!(this->has_edge_mask()), unimplemented.)

---

python/cugraph/cugraph/community/egonet.py
python/cugraph/cugraph/dask/community/egonet.py

This PR addresses #4191 
Since the plan is to add "batched" support to the regular `ego_graph` method, a `DeprecationWarning` has been added to `batched_ego_graphs`. 
--
Minor change: use proper indexing when accessing a pd.Series value.

Add `DeprecationWarning` to `batched_ego_graphs`

---

benchmarks/cugraph/pytest-based/bench_cugraph_uniform_neighbor_sample.py

This PR addresses one of the nightly benchmark algo failures that was calling the previous (experimental) version of the Datasets API.
Relevant Logs: https://mg-test-results.s3.us-east-2.amazonaws.com/cugraph/20240306_101219_UTC/benchmarks/2-GPU/pytest-results.html

Remove Usage of Experimental Datasets Package

---

ci/build_wheel.sh
ci/test_wheel.sh
ci/test_wheel_cugraph-dgl.sh
ci/test_wheel_cugraph-equivariant.sh
ci/test_wheel_cugraph-pyg.sh

This marks `nx-cugraph`, `cugraph-dgl`, `cugraph-pyg`, and `cugraph-equivariant` as pure wheels, meaning that the CI artifacts are not specific to a Python version or CPU architecture. This change depends on https://github.com/rapidsai/gha-tools/pull/96, and makes CI workflows more robust by allowing the test matrix to be separated from the build matrix.

Treat nx-cugraph, cugraph-pyg, cugraph-dgl, and cugraph-equivariant CI artifacts as pure wheels

---

.github/workflows/pr.yaml
.github/workflows/test.yaml
cpp/include/cugraph/detail/decompress_edge_partition.cuh
cpp/libcugraph_etl/include/hash/helper_functions.cuh
cpp/libcugraph_etl/src/renumbering.cu
cpp/src/community/legacy/ecg.cu
cpp/src/components/legacy/weak_cc.cuh
cpp/src/layout/legacy/bh_kernels.cuh
cpp/src/layout/legacy/exact_repulsion.cuh
cpp/src/layout/legacy/fa2_kernels.cuh
cpp/src/prims/detail/extract_transform_v_frontier_e.cuh
cpp/src/prims/per_v_random_select_transform_outgoing_e.cuh
cpp/src/prims/per_v_transform_reduce_incoming_outgoing_e.cuh
cpp/src/prims/transform_e.cuh
cpp/src/prims/transform_reduce_e.cuh
cpp/src/prims/transform_reduce_e_by_src_dst_key.cuh
cpp/src/structure/graph_view_impl.cuh
cpp/src/traversal/od_shortest_distances_impl.cuh
cpp/src/utilities/eidecl_graph_utils.hpp
cpp/src/utilities/eidir_graph_utils.hpp
cpp/src/utilities/graph_utils.cuh
cpp/src/utilities/path_retrieval.cu

Downstream consumers of static built versions of RAPIDS C++ projects have encountered runtime issues due to multiple instances of the same kernel existing in different DSOs.
To resolve this issue we need to ensure that all CUDA kernels in all RAPIDS libraries need to be have internal linkage ( static for projects using whole compilation, __attribute__((visibility("hidden"))) for header libraries / separable compilation ).
This updates all cugraph kernels to have internal linkage, and adds a CI job to verify that no new kernels are added with external linkage.

Mark kernels as internal

---

.pre-commit-config.yaml
python/nx-cugraph/_nx_cugraph/__init__.py

A [recent PR](https://github.com/rapidsai/cugraph/pull/4217) was merged that added `packaging` as a runtime dependency to nx-cugraph.  This PR removes that dependency and manually extracts the `major` and `minor` version numbers instead.

Removes (unintentional?) runtime dependency on `packaging` from nx-cugraph

---

python/cugraph-equivariant/cugraph_equivariant/nn/tensor_product_conv.py

Always scatter in FP32 in TPConv due to poor performance of torch's native scatter_add in bfloat16.

Always scatter in FP32 in TPConv

---

ci/test_python.sh
ci/test_wheel.sh
python/cugraph/cugraph/dask/common/part_utils.py
python/cugraph/cugraph/dask/comms/comms.py

Closes #4190
cc: @jnke2016 
This PR adds a function to `comms.py` which returns a mapping of workers to ranks. This is then sorted in `part_utils.py` before being used to submit jobs to `dask`.
This should fix a bug in MG `ego_graph` where induced subgraphs were being returned in seemingly random orders (while the results are correct).

Fix Bug in MG `ego_graph`

---

ci/build_docs.sh
ci/check_style.sh
ci/test_cpp.sh
ci/test_notebooks.sh
ci/test_python.sh

conda dropped support for the `--force` flag to `conda env create`. This changes that flag name to `--yes`.
See https://github.com/conda/conda/blob/main/CHANGELOG.md#2430-2024-03-12 and https://github.com/rapidsai/miniforge-cuda/pull/63 for more info.

Use `conda env create --yes` instead of `--force`

---

docs/cugraph/source/installation/getting_cugraph.md

`https://pypi.ngc.nvidia.com` was retired a while ago, and RAPIDS wheels are now available from `https://pypi.nvidia.com` (see https://docs.rapids.ai/install).
This proposes removing one lingering reference to `pypi.ngc.nvidia.com` left over in this project's docs.
```shell
docker run \
--rm \
python:3.10 \
pip install --dry-run cugraph-cu12 --extra-index-url=https://pypi.nvidia.com
```
saw the expected output
```text
Collecting cugraph-cu12
Downloading https://pypi.nvidia.com/cugraph-cu12/cugraph_cu12-24.2.0-cp310-cp310-manylinux_2_28_aarch64.whl (1318.6 MB)
```
This is the only use of that `ngc.nvidia.com` URL in this project.
```shell
git grep -E 'ngc\.'
```

fix PyPI URL in docs

---

python/cugraph/cugraph/structure/graph_classes.py

Closes #4165
This PR removes this statement from `cugraph/structure/graph_classes.py`
> Undirected Graphs are not currently supported.

Fix Docstring for `from_dask_cudf_edgelist`

---

cpp/tests/centrality/betweenness_centrality_reference.hpp

This PR fixes the [build error](https://github.com/rapidsai/cugraph/actions/runs/8713790822/job/23902856859?pr=4352#step:7:6141) in the pip devcontainers.

Add missing `<optional>` include

---

conda/recipes/cugraph-pyg/conda_build_config.yaml
conda/recipes/cugraph-pyg/meta.yaml
conda/recipes/cugraph/conda_build_config.yaml
conda/recipes/cugraph/meta.yaml
conda/recipes/libcugraph/conda_build_config.yaml
conda/recipes/libcugraph/meta.yaml
conda/recipes/pylibcugraph/conda_build_config.yaml
conda/recipes/pylibcugraph/meta.yaml

The `sysroot*` syntax is getting phased out (conda-forge/conda-forge.github.io#2102).
The recommendation is to move to `{{ stdlib("c") }}`.
Ref https://github.com/rapidsai/build-planning/issues/39

Migrate to `{{ stdlib("c") }}`

---

python/cugraph-service/server/cugraph_service_server/cugraph_handler.py
python/cugraph-service/server/cugraph_service_server/testing/benchmark_server_extension.py
python/cugraph/cugraph/structure/property_graph.py

This handles a [recent cuDF change](https://github.com/rapidsai/cudf/pull/15683) by applying non-dict and non-Series values for a `fillna()` call on `PropertyGraph` instances only to the user-defined columns, with the assumption that savvy users that intend to update the "internal" columns, or users that are aware of their own categorical dtype columns, will use a dict or Series value to properly apply dtypes as needed.
This also updates code in `cugraph-service` that serializes dataframes to numpy bytes to properly convert NA values when categoricals are present.
Notes:
* This is only applied to the SG `PropertyGraph` class.  The MG class needs further review as to how to best apply the same policy (and because there are other MG failing tests that need addressed).  Since this is …

Updates SG `PropertyGraph` and `cugraph-service` to apply `DataFrame.fillna()` based on latest cuDF changes

---

python/cugraph/cugraph/community/ktruss_subgraph.py
python/cugraph/cugraph/tests/community/test_k_truss_subgraph.py

This deprecated parameter appears to be a no-op but can raise the warning through `k_truss` with no addressable action from a user.

Address k_truss_subgraph(use_weights=) deprecation

---

python/cugraph/cugraph/tests/sampling/test_random_walks_mg.py

Removes an easy `PytestBenchmarkWarning` from the tests

Remove unused benchmark fixture in test_dask_mg_random_walks

---

python/cugraph/cugraph/tests/community/test_subgraph_extraction.py

Broken off from https://github.com/rapidsai/cugraph/pull/4271
Appears this was deprecated in favor of `induced_subgraph`

Adjust deprecated cugraph.subgraph usage in Python tests

---

python/cugraph/cugraph/tests/link_prediction/test_overlap.py
python/cugraph/cugraph/tests/link_prediction/test_sorensen.py

Looks like this parameter has no effect in `sorensen` and `overlap` so it should test equivalent behavior to set to `False` and avoid the `FutureWarning`

Address do_expensive_check FutureWarnings in Python tests

---

python/cugraph/cugraph/structure/graph_implementation/simpleGraph.py

`__from_edgelist`'s default is causing a `PendingDeprecationWarning` from having a default of `legacy_renum_only=True`.
It appears that this parameter has no effect so it should be OK to change the default so that this warning doesn't appear

Address PendingDeprecationWarning from _from_edgelist

---

cpp/src/utilities/collect_comm.cuh

Update collect_comm to handle value of tuple type

Update collect_comm to handle value of tuple type

---

cpp/include/cugraph/detail/decompress_edge_partition.cuh
cpp/include/cugraph/graph_functions.hpp
cpp/src/c_api/betweenness_centrality.cpp
cpp/src/community/k_truss_impl.cuh
cpp/src/prims/transform_reduce_dst_nbr_intersection_of_e_endpoints_by_v.cuh
cpp/src/structure/coarsen_graph_impl.cuh
cpp/src/structure/decompress_to_edgelist_impl.cuh
cpp/src/structure/decompress_to_edgelist_mg.cu
cpp/src/structure/decompress_to_edgelist_sg.cu
cpp/src/structure/symmetrize_graph_impl.cuh
cpp/src/structure/transpose_graph_impl.cuh
cpp/src/structure/transpose_graph_storage_impl.cuh
cpp/tests/centrality/eigenvector_centrality_test.cpp
cpp/tests/community/egonet_validate.cu
cpp/tests/cores/k_core_validate.cu
cpp/tests/prims/mg_transform_e.cu
cpp/tests/sampling/random_walks_check.cuh
cpp/tests/structure/mg_symmetrize_test.cpp
cpp/tests/structure/mg_transpose_storage_test.cpp
cpp/tests/structure/mg_transpose_test.cpp
cpp/tests/structure/symmetrize_test.cpp
cpp/tests/structure/transpose_storage_test.cpp
cpp/tests/structure/transpose_test.cpp
cpp/tests/utilities/conversion_utilities_impl.cuh
cpp/tests/utilities/debug_utilities_impl.hpp

Update decompress_to_edgelist to handle edge types

Update decompress_to_edgelist to handle edge types

---

python/cugraph/cugraph/sampling/uniform_neighbor_sample.py

#4355 accidentally added an expensive check to SG uniform neighbor sample.  This PR reverts that addition.

[FIX] Remove Unintentional Expensive Check from SG Uniform Neighbor Sample

---

cpp/src/prims/kv_store.cuh

Update size_ field of kv_cuco_store_t with correct values.

Fix bug in kv_store_t's insertion methods

---

ci/test_wheel_cugraph-dgl.sh

To fix the [CI nightly issue](https://github.com/rapidsai/cugraph/actions/runs/9188624604/job/25298484338#step:8:837) in cugraph-dgl wheel test for CUDA 11.

Pin torch version in `cugraph-dgl` wheel test

---

conda/environments/all_cuda-118_arch-x86_64.yaml
conda/environments/all_cuda-122_arch-x86_64.yaml
dependencies.yaml

fixes #4474 
#4496 and related PRs introduced a ceiling on `openmpi`, a dependency that's only pulled in at test time, because `cugraph`'s builds were struggling to find it.
This proposes removing that pin, as the fixes in https://github.com/conda-forge/openmpi-feedstock/pull/159 should allow the package to again be found by e.g. `find_package(MPI)` in CMake scripts.

remove openmpi ceiling

---

cpp/src/community/triangle_count_impl.cuh

MG triangle count computation hangs when invoked with a small number of vertices to update triangle counts (so some GPUs have 0 vertex to update); this PR fixes this hang issue.

[BUG] Fix a hang issue in MG triangle counts (when invoked with a small number of vertices to update triangle counts)

---

python/nx-cugraph/lint.yaml
python/nx-cugraph/nx_cugraph/classes/graph.py
python/nx-cugraph/nx_cugraph/convert_matrix.py

Optimistically use cupy, but fall back to numpy if necessary.
Also, bump lint versions.
CC @rlratzel

Better handle cudf.pandas in `from_pandas_edgelist`

---

cpp/libcugraph_etl/CMakeLists.txt

Usage of the CUDA math libraries is independent of the CUDA runtime. Make their static/shared status separately controllable.
Contributes to https://github.com/rapidsai/build-planning/issues/35

Add CUDA_STATIC_MATH_LIBRARIES

---

python/cugraph-pyg/cugraph_pyg/examples/gcn_dist_mnmg.py

For MNMG processing, the only supported memory type is `distributed`.  While it is possible to test using `torchrun` on a single machine, when running on multiple machines, or a SLURM cluster, etc., anything other than `distributed` won't work.  Therefore, this PR makes `distributed` the default memory type for that example to avoid user confusion.

[IMP] Set the Default WG Memory Type to 'distributed' for the MNMG PyG Example

---

python/cugraph/cugraph/structure/graph_implementation/simpleDistributedGraph.py

This PR fixes a warning seen when accessing a `dask_cudf.Series` object directly

Fix Warning from `simpleDistributedGraph.py`

---

datasets/get_test_data.sh

* support calling `get_test_data.sh` from any directory
* only download datasets if newer than local copies
* extract datasets in parallel
After this PR, datasets will be stored in `datasets/tmp` and not deleted after extraction, because `wget -N` (aka `--timestamping`) relies on comparing the local and remote mtimes.

Ensure `get_test_data.sh` doesn't re-download datasets

---

cpp/include/cugraph/graph_functions.hpp
cpp/src/structure/create_graph_from_edgelist_impl.cuh
cpp/src/structure/create_graph_from_edgelist_mg_v32_e32.cu
cpp/src/structure/create_graph_from_edgelist_mg_v32_e64.cu
cpp/src/structure/create_graph_from_edgelist_mg_v64_e64.cu
cpp/src/structure/create_graph_from_edgelist_sg_v32_e32.cu
cpp/src/structure/create_graph_from_edgelist_sg_v32_e64.cu
cpp/src/structure/create_graph_from_edgelist_sg_v64_e64.cu
cpp/tests/mtmg/multi_node_threaded_test.cu
cpp/tests/mtmg/threaded_test.cu
cpp/tests/mtmg/threaded_test_jaccard.cu
cpp/tests/mtmg/threaded_test_louvain.cu
cpp/tests/structure/renumbering_test.cpp
cpp/tests/utilities/test_graphs.hpp

Added a graph creation function that takes edge list in multiple chunks. This helps to cut peak memory footprint.

Create a graph from the edge list in multiple chunks

---

dependencies.yaml

This change ensures RAPIDS build backend writes the correct `cugraph-service-client` package in the `cugraph-service-server` wheel's dependencies metadata.

Add `-cuXX` suffixed versions of cugraph-service-client dependency to pyproject.toml's project.dependencies list

---

python/cugraph/cugraph/tests/community/test_triangle_count.py
python/cugraph/cugraph/tests/traversal/test_paths.py

This PR count the total number of triangles before testing it against the ground truth. It also remove an unnecessary sorting before testing.

Fix triangle count test bug

---

python/cugraph/cugraph/tests/data_store/test_gnn_feat_storage_wholegraph.py

CI is currently blocked due to these tests failing.  This PR disables the failing tests to unblock CI.

Temporarily Disable Feature Store Tests with WholeGraph

---

python/nx-cugraph/nx_cugraph/convert_matrix.py

This fixes this: https://github.com/networkx/networkx/pull/7466
We would catch this (and other changes) if we tested networkx nightlies. Someday!
I kept the buggy behavior for older versions of networkx in order to match networkx, which feels kinda silly, but also okay-ish.

nx-cugraph: fix `from_pandas_edgekey` given edgekey but not edgeattr

---

python/cugraph/cugraph/dask/centrality/katz_centrality.py

[This](https://github.com/rapidsai/cudf/pull/16311) PR recently introduced some API changes that broke `test_katz_centrality_mg.py` because it was using an improper method of trying to evaluate a `cudf.DataFrame` to a truth value.
This PR adds a fix to check if the `nstart` argument is set to `None`.

Fix MG `katz_centrality`: Check if DataFrame Arg is Not None

---

python/nx-cugraph/nx_cugraph/classes/graph.py
python/nx-cugraph/nx_cugraph/classes/multigraph.py

Adding this now, because this was an oversight.
By having a `G.__networkx_cache__` MutableMapping, we give NetworkX the ability to cache graph conversions. This will be most useful in dev and future versions of NetworkX. As such, it would be nice (but not strictly essential) to get this in 24.08.

nx-cugraph: add `G.__networkx_cache__` to enable graph conversion caching

---

conda/recipes/pylibcugraph/meta.yaml

@quasiben noticed that pylibcugraph was missing a pylibraft dependency. See #4568.
This PR adds the missing dependency on pylibraft, and also adds a dependency on rmm. This aligns with the wheel packaging: https://github.com/rapidsai/cugraph/blob/aa0347cd208255942fce6b926843f005a538c06f/dependencies.yaml#L132-L139

Add pylibcugraph dependency on pylibraft.

---

python/nx-cugraph/_nx_cugraph/__init__.py
python/nx-cugraph/nx_cugraph/__init__.py

This is to address the feedback from @bdice in https://github.com/rapidsai/cugraph/pull/4531#discussion_r1697414065, which I was unable to do in that PR.
I know checking version strings is playing it fast-and-loose, but I believe we are abundantly safe to do so here, as networkx releases have been, and are expected to be, slow and predictable. Also, we do not have `packaging` as a runtime dependency (it _is_ a test dependency for finer control).
So, even better than using `packaging.version.parse`, this PR performs a sanity check on the networkx version. I put it in both `nx_cugraph.__init__` and `_nx_cugraph.__init__` to give us obvious breadcrumbs to discover and follow.

nx-cugraph: check networkx version

---

conda/recipes/cugraph-dgl/meta.yaml
conda/recipes/cugraph-equivariant/meta.yaml
conda/recipes/cugraph-pyg/meta.yaml
conda/recipes/cugraph-service/meta.yaml
conda/recipes/nx-cugraph/meta.yaml

@caryr35 pointed out to me this morning that `cugraph`'s nightly CI is failing. All `conda-python-build` jobs are failing like this, when building `nx-cugraph`
> ModuleNotFoundError: No module named 'setuptools'
> ...
> ValueError: Could not import build backend specified in pyproject.toml's tool.rapids-build-backend table. Make sure you specified the right optional dependency in your build-system.requires entry for rapids-build-backend.
([build link](https://github.com/rapidsai/cugraph/actions/runs/10176436224/job/28166520972))
**suspected root cause:**  `nx-cugraph` uses `setuptools.build_meta`, but `setuptools` isn't present in the conda build environment
Looks like CI is failing there too: https://github.com/rapidsai/cugraph/actions/runs/10183681336/job/28171285190
I suspect that …

add setuptools to host requirements for conda packages that need it

---

ci/release/update-version.sh

Back ports the `update-version.sh` fixes from https://github.com/rapidsai/cugraph/pull/4562

Fix ucx-py update-version script

---

python/cugraph/cugraph/utilities/utils.py

This PR fixes an issue that recently arose due to a change in constructing a `cudf.Series` object.
`test_property_graph_mg.py` uses a function from `utilities/utils.py` to construct a Series object from 2d arrays. The function is now using the correct `cudf.Series._from_column` API.

Fix `test_property_graph_mg` Usage of Util Function

---

cpp/src/prims/detail/sample_and_compute_local_nbr_indices.cuh
cpp/src/prims/detail/transform_v_frontier_e.cuh
cpp/tests/prims/mg_per_v_random_select_transform_outgoing_e.cu

Fix bugs in biased sampling with 0 bias values.
Add tests that include 0 bias edges.

Biased sampling primitive bug fix

---

python/cugraph/cugraph/structure/hypergraph.py
python/cugraph/cugraph/tests/structure/test_hypergraph.py

cc: @rlratzel @ChuckHastings 
This PR addresses failures seen in certain PRs (like [here](https://github.com/rapidsai/cugraph/actions/runs/10372270389/job/28718471674?pr=4606#step:7:5269)) due to a [recent change](https://github.com/rapidsai/cudf/pull/16514) to `cudf` that disallows selecting duplicate column labels.
---
In `hypergraph.py`, this PR modifies `_create_hyper_edges` and `_create_direct_edges` to ensure that DataFrames are being indexed by non-duplicate column values.
This is done by taking a list that includes duplicates (`fs`), and removing the non-unique values
```python
fs = list(set(fs))
```
_This part requires some attention from the author of the unit test @jnke2016_
In `test_hypergraph.py`, this PR adds the `check_like=True` arg to `assert_frame_equals` function …

Updates to `cugraph.hypergraph` (Duplicate Col Labels Bug)

---

python/nx-cugraph/_nx_cugraph/__init__.py

Part of https://github.com/rapidsai/graph_dl/issues/579
This PR allows `nx-cugraph` to operate with release candidate (under development) versions of `networkx`
What This Pattern Allows:
- Just a single digit: `3.4`, `3.9`, etc
- Release Candidate format: `3.4rc0`. `3.7rc2`
This is needed to complete adding nightly test coverage for development branches of `nx`

Add Additional Check for `NetworkX` Release Candidate Versions

---

python/cugraph/cugraph/utilities/utils.py

A recent API change in cudf (https://github.com/rapidsai/cudf/pull/16465) now requires the `data` argument to be passed (consistent with the other Column subclasses)

Fix ListColumn constructor argument

---

benchmarks/cugraph/pytest-based/bench_cugraph_uniform_neighbor_sample.py

This PR adds two arguments (`use_legacy_names=False`, `with_edge_properties=True`) to suppress warnings from `bench_cugraph_uniform_neighbor_sample.py` and reduces the number of fan-out combinations being run in the nightlies.

Remove Warnings and Timeout from `bench_cugraph_uniform_neighbor_sample.py` 

---

conda/recipes/nx-cugraph/meta.yaml

Build strings aren't being published correctly for `nx-cugraph` (see missing info in current nightlies: https://anaconda.org/rapidsai-nightly/nx-cugraph/files). This is due to a formatting or copy-paste problem in the `meta.yaml` recipe file. This PR fixes the problem.

Fix build strings in nx-cugraph

---

benchmarks/nx-cugraph/pytest-based/README.md
benchmarks/nx-cugraph/pytest-based/run-main-benchmarks.sh

This PR is a follow-up to https://github.com/rapidsai/cugraph/pull/4616
This PR adds the following CLI argument options for `benchmarks/nx-cugraph/pytest-based/run-main-benchmarks.sh` 
- `--cpu-only`
- `--gpu-only`
And adds minor updates to the README

Add `--cpu-only` or `--gpu-only` Arguments to `nx-cugraph` Benchmark

---

.pre-commit-config.yaml
benchmarks/cugraph-dgl/python-script/ogbn_mag_benchmark.py
python/cugraph-dgl/cugraph_dgl/nn/conv/base.py
python/cugraph-dgl/examples/graphsage/node-classification-dask.py
python/cugraph-dgl/examples/graphsage/node-classification.py
python/cugraph-dgl/examples/multi_trainer_MG_example/model.py
python/cugraph-dgl/examples/multi_trainer_MG_example/workflow_mnmg.py
python/cugraph-dgl/examples/multi_trainer_MG_example/workflow_snmg.py
python/cugraph-pyg/cugraph_pyg/data/dask_graph_store.py
python/cugraph-pyg/cugraph_pyg/examples/gcn_dist_sg.py
python/cugraph-service/tests/test_e2e.py
python/cugraph-service/tests/test_mg_e2e.py
python/cugraph/cugraph/tests/generators/test_rmat.py
python/cugraph/cugraph/tests/generators/test_rmat_mg.py
python/cugraph/cugraph/tests/sampling/test_bulk_sampler.py
python/cugraph/cugraph/tests/structure/test_graph_mg.py
python/cugraph/cugraph/tests/traversal/test_sssp.py
python/cugraph/cugraph/traversal/sssp.py

We need to update flake8 to fix a false-positive that appears with older flake8 versions on Python 3.12.

Update flake8 to 7.1.1.

---

python/nx-cugraph/nx_cugraph/classes/graph.py
python/nx-cugraph/nx_cugraph/tests/test_pagerank.py

Graph input with duplicate edges intended for `Graph`/`DiGraph` instances resulted in internal PLC `SGGraph` instances with duplicate edges, which were effectively treated as MultiGraphs and caused incorrect results from algorithms like `pagerank`.
This PR sets the `drop_multi_edges` PLC `SGGraph` ctor option to have PLC remove duplicate edges on `SGGraph` creation.
The overhead to drop duplicate edges for non-MultiGraphs is negligible, and in the case of a large test graph (wikipedia data, 37.5M nodes, 464.5M edges) resulted in <s>an overall _speedup_ for pagerank going from 12.2 seconds to 10.7 seconds on my workstation, likely due to fewer edges to process</s> a minor slowdown from 10.5s to 10.7s. _edit: after several re-runs, the pagerank runtime before the change settled to 10.5, and …

Drops duplicate edges in non-MultiGraph PLC `SGGraph` instances

---

conda/environments/all_cuda-118_arch-x86_64.yaml
conda/environments/all_cuda-125_arch-x86_64.yaml
conda/recipes/libcugraph/conda_build_config.yaml
cpp/include/cugraph/mtmg/instance_manager.hpp
cpp/include/cugraph/mtmg/resource_manager.hpp
cpp/tests/mtmg/multi_node_threaded_test.cu
dependencies.yaml

Contributes to https://github.com/rapidsai/build-planning/issues/102
Some RAPIDS libraries are using `ncclCommSplit()`, which was introduced in `nccl==2.18.1.1`. This is part of a series of PRs across RAPIDS updating libraries' pins to `nccl>=2.18.1.1` to ensure they get a new-enough version that supports that.

bump NCCL floor to 2.18.1.1, include nccl.h where it's needed

---

cpp/tests/CMakeLists.txt
rapids_config.cmake

`rapids_test_add()` does not install the executables we need, because it's checking the value of `${MPIEXEC_EXECUTABLE}` and seeing that it's not a target. Install the target separately.

Install mg test executables

---

ci/build_docs.sh
ci/build_python.sh
ci/test_cpp.sh
ci/test_notebooks.sh
ci/test_python.sh
ci/test_wheel_cugraph-dgl.sh
conda/environments/all_cuda-118_arch-x86_64.yaml
conda/environments/all_cuda-125_arch-x86_64.yaml
conda/recipes/cugraph-dgl/meta.yaml
conda/recipes/cugraph-pyg/meta.yaml
dependencies.yaml
docs/cugraph/source/graph_support/DGL_support.md
docs/cugraph/source/wholegraph/installation/container.md
python/cugraph-dgl/README.md
python/cugraph-dgl/conda/cugraph_dgl_dev_cuda-118.yaml
python/cugraph-pyg/conda/cugraph_pyg_dev_cuda-118.yaml

We were pulling the wrong packages because the PyTorch version constraint wasn't tight enough.  Hopefully these sorts of issues will be resolved in the `cugraph-gnn` repository going forward, where we can pin a specific pytorch version for testing.

Constrain versions of PyTorch and CI artifacts in CI Runs, upgrade to dgl 2.4

---

.pre-commit-config.yaml
python/nx-cugraph/_nx_cugraph/__init__.py
python/nx-cugraph/nx_cugraph/tests/test_ego_graph.py

This run `make` in `python/nx-cugraph` directory and update the pre-commit hook.
Also fixes `ego_graph` tests to check `nx.config.fallback_to_nx` configuration.

Update nx-cugraph to NetworkX 3.4

---

python/nx-cugraph/README.md

This PR updates the nx-cugraph README with the new `NX_CUGRAPH_AUTOCONFIG` variable.

Update `nx-cugraph` README with New Env Variable

---

benchmarks/nx-cugraph/pytest-based/run-main-benchmarks.sh

Short PR. Removes a flag preventing benchmarks from being run in a script.

Remove `--collect-only` Option Left by Accident

---

conda/recipes/cugraph/meta.yaml

This project is incompatible with newer versions of `cuda-python`. This puts ceilings of `<=11.8.3` (CUDA 11) and `<=12.6.0` (CUDA 12) on that library.
Those ceilings should be removed and replaced with `!=` constraints once new releases of `cuda-python` are up that this project is compatible with.
See https://github.com/rapidsai/build-planning/issues/116 for more information.

Put a ceiling on cuda-python

---

cpp/tests/link_analysis/mg_hits_test.cpp

Increase max_iterations in MG HITS tests (with edge masking).
With masking, we may end up with different graphs with different numbers of GPUs; this results in higher iteration counts for convergence for certain GPU counts. Increase the maximum iteration count to consider this.

Increase max_iterations in MG HITS TEST

---

.devcontainer/Dockerfile
.devcontainer/cuda11.8-pip/devcontainer.json
.github/workflows/pr.yaml

Contributes to https://github.com/rapidsai/build-planning/issues/118
Proposes the following changes for pip devcontainers:
* use UCX 1.17 (ref: https://github.com/rapidsai/cugraph-gnn/pull/79#discussion_r1861029925)
* prefer system installation of ucx to the one provided by the `libucx-cu{11,12}` wheels (ref: https://github.com/rapidsai/devcontainers/pull/421#issuecomment-2502324982)
And one other related change:
* skip most CI when a PR only changes files in the `.devcontainer/` directory (this was incorrectly spelled `.devcontainers/` before)

pip devcontainers: use UCX 1.17, prefer system installation

---

cpp/libcugraph_etl/src/renumbering.cu

We are planning to migrate to CCCL 2.7.0 in RAPIDS 25.02. I found a compilation error in `libcugraph_etl` that is fixed by removing a reference `&` from a device comparator, and passing the parameters by value instead.
This is a pretty small fix but I expect we will want to build 24.12 with newer CCCL versions for DLFW releases. To avoid needing a backport for DLFW, I am targeting 24.12 with this change. I can retarget to 25.02 if desired.
This is extracted from #4743, but that PR shouldn't be merged (it includes testing changes that are not intended for merge).

Fix CCCL 2.7.0-rc2 compile issue by removing reference from values.

---

conda/recipes/cugraph/meta.yaml

Now that some upstream bugs have been fixed, we can allow cuda-python 12.6.2 and 11.8.5.
See https://github.com/NVIDIA/cuda-python/issues/226#issuecomment-2472355738 for more information.

Remove upper bounds on cuda-python to allow 12.6.2 and 11.8.5

---

conda/environments/all_cuda-118_arch-x86_64.yaml
conda/environments/all_cuda-125_arch-x86_64.yaml
dependencies.yaml
python/cugraph/cugraph/tests/data_store/test_gnn_feat_storage_wholegraph.py

Set Max PyTorch Version, Skip 11.4 Tests Using WholeGraph

[BUG] Set Max PyTorch Version, Skip 11.4 Tests Using WholeGraph

---

conda/recipes/cugraph/meta.yaml

We require a newer cuda-python lower bound for new features and to use the new layout.
This will fix a number of errors observed when the runtime version of cuda-python is older than the version used to build packages using Cython features from cuda-python.
See https://github.com/rapidsai/build-planning/issues/117#issuecomment-2524250915 for details.

Update cuda-python lower bounds to 12.6.2 / 11.8.5

---

conda/environments/all_cuda-118_arch-x86_64.yaml
conda/environments/all_cuda-125_arch-x86_64.yaml
dependencies.yaml
python/cugraph/pyproject.toml

cuGraph depends on `cuda-python` but does not currently list that dependency. This PR adds it.

Add cuda-python dependency

---

conda/environments/all_cuda-118_arch-x86_64.yaml
conda/environments/all_cuda-125_arch-x86_64.yaml
dependencies.yaml

See https://github.com/rapidsai/cuvs/pull/554, the switch to pip for Breathe in #4839 is no longer required.

Get breathe from conda

---

benchmarks/cugraph/pytest-based/bench_algos.py
ci/notebook_list.py
python/cugraph/cugraph/traversal/ms_bfs.py
python/cugraph/cugraph/utilities/utils.py

This PR removes some utilities that were updated in https://github.com/rapidsai/cugraph/pull/4830 but are no longer needed.
xref: https://github.com/rapidsai/build-planning/issues/117

Remove unnecessary CUDA utilities

---

cpp/src/community/leiden_impl.cuh
cpp/tests/community/leiden_test.cpp
cpp/tests/community/mg_leiden_test.cpp
python/cugraph/cugraph/community/leiden.py
python/cugraph/cugraph/dask/community/leiden.py
python/cugraph/cugraph/tests/community/test_leiden.py
python/cugraph/cugraph/tests/community/test_leiden_mg.py

Our current implementation of Leiden can return non contiguous cluster IDs however, there is an unused utility function [relabel_cluster_ids](https://github.com/rapidsai/cugraph/blob/branch-25.02/cpp/src/community/leiden_impl.cuh#L601:L604) that serves the purpose of relabeling.
This PR
- Addresses the Leiden numbering issue from [4791](#4791)  by calling `relabel_cluster_ids` after flattening the dendrogram. 
- Fixes a bug in the MG python API of Leiden which requires a different seed for each GPU in the C++ API
- Add SG and MG C++ tests
- Add a python SG and MG test capturing the numbering issue
closes #4791

Address Leiden numbering issue

---

dependencies.yaml
python/cugraph/pyproject.toml

Similar to #4854 
`cugraph-cu{11,12}` has a hard runtime dependency on `pylibraft`:
https://github.com/rapidsai/cugraph/blob/dd228f9f1bea23b74b17dc0f939ff1b0b15cee4f/python/cugraph/cugraph/dask/comms/comms.py#L29
But doesn't declare that dependency for wheels.
This PR explicitly declares it.
This only affects wheels... this dependency is correctly declared in the `cugraph` conda packages.
https://github.com/rapidsai/cugraph/blob/dd228f9f1bea23b74b17dc0f939ff1b0b15cee4f/conda/recipes/cugraph/meta.yaml#L90
Other dependencies of `cugraph` pull it in.

cugraph: declare pylibraft dependency for wheels

---

cpp/include/cugraph/algorithms.hpp
cpp/include/cugraph/detail/collect_comm_wrapper.hpp
cpp/include/cugraph/detail/shuffle_wrappers.hpp
cpp/include/cugraph/graph_functions.hpp
cpp/include/cugraph/graph_generators.hpp
cpp/include/cugraph/legacy/functions.hpp
cpp/include/cugraph/legacy/graph.hpp
cpp/include/cugraph/sampling_functions.hpp

Adding doxygen groups in cpp to show api

added doxygen instrumentation to various cpp include files to use in doxygen

---

benchmarks/cugraph/standalone/bulk_sampling/bench_cugraph_training.py
benchmarks/cugraph/standalone/bulk_sampling/trainers/pyg/trainers_pyg.py
python/utils/gpu_metric_poller.py

In the PyNVML 12 upgrade, the `pynvml` package now depends on `nvidia-ml-py`. However `nvidia-ml-py` does not supply the `smi` submodule. To avoid clobbering the package, this module was moved from the `pynvml` namespace to `pynvml_utils`. As a result the `import` here needs the same tweak.

Switch to `pynvml_utils.smi` for PyNVML 12

---

conda/environments/all_cuda-125_arch-x86_64.yaml
conda/recipes/cugraph/conda_build_config.yaml
conda/recipes/cugraph/meta.yaml
conda/recipes/libcugraph/conda_build_config.yaml
conda/recipes/libcugraph/meta.yaml
conda/recipes/pylibcugraph/conda_build_config.yaml
conda/recipes/pylibcugraph/meta.yaml
dependencies.yaml

conda-forge is using GCC 13 for CUDA 12 builds. This PR updates CUDA 12 conda builds to use GCC 13, for alignment.
These PRs should be merged in a specific order, see https://github.com/rapidsai/build-planning/issues/129 for details.

Use GCC 13 in CUDA 12 conda builds.

---

ci/build_wheel.sh

Contributes to https://github.com/rapidsai/build-planning/issues/137
Follow-up to #4804
Wheel builds here currently list out some shared library to exclude in `auditwheel repair`, which they pick up transitively via linking to `libraft`.
https://github.com/rapidsai/cugraph/blob/a9c923bb3f4a6a6f5a9d46337adc65d969717567/ci/build_wheel.sh#L42-L49
The version components of those library names can change when those libraries have ABI breakages, for example across CUDA major version boundaries. This proposes replacing specific versions with wildcards, to exclude *all* versions of those libraries.
This is especially relevant given this: https://github.com/rapidsai/raft/pull/2548
For example, the latest `nvidia-cublas-cu11` has `libcublas.so.11` while `nvidia-cublas-cu12` has `libcublas.so.12`.

use wildcards in auditwheel exclusions

---

.github/workflows/pr.yaml
.github/workflows/test.yaml

Due to some failures coming from libraft C++ wheels, CUDA 11 wheel CI will not pass. This PR temporarily disables CUDA 11 wheel tests until those issues can be resolved.
See https://github.com/rapidsai/build-planning/issues/137.

Temporarily skip CUDA 11 wheel CI

---

conda/environments/all_cuda-118_arch-x86_64.yaml
conda/environments/all_cuda-125_arch-x86_64.yaml
conda/recipes/cugraph-service/meta.yaml
dependencies.yaml
python/cugraph-service/server/pyproject.toml
python/cugraph/pyproject.toml

Numba 0.61.0 just got released with couple of breaking changes, this pr is required to unblock the ci.
xref: https://github.com/rapidsai/cudf/pull/17777

Add upper bound to prevent usage of numba 0.61.0

---

.github/workflows/pr.yaml
.github/workflows/test.yaml

Reverts rapidsai/cugraph#4876 now that https://github.com/rapidsai/raft/pull/2548 has landed.

Revert "Temporarily skip CUDA 11 wheel CI"

---

conda/environments/all_cuda-118_arch-x86_64.yaml
conda/environments/all_cuda-125_arch-x86_64.yaml
conda/recipes/cugraph/meta.yaml
conda/recipes/libcugraph/meta.yaml
dependencies.yaml

Contributes to https://github.com/rapidsai/build-planning/issues/142
`ucx-proc` has been unnecessary for conda environments since UCX 1.14, and RAPIDS currently supports UCX 1.15+. This proposes removing that dependency from conda packages and environments here.
See the linked issue for more details.

remove ucx-proc dependency

---

python/cugraph/cugraph/gnn/data_loading/dist_sampler.py

We currently do not output edge labels in the distributed sampler, which breaks some link prediction workflows where the graph contains pre-labeled edges.  This PR adds support for that so these workflows can be enabled.

[BUG] Output Edge Labels in the Distributed Sampler

---

cpp/include/cugraph/utilities/shuffle_comm.cuh
cpp/src/prims/property_op_utils.cuh
cpp/src/traversal/extract_bfs_paths_impl.cuh
cpp/tests/utilities/check_utilities.hpp

We are removing a lot of deprecated thrust features, so replace them by the equivalent `cuda::std` ones

Fix issues when building with upcoming cccl

---

ci/build_wheel.sh
ci/build_wheel_libcugraph.sh
ci/test_wheel_cugraph.sh
ci/test_wheel_pylibcugraph.sh

Uses a retry wrapper for `pip` commands to try to alleviate CI failures due to hash mismatches that result from network hiccups
xref rapidsai/gha-tools#132
This will retry failures that show up in CI like:
```
Collecting nvidia-cublas-cu12 (from libraft-cu12==25.2.*,>=0.0.0a0)
Downloading https://pypi.nvidia.com/nvidia-cublas-cu12/nvidia_cublas_cu12-12.8.3.14-py3-none-manylinux_2_27_aarch64.whl (604.9 MB)
━━━━━━━━━━━━━━━━━━━━━                 350.2/604.9 MB 229.2 MB/s eta 0:00:02
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
nvidia-cublas-cu12 from https://pypi.nvidia.com/nvidia-cublas-cu12/nvidia_cublas_cu12 …
```

Use `rapids-pip-retry` in CI jobs that might need retries

---

cpp/src/mtmg/vertex_result.cuh
cpp/src/prims/detail/per_v_transform_reduce_e.cuh
cpp/src/prims/fill_edge_property.cuh
cpp/src/sampling/negative_sampling_impl.cuh
cpp/src/traversal/od_shortest_distances_impl.cuh

It is deprecated and will be removed in an upcoming release

Replace `thrust::identity` with `cuda::std::identity`

---

cpp/include/cugraph/edge_src_dst_property.hpp
cpp/src/detail/utility_wrappers_impl.cuh
cpp/src/prims/vertex_frontier.cuh
cpp/src/structure/create_graph_from_edgelist_impl.cuh

We are seeing some compiler warnings in CUDA 12.8 build.

Fix CUDA 12.8 build compiler warnings

---

python/cugraph/cugraph/gnn/data_loading/dist_sampler.py

In order to better debug issues with batch distribution, this PR updates the warning message to show how many batches each rank received.  Partially resolves rapidsai/cugraph-gnn#130.

[FIX] Improve the Warning Displayed for Uneven Batch Distributions

---

ci/build_docs.sh
ci/release/update-version.sh
ci/test_cpp.sh
ci/test_notebooks.sh
ci/test_python.sh
dependencies.yaml

Issue: https://github.com/rapidsai/build-planning/issues/22

Create Conda CI test env in one step

---

python/cugraph/cugraph/utilities/utils.py

`as_column` previously allowed a string describing the dtype (ex. `"int32"`), but the latest version requires a dtype object (ex. `cp.dtype(cp.int32)`)

Updates call to `as_column` for new requirement on `dtype` arg

---

cpp/include/cugraph/edge_property.hpp

We are seeing spurious compiler warnings like
> error: calling a __host__ function("std::vector<...> ::~vector()") from a __host__ __device__ function("cugraph::edge_property_view_t<...> ::~edge_property_view_t") is not allowed
This is clearly a compiler bug that has been fixed but affects 12.5 which is what runs in CI
Example [here](https://github.com/NVIDIA/cccl/actions/runs/13720179287/job/38373997200?pr=3953#step:6:12629)

Silence compiler warnings about host device destructor

---

cpp/include/cugraph/graph_functions.hpp
cpp/src/structure/remove_multi_edges_impl.cuh

`remove_multi_edges` functions takes `keep_min_edge_value`.
This is set to true when removing multi-edges in a symmetric edge list (which will be used to create an undirected graph) to ensure that the edge list remain symmetric (including edge values).
The existing implementation doesn't work properly if # edge properties > 1.
The existing implementation sorts (src, dst, edge index) and keeps the edge with the minimum index among the multi-edges between src & dst.  This doesn't guarantee that the same (src, dst, edge value) will be selected in both directions.
This PR fixes this bug.

remove_multi_edges bug fix.

---

ci/release/update-version.sh

Add two new dependencies to `update-version.sh`
Skipping CI because this script is not tested in CI

Fix update-version script

---

cpp/include/cugraph/edge_property.hpp

NVCC seems to also incorrectly deduce this in 12.5

[CTK 12.5]: Avoid another compiler issue with host device detection

---

.github/workflows/pr.yaml

This PR adds a filter to skip CUDA 11.4 jobs on PRs as a precursor to enabling them in shared-workflows.
Once the 11.4 issues are fixed, this matrix filter should be removed so 11.4 gets tested on PRs.
xref: rapidsai/build-planning#164

ci: pre-filter 11.4 jobs before they are enabled in shared workflows

---

cpp/include/cugraph/detail/utility_wrappers.hpp
cpp/include/cugraph/graph_functions.hpp
cpp/src/structure/detail/structure_utils.cuh
cpp/src/structure/remove_multi_edges_impl.cuh
cpp/src/structure/remove_multi_edges_sg_v32_e32.cu
cpp/src/structure/remove_multi_edges_sg_v64_e64.cu
cpp/tests/CMakeLists.txt
cpp/tests/structure/remove_multi_edges_test.cpp

We can create a graph from an edge list in a single chunk or multiple chunks (e.g. reading from multiple files, and this has advantage in peak memory requirement).
To support the latter case, this PR updates the `remove_multi_edges` function to take an edge list in multiple chunks.
Tests were previously missing and this PR adds tests as well.

Update remove_multi_edges to support edge list in multiple chunks.

---

.github/workflows/pr.yaml

This PR adds the nightly CI check back and removes the temporarily increase length as nightlies were blocked due to failing changes in RAFT that are now resolved as of https://github.com/rapidsai/raft/actions/runs/13913530930

Revert "temporarily increase the timeout for nightly test failures" (#4957)

---

dependencies.yaml

I noticed that `dependencies.yaml` had a dependency on an `x86_64` compiler on `aarch64`. This was a typo, not an attempt at cross-compilation.

Fix compiler dependency on ARM

---

cpp/include/cugraph/edge_property.hpp

We found the issue to be in some unclear compile issues within libcu++ `not_fn`, so we can revert all those hacks
Revert "Silence compiler warnings about host device destructor (#4960)"
Revert "[CTK 12.5]: Avoid another compiler issue with host device detection (#4971)"

Revert hacks around compile issue with host device deduction

---

.github/workflows/pr.yaml

Now that nightlies are passing, we should be able to test these jobs in PRs.

Revert "ci: pre-filter 11.4 jobs before they are enabled in shared workflows (#4975)"

---

cpp/include/cugraph/detail/utility_wrappers.hpp
cpp/include/cugraph_c/graph_functions.h
cpp/src/c_api/graph_functions.cpp
cpp/src/c_api/graph_sg.cpp
cpp/src/detail/utility_wrappers_32.cu
cpp/src/detail/utility_wrappers_64.cu
cpp/src/detail/utility_wrappers_impl.cuh
python/cugraph/cugraph/dask/traversal/bfs.py
python/cugraph/cugraph/dask/traversal/sssp.py
python/cugraph/cugraph/traversal/bfs.py
python/cugraph/cugraph/traversal/sssp.py
python/pylibcugraph/pylibcugraph/CMakeLists.txt
python/pylibcugraph/pylibcugraph/__init__.py
python/pylibcugraph/pylibcugraph/_cugraph_c/graph_functions.pxd
python/pylibcugraph/pylibcugraph/bfs.pyx
python/pylibcugraph/pylibcugraph/graphs.pxd
python/pylibcugraph/pylibcugraph/graphs.pyx
python/pylibcugraph/pylibcugraph/has_vertex.pyx
python/pylibcugraph/pylibcugraph/sssp.pyx
python/pylibcugraph/pylibcugraph/utils.pyx

This PR leverages the CAPI to optimize the check for vertex existence which can lead to +100x speedup compared to the cudf based version as it can be noticed from the performance figure below
closes #4956

Optimize check for vertex existence

---

cpp/include/cugraph/utilities/misc_utils.cuh
cpp/src/detail/utility_wrappers_impl.cuh
cpp/tests/centrality/betweenness_centrality_validate.cu
cpp/tests/community/egonet_validate.cu
cpp/tests/prims/mg_per_v_pair_transform_dst_nbr_intersection.cu
cpp/tests/prims/mg_per_v_pair_transform_dst_nbr_weighted_intersection.cu
cpp/tests/prims/mg_transform_reduce_dst_nbr_intersection_of_e_endpoints_by_v.cu
cpp/tests/utilities/csv_file_utilities.cu
cpp/tests/utilities/thrust_wrapper.cu
python/cugraph/cugraph/structure/hypergraph.py

Note by @jakirkham this includes C++ and Python fixes needed for CI. Details below:
<hr>
From @alliepiper :
Discovered in CCCL CI.
```
/usr/bin/sccache /home/coder/.conda/envs/rapids/bin/nvcc -forward-unknown-to-host-compiler -ccbin=/home/coder/.conda/envs/rapids/bin/x86_64-conda-linux-gnu-c++ -DCUDA_API_PER_THREAD_DEFAULT_STREAM -DCUTLASS_NAMESPACE=raft_cutlass -DLIBCUDACXX_ENABLE_EXPERIMENTAL_MEMORY_RESOURCE -DRAFT_COMPILED -DRAFT_LOG_ACTIVE_LEVEL=RAPIDS_LOGGER_LOG_LEVEL_INFO -DRAFT_SYSTEM_LITTLE_ENDIAN=1 -DTHRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_CUDA -DTHRUST_DISABLE_ABI_NAMESPACE -DTHRUST_HOST_SYSTEM=THRUST_HOST_SYSTEM_CPP -DTHRUST_IGNORE_ABI_NAMESPACE_ERROR -Dcugraph_EXPORTS -I/home/coder/cugraph/cpp/../thirdparty -I/home/coder/cugraph/cpp/src -I/home/coder/cugraph/cpp/include …
```

Add missing thrust headers & Pass dtype objects to cuDF as_column

---

cpp/tests/CMakeLists.txt

Update C++ test binary file output directory to gtests following RAPIDS convention.

Update C++ test binary file output directory from build/tests to build/gtests

---

python/cugraph/cugraph/gnn/data_loading/bulk_sampler.py
python/cugraph/cugraph/gnn/dgl_extensions/__init__.py

Adds deprecation warnings for BulkSampler, bulk sampling API, and DGL extensions.
This is needed for 25.04 to maintain the standard number of releases for a deprecation before removing the features.

[HOTFIX] Adds deprecation warnings for BulkSampler, bulk sampling API, and DGL extensions.

---

.github/workflows/build.yaml

Adding a matrix filter to the `build.yaml` to fix the issue with artifact name collisions in `libcugraph` builds

Avoid unnecessary libcugraph wheel builds

---

python/cugraph/cugraph/structure/hypergraph.py

From the discussion in https://github.com/rapidsai/cugraph/pull/5023, cugraph appears to be using some private cuDF Python APIs (from `cudf.core`). It appears their usage can be wholly replaced with public APIs which will prevent breakage as cuDF should be at liberty to modify private functionality.
This PR will require https://github.com/rapidsai/cudf/pull/18485 to be merged first.

Avoid private cuDF Python APIs

---

cpp/src/prims/detail/sample_and_compute_local_nbr_indices.cuh
cpp/src/traversal/od_shortest_distances_impl.cuh

1. Added  #include <cuda/std/cmath> for correct cuda::std::log reference in sample_and_compute_local_nbr_indices.cuh
Without proper include, the following error would be raised during building libcugraph in my environment:
```
cpp/src/prims/detail/sample_and_compute_local_nbr_indices.cuh([[1994|2006|2260|2272]]):
error: namespace "cuda::std" has no member "log"
return cuda::std::min(-cuda::std::log(r) / b, std::numeric_limits<bias_t>::max());
```
2. Update od_shortest_distances_impl.cuh, fix missing required parameter: invalid_distance in struct e_op_t
Without proper include, the following error would be raised during building libcugraph in my environment:
```
cpp/src/traversal/od_shortest_distances_impl.cuh(143):
Build log is lost, but the line 143 would complain on missing variable …
```

Added  #include <cuda/std/cmath> for correct cuda::std::log reference

---

ci/test_wheel_cugraph.sh
ci/test_wheel_pylibcugraph.sh

Fixes the `libcugraph*.whl is not a valid wheel filename.` bug in the wheel test steps of `pylibcugraph` and `cugraph`on Github CI

[BUGFIX] Fixed quoting in wheel paths in cugraph and pylibcugraph tests

---

.github/workflows/build.yaml
.github/workflows/pr.yaml
.github/workflows/test.yaml
.github/workflows/trigger-breaking-change-alert.yaml
conda/environments/all_cuda-118_arch-aarch64.yaml
conda/environments/all_cuda-118_arch-x86_64.yaml
conda/environments/all_cuda-128_arch-aarch64.yaml
conda/environments/all_cuda-128_arch-x86_64.yaml
dependencies.yaml
python/cugraph-service/client/pyproject.toml
python/cugraph-service/server/pyproject.toml
python/cugraph/pyproject.toml
python/pylibcugraph/pyproject.toml

Contributes to https://github.com/rapidsai/build-planning/issues/120
This PR adds support for Python 3.13.
This is part of ongoing work to add Python 3.13 support across RAPIDS.
It temporarily introduces a build/test matrix including Python 3.13, from https://github.com/rapidsai/shared-workflows/pull/268.
A follow-up PR will revert back to pointing at the `branch-25.06` branch of `shared-workflows` once all
RAPIDS repos have added Python 3.13 support.
CI here is expected to fail until all of this project's upstream dependencies support Python 3.13.
This can be merged whenever all CI jobs are passing.

Add support for Python 3.13

---

python/cugraph/cugraph/dask/common/part_utils.py
python/cugraph/cugraph/structure/graph_implementation/simpleDistributedGraph.py

Removes the invalid keyword argument `pure=False` from `Client.compute` calls. Hoping to fix https://github.com/rapidsai/cugraph/actions/runs/15036791514/job/42294643137?pr=5075#step:9:13232

Remove pure=False from client.compute calls

---

.devcontainer/cuda12.8-conda/devcontainer.json
.devcontainer/cuda12.8-pip/devcontainer.json
.github/workflows/build.yaml
.github/workflows/pr.yaml
.github/workflows/test.yaml
.github/workflows/trigger-breaking-change-alert.yaml
conda/environments/all_cuda-128_arch-aarch64.yaml
conda/environments/all_cuda-128_arch-x86_64.yaml
dependencies.yaml

This PR reverts shared-workflows branches to `branch-25.06` and ensures builds use CUDA 12.8.
CUDA 12.9 will be used in the test matrix but not for builds in RAPIDS 25.06. See https://github.com/rapidsai/build-planning/issues/173#issuecomment-2882179838 for more information.

Finish CUDA 12.9 migration and use branch-25.06 workflows

---

cpp/include/cugraph/edge_src_dst_property.hpp
cpp/src/community/approx_weighted_matching_impl.cuh
cpp/src/community/detail/common_methods.cuh
cpp/src/community/detail/maximal_independent_moves.cuh
cpp/src/community/detail/refine_impl.cuh
cpp/src/components/mis_impl.cuh
cpp/src/components/vertex_coloring_impl.cuh
cpp/src/components/weakly_connected_components_impl.cuh
cpp/src/traversal/sssp_impl.cuh

In SG, the vertex range of edge source/destination property values coincide with the local vertex partition size; so, creating owning data structures for both vertex property values & edge source|destination property values waste memory.
Users can directly call detail::edge_endpoint_property_view_t constructor functions to avoid this (this was considered as tricks for advanced users). To make this easier, this PR adds non-detail space utility functions.

Utility functions to create an edge_src|dst_property view objects.

---

ci/test_python.sh

Adds `test_node2vec` to temporary non-xdist test list.
This is in response to the failed nightly test run [here](https://github.com/rapidsai/cugraph/actions/runs/15131078012/job/42532125240).

Adds `test_node2vec` to temporary non-xdist test list

---

conda/environments/all_cuda-118_arch-aarch64.yaml
conda/environments/all_cuda-118_arch-x86_64.yaml
conda/environments/all_cuda-128_arch-aarch64.yaml
conda/environments/all_cuda-128_arch-x86_64.yaml
dependencies.yaml
python/cugraph/pyproject.toml

The 25.6 dependency probably stuck in through a forward merge.

Fix pylibcudf dependency

---

.github/workflows/build.yaml
.github/workflows/pr.yaml
.github/workflows/test.yaml
ci/build_wheel.sh
ci/build_wheel_cugraph.sh
ci/build_wheel_libcugraph.sh
ci/build_wheel_pylibcugraph.sh
ci/test_wheel_cugraph.sh
ci/test_wheel_pylibcugraph.sh

Proposes a batch of small, mostly-unrelated changes to building and packaging.
These are all part of RAPIDS-wide efforts to make it easier to reproduce CI locally and to use artifacts from one project's CI in another project's CI.
Contributes to https://github.com/rapidsai/build-planning/issues/178
* prevents triggering expensive CI jobs based on PRs modifying `ci/release/update-version.sh`
Contributes to https://github.com/rapidsai/shared-workflows/issues/356
* explicitly provides an input for `script` to workflows using it, instead of relying on a default value coming from the workflow file
Contributes to https://github.com/rapidsai/shared-workflows/issues/337
* switches from input `run_script` to `script` in uses of the `custom-job` workflow
Contributes to …

use 'rapids-init-pip' in wheel CI, other CI changes

---

cpp/tests/components/mg_weakly_connected_components_test.cpp
cpp/tests/components/weakly_connected_components_test.cpp

WCC works with edge masking but our C++ tests didn't test with edge masking. This PR adds WCC C++ tests with edge masking.

Test WCC with edge masking

---

python/cugraph/cugraph/structure/graph_classes.py
python/cugraph/cugraph/structure/graph_implementation/simpleDistributedGraph.py
python/cugraph/cugraph/structure/graph_implementation/simpleGraph.py
python/cugraph/cugraph/tests/structure/test_convert_matrix.py
python/cugraph/cugraph/tests/structure/test_graph.py
python/cugraph/cugraph/tests/structure/test_graph_mg.py
python/cugraph/cugraph/tests/structure/test_multigraph.py

A breaking change was introduced few releases ago that modifies the way an undirected graph is created. In fact, the method symmetrizing the edgelist was there used to be a cudf/dask_cudf based method that symmetrizes the edgelist however, this operation is now supported internally during the graph creation through our C/C++ API with the flag `symmetrize` and the edgelist is exposed through [decompress_to_edgelist ](https://github.com/rapidsai/cugraph/pull/4750).
This PR leverages the method `decompress_to_edgelist` to extract the symmetric edges which is then leverage by the method `view_edge_list` and `number_of_edges`
closes #5003 
closes #4976

Update method retrieving the edgelist

---

cpp/src/prims/detail/per_v_transform_reduce_e.cuh
cpp/src/prims/vertex_frontier.cuh
cpp/src/sampling/detail/shuffle_and_organize_output_impl.cuh
cpp/tests/centrality/betweenness_centrality_reference.hpp

This fixes build errors occurred in https://github.com/rapidsai/cugraph/pull/5124 + add workarounds to silence (spurious) compiler warnings.

Fix build error with gcc 14.

---

.github/workflows/build.yaml
.github/workflows/pr.yaml
.github/workflows/test.yaml

Contributes to https://github.com/rapidsai/shared-workflows/issues/376
* adds descriptions for all inputs to workflows triggered by `workflow_dispatch`
Contributes to https://github.com/rapidsai/shared-workflows/issues/379
* removes input `enable_check_symbols` for `conda-cpp-checks` workflow... no longer needed as of https://github.com/rapidsai/shared-workflows/pull/382
The input descriptions show up in the UI when you go to trigger these workflows. Like this:
I'm hoping that will make it easier for developers to manually trigger workflows. Inspired by being asked multiple times "what format is `date` supposed to be in?".
Removing `enable_check_symbols` here is a step towards completely removing that always-true input, as part of https://github.com/rapidsai/shared-workflows/issues/379

add docs on CI workflow inputs

---

cpp/tests/c_api/legacy_mst_test.c

A change in the Raft API was merged to add support for graph with identical vertices. However, because of the new random weights being added to each edge weight to break-tie, it leads to a different but valid MST. The CAPI test hence has a different hardcoded MST result. This PR updates the test accordingly.

Update MST test

---

conda/environments/all_cuda-129_arch-aarch64.yaml
conda/environments/all_cuda-129_arch-x86_64.yaml
dependencies.yaml

This removes the PyTorch upper bound to ensure we can test with current versions.

Relax PyTorch pinning to >=2.3.

---

cpp/include/cugraph/graph_functions.hpp
cpp/src/c_api/decompress_to_edgelist.cpp
cpp/src/structure/decompress_to_edgelist_impl.cuh
cpp/src/structure/decompress_to_edgelist_mg_v32_e32.cu
cpp/src/structure/decompress_to_edgelist_mg_v64_e64.cu
cpp/src/structure/decompress_to_edgelist_sg_v32_e32.cu
cpp/src/structure/decompress_to_edgelist_sg_v64_e64.cu
cpp/tests/cores/k_core_validate.cu

If the optional large buffer type is specified, the decompressed edge list will be placed in a large buffer (which is currently host pinned memory).
This will slightly simplify the current Graph 500 test code (https://github.com/rapidsai/cugraph/blob/branch-25.08/cpp/tests/traversal/mg_graph500_bfs_test.cu#L304); which generates the edge list using the default memory resource and copy to the large memory buffer. With this update, this two steps can be merged to a single step.
Breaking as one additional input parameter is added to a public function. But unless the caller has been explicitly specifying `do_expensive_check`, no change will be necessary as the default value (std::nullopt) is provided.

Update decompress_to_edgelist to take an optional large buffer type as an input parameter.

---

cpp/src/components/weakly_connected_components_impl.cuh
cpp/src/prims/per_v_pair_transform_dst_nbr_intersection.cuh
cpp/src/prims/update_edge_src_dst_property.cuh
cpp/src/sampling/detail/update_temporal_edge_mask_impl.cuh
cpp/src/sampling/random_walks_impl.cuh
cpp/src/traversal/sssp_impl.cuh

update_edge_src|dst_property has two versions.
One that updates the values for the entire vertex range, and the second one that takes a vertex list to update.
In the second version, it currently asks users to provide the property values for the entire vertex partition range (same to the first version, the primitives internally gather the values). This behavior is counter intuitive and became the sources of bugs recently.
In this PR, the primitive is updated to take property values in an array which has the size of the vertex list.

Update update_edge_src|dst_property behavior (with vertex list)

---

ci/test_python.sh

Skips PG benchmarks for cyber datasets.
This is temporary until a better fix that allows these tests to run with `pytest-xdist` is done.

[HOTFIX] Skips PG benchmarks for cyber datasets

---

ci/release/update-version.sh
dependencies.yaml

This project no longer has any dependency on `cugraph-pyg` or `pylibwholegraph`.
This removes some lingering configuration for them in `dependencies.yaml` and `update-version.sh`.
Discovered while working on #5236. Getting this merged soon would make the diff there a bit smaller.
Found like this:
```shell
git grep -i pyg
git grep -i wholegraph
```

remove cugraph-pyg and wholegraph configuration

---

python/cugraph/cugraph/testing/mg_utils.py

On a tegra machine which has a single GPU and CPU memory pool we can't request spilling back to CPU since it doesn't make sense. So on those style of machines we don't set a limit

mg_util supports running on tegra like machines

---

dependencies.yaml

Follow-up to #5236
There, I intended to introduce a dependency on `torch` nightly wheels for CUDA 13, but made a typo in the `dependencies.yaml` filter. This fixes that, so that wheels for the correct `torch` variant + version will be installed in wheel-testing CI jobs here.

fix pytorch requirement for CUDA 13 builds

---

cpp/include/cugraph/algorithms.hpp
cpp/include/cugraph_c/layout_algorithms.h
cpp/src/c_api/legacy_fa2.cpp
cpp/src/layout/legacy/barnes_hut.cuh
cpp/src/layout/legacy/bh_kernels.cuh
cpp/src/layout/legacy/exact_fa2.cuh
cpp/src/layout/legacy/exact_repulsion.cuh
cpp/src/layout/legacy/fa2_kernels.cuh
cpp/src/layout/legacy/force_atlas2.cu
cpp/tests/layout/legacy/force_atlas2_test.cu
python/cugraph/cugraph/layout/force_atlas2.py
python/cugraph/cugraph/tests/layout/test_force_atlas2.py
python/pylibcugraph/pylibcugraph/_cugraph_c/layout_algorithms.pxd
python/pylibcugraph/pylibcugraph/force_atlas2.pyx

This is a "quick" follow-up to https://github.com/rapidsai/cugraph/pull/5260 (and https://github.com/rapidsai/cugraph/pull/5213) and https://github.com/rapidsai/nx-cugraph/pull/191 to add vertex mass to the API. This will allow `nx-cugraph` to better match the networkx API.
This required changing the dtype of the mass arrays from integral to float32.
As time permits, I plan to add a test to show that increasing mass of a vertex increases its distance to other vertices. The plan is to also update `nx-cugraph` to use this parameter.

`force_atlas2`: allow vertex mass to be given by the user
